package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemSettings model in separate Go files,
// using filenames that reflect their purpose (e.g., system_settings_validation.go,
// system_settings_serialization.go). Avoid throwing all logic into a
// single system_settings_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemSettingsMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemSettings struct {
	document.DocumentModel
	ID        string                  `anansi:"_id_,required=true" json:"_id_"`
	Key       string                  `anansi:"key,required=true" json:"key"`
	Metadata  *SystemSettingsMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	TenantID  *string                 `anansi:"tenant_id,required=false,omitempty" json:"tenant_id,omitempty"`
	UpdatedBy *string                 `anansi:"updated_by,required=false,omitempty" json:"updated_by,omitempty"`
	Value     map[string]any          `anansi:"value,required=true" json:"value"`
}

// GetID returns the document identifier for SystemSettings.
func (m *SystemSettings) GetID() string {
	return m.ID
}

// NewSystemSettings creates and initializes a new SystemSettings
func NewSystemSettings(model SystemSettings) *SystemSettings {
	return document.New(&model)
}

// SystemSettingss is a type-safe collection for SystemSettings
type SystemSettingss struct {
	*collection.ModelCollection[*SystemSettings]
}

const SystemSettingssCollectionName = "_settings_"

var (
	systemSettingssModelMu sync.Mutex
	systemSettingssModel   *SystemSettingss
)

// InitSystemSettingssModel must be called once at startup to configure and
// construct the SystemSettings model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemSettingssModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemSettings]) (*SystemSettingss, error) {
	systemSettingssModelMu.Lock()
	defer systemSettingssModelMu.Unlock()
	if systemSettingssModel != nil {
		return systemSettingssModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemSettingssCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSettingssModel").
			WithPath("_settings_")
	}
	mc, err := collection.NewModelCollection[*SystemSettings](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSettingssModel").
			WithPath("_settings_")
	}
	systemSettingssModel = &SystemSettingss{ModelCollection: mc}
	return systemSettingssModel, nil
}

// SystemSettingssModel returns the singleton SystemSettings model.
func SystemSettingssModel() (*SystemSettingss, error) {
	systemSettingssModelMu.Lock()
	defer systemSettingssModelMu.Unlock()
	if systemSettingssModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemSettingssModel not initialized — call InitSystemSettingssModel first").
			WithOperation("SystemSettingssModel")
	}
	return systemSettingssModel, nil
}

// Deprecated: DangerouslyResetSystemSettingssModel clears the cached singleton so
// InitSystemSettingssModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemSettingssModel() {
	systemSettingssModelMu.Lock()
	defer systemSettingssModelMu.Unlock()
	if systemSettingssModel == nil {
		return
	}
	_ = systemSettingssModel.Close()
	systemSettingssModel = nil
}
