// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/audit/model/access_log.schema.json
// Date: 2026-08-28T08:14:53Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _audit_log__0_0_0_to_1_0_0 returns a migration plan for _audit_log__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _audit_log__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__audit_log__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _audit_log__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__audit_log__1_0_0 is the target schema serialized from core/system/audit/model/access_log.schema.json.
var target__audit_log__1_0_0_json = []byte(`{
  "description": "Audit trail of security-relevant actions: who did what, to what, when, from where, and with what outcome.",
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69cc-7014-befa-b56800e9839b": {
      "description": "Distributed trace/correlation ID linking this event to related events across services.",
      "name": "trace_id",
      "type": "string"
    },
    "019fdc60-69cd-7014-895e-bc5dbf1b49b3": {
      "description": "Set when actor_id is acting on behalf of another identity (delegation/impersonation), e.g. an admin or service acting for a user.",
      "name": "on_behalf_of_id",
      "type": "string"
    },
    "019fdc60-69cd-7015-8e28-7c852d323fc7": {
      "description": "Non-secret session/token identifier. Never store raw credentials, tokens, or secrets here.",
      "name": "session_id",
      "type": "string"
    },
    "019fdc60-69cd-7016-8969-e934b8ae87fd": {
      "description": "Deployment region or data center of the emitting service.",
      "name": "region",
      "type": "string"
    },
    "019fdc60-69cd-7017-a753-51fbbcd816d7": {
      "description": "Additional producer-specific context that doesn't warrant a first-class field.",
      "name": "metadata",
      "type": "record"
    },
    "019fdc60-69cd-7018-9ed4-55b863a12509": {
      "description": "Hash of this record chained with the previous record's hash, for tamper-evidence. Populated by the log writer, never by the emitting service.",
      "name": "integrity_hash",
      "type": "string"
    },
    "019fdc60-69cd-7019-8f6b-9e9df3fbd2b4": {
      "description": "Unique identifier for this audit record itself (UUIDv7).",
      "name": "event_id",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019fdc60-69cd-701a-994a-1c1ae18f8aa0": {
      "description": "ISO-8601 timestamp of when the audited action actually took place.",
      "name": "occurred_at",
      "required": true,
      "type": "string"
    },
    "019fdc60-69cd-701b-9fcb-c60a227a5a22": {
      "description": "ISO-8601 timestamp of when this record was written. Compare with occurred_at to detect ingestion lag or clock skew.",
      "name": "recorded_at",
      "required": true,
      "type": "string"
    },
    "019fdc60-69cd-701c-9625-714db6ad22aa": {
      "description": "Identifier of who or what performed the action. Use \"system\" for automated/internal actors.",
      "name": "actor_id",
      "required": true,
      "type": "string"
    },
    "019fdc60-69cd-701d-ada2-5b3846cc57f6": {
      "description": "Identifier of the specific resource instance acted upon.",
      "name": "resource_id",
      "type": "string"
    },
    "019fdc60-69cd-701e-a3b8-c249b3bf840b": {
      "name": "status",
      "required": true,
      "schema": {
        "id": "019fdc60-69cd-702f-a18e-5224f8739be3"
      },
      "type": "enum"
    },
    "019fdc60-69cd-701f-9f5d-05663af5a8a9": {
      "name": "severity",
      "schema": {
        "id": "019fdc60-69cd-7030-934c-79ac44521d40"
      },
      "type": "enum"
    },
    "019fdc60-69cd-7020-925c-b30e646b2ebf": {
      "description": "Human-readable error detail. Avoid embedding secrets or PII beyond what's already logged elsewhere.",
      "name": "error_message",
      "type": "string"
    },
    "019fdc60-69cd-7021-83cc-7d8760013d3b": {
      "name": "actor_type",
      "required": true,
      "schema": {
        "id": "019fdc60-69cd-702c-901b-0de264bee51c"
      },
      "type": "enum"
    },
    "019fdc60-69cd-7022-bff0-58fd34b1af45": {
      "description": "The kind of resource acted upon, e.g. \"invoice\", \"user_account\", \"api_key\".",
      "name": "resource_type",
      "required": true,
      "type": "string"
    },
    "019fdc60-69cd-7023-ae15-b565086044a3": {
      "description": "Duration of the underlying operation, in milliseconds.",
      "name": "latency_ms",
      "type": "integer"
    },
    "019fdc60-69cd-7024-8716-c48cd2883a60": {
      "description": "Fine-grained, human-readable event taxonomy, e.g. \"user.login.failed\" or \"invoice.updated\". Complements operation/resource_type with producer-specific detail.",
      "name": "event_name",
      "required": true,
      "type": "string"
    },
    "019fdc60-69cd-7025-bac1-e03ab63af3cd": {
      "description": "Identifier of the originating request, if applicable.",
      "name": "request_id",
      "type": "string"
    },
    "019fdc60-69cd-7026-9f23-5657bd0fbef5": {
      "name": "auth_method",
      "schema": {
        "id": "019fdc60-69cd-702d-95c6-94c9d47ea239"
      },
      "type": "enum"
    },
    "019fdc60-69cd-7027-b867-7ef2862423b4": {
      "description": "Coarse-grained action category, for consistent filtering across all producers.",
      "name": "operation",
      "required": true,
      "schema": {
        "id": "019fdc60-69cd-702e-a166-2039ac1e6cc1"
      },
      "type": "enum"
    },
    "019fdc60-69cd-7028-993b-c309eed292b5": {
      "description": "Machine-readable error/denial code, present when status is failure, denied, or error.",
      "name": "error_code",
      "type": "string"
    },
    "019fdc60-69cd-7029-98d6-e7e81d36c913": {
      "description": "Originating IP address of the actor.",
      "name": "source_ip",
      "type": "string"
    },
    "019fdc60-69cd-702a-8427-0f80b5df6fd4": {
      "name": "user_agent",
      "type": "string"
    },
    "019fdc60-69cd-702b-ad82-677a7671314a": {
      "description": "The service/component that emitted this audit record.",
      "name": "service_name",
      "required": true,
      "type": "string"
    }
  },
  "indexes": {
    "019f65b3-d3e4-70aa-a5ca-a39c18823c81": {
      "fields": [
        "occurred_at"
      ],
      "name": "idx_occurred_at",
      "order": "desc",
      "type": "normal"
    },
    "019f65b3-d3e4-7395-9c1b-d852a9c19587": {
      "fields": [
        "request_id"
      ],
      "name": "idx_request_id",
      "type": "normal"
    },
    "019f65b3-d3e4-74be-a3a3-7a15bfb48367": {
      "fields": [
        "status"
      ],
      "name": "idx_status",
      "type": "normal"
    },
    "019f65b3-d3e4-7764-bb2d-ca2fef76040d": {
      "fields": [
        "severity"
      ],
      "name": "idx_severity",
      "type": "normal"
    },
    "019f65b3-d3e4-791c-87e6-1a24e489a53f": {
      "fields": [
        "actor_id"
      ],
      "name": "idx_actor_id",
      "type": "normal"
    },
    "019f65b3-d3e4-7941-8dde-35faa7eac266": {
      "fields": [
        "resource_type",
        "resource_id"
      ],
      "name": "idx_resource",
      "type": "normal"
    },
    "019f65b3-d3e4-7a51-9b57-1ed43107b048": {
      "fields": [
        "operation"
      ],
      "name": "idx_operation",
      "type": "normal"
    },
    "019f65b3-d3e4-7a60-b1c0-7bcb6e024155": {
      "fields": [
        "event_id"
      ],
      "name": "idx_event_id",
      "type": "unique"
    },
    "019f65b3-d3e4-7ce0-b413-5d2cc9f4b76f": {
      "fields": [
        "trace_id"
      ],
      "name": "idx_trace_id",
      "type": "normal"
    }
  },
  "name": "_audit_log_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    },
    "019fdc60-69cd-702c-901b-0de264bee51c": {
      "name": "ActorType",
      "type": "string",
      "values": [
        "user",
        "service",
        "system",
        "anonymous"
      ]
    },
    "019fdc60-69cd-702d-95c6-94c9d47ea239": {
      "name": "AuthMethod",
      "type": "string",
      "values": [
        "password",
        "oauth",
        "api_key",
        "mtls",
        "sso",
        "service_account",
        "none"
      ]
    },
    "019fdc60-69cd-702e-a166-2039ac1e6cc1": {
      "name": "Operation",
      "type": "string",
      "values": [
        "create",
        "read",
        "update",
        "delete",
        "login",
        "logout",
        "grant",
        "revoke",
        "execute",
        "other"
      ]
    },
    "019fdc60-69cd-702f-a18e-5224f8739be3": {
      "name": "Status",
      "type": "string",
      "values": [
        "success",
        "failure",
        "denied",
        "error"
      ]
    },
    "019fdc60-69cd-7030-934c-79ac44521d40": {
      "name": "Severity",
      "type": "string",
      "values": [
        "info",
        "warning",
        "critical"
      ]
    }
  },
  "version": "1.0.0"
}
`)

func target__audit_log__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__audit_log__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
