// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/auth/model/token_blocklist.schema.json
// Date: 2026-08-19T09:50:36Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _token_blocklist__0_0_0_to_1_0_0 returns a migration plan for _token_blocklist__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _token_blocklist__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__token_blocklist__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _token_blocklist__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__token_blocklist__1_0_0 is the target schema serialized from core/system/auth/model/token_blocklist.schema.json.
var target__token_blocklist__1_0_0_json = []byte(`{
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69d0-7030-a2de-3d9d06dc7a9c": {
      "name": "jti",
      "required": true,
      "type": "string"
    },
    "019fdc60-69d0-7031-acc0-987358f39789": {
      "name": "exp",
      "required": true,
      "type": "integer"
    },
    "019fdc60-69d0-7032-93bf-fcfaa2a04ea8": {
      "name": "user_id",
      "required": true,
      "type": "string"
    }
  },
  "indexes": {
    "019f32aa-ba8a-7ba1-9ceb-3de9492ab2b2": {
      "fields": [
        "jti"
      ],
      "name": "idx_jti",
      "type": "unique"
    },
    "019f32aa-ba8a-7cef-992c-d4754160bb20": {
      "fields": [
        "exp"
      ],
      "name": "idx_exp",
      "type": "normal"
    }
  },
  "name": "_token_blocklist_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    }
  },
  "version": "1.0.0"
}
`)

func target__token_blocklist__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__token_blocklist__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
