// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/tenants/model/tenant.schema.json
// Date: 2026-08-17T14:00:23Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _tenant__0_0_0_to_1_0_0 returns a migration plan for _tenant__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _tenant__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__tenant__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _tenant__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__tenant__1_0_0 is the target schema serialized from core/system/tenants/model/tenant.schema.json.
var target__tenant__1_0_0_json = []byte(`{
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69de-7059-91f5-2f23e1a9c42f": {
      "default": "active",
      "name": "status",
      "type": "string"
    },
    "019fdc60-69de-705a-8837-7ec75867109b": {
      "name": "metadata",
      "type": "record"
    },
    "019fdc60-69de-705b-aa8c-6b37fdf890e1": {
      "name": "name",
      "required": true,
      "type": "string"
    },
    "019fdc60-69de-705c-b2af-49c3bd023ad4": {
      "name": "domain",
      "type": "string",
      "unique": true
    }
  },
  "name": "_tenant_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    }
  },
  "version": "1.0.0"
}
`)

func target__tenant__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__tenant__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
