// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/apikeys/model/api_key.schema.json
// Date: 2026-08-19T08:40:10Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _api_key__0_0_0_to_1_0_0 returns a migration plan for _api_key__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _api_key__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__api_key__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _api_key__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__api_key__1_0_0 is the target schema serialized from core/system/apikeys/model/api_key.schema.json.
var target__api_key__1_0_0_json = []byte(`{
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69c4-7005-98d9-9f0cb2f9bb44": {
      "name": "environment",
      "type": "string"
    },
    "019fdc60-69c4-7006-a137-50262ef675df": {
      "name": "operations",
      "schema": {
        "id": "019fdc60-69c4-7012-b851-0072ccca431c"
      },
      "type": "array"
    },
    "019fdc60-69c4-7007-92d8-b7fd5d58cbf7": {
      "name": "status",
      "type": "string"
    },
    "019fdc60-69c4-7008-8c96-2de2677a17da": {
      "name": "expiry",
      "type": "string"
    },
    "019fdc60-69c4-7009-b986-1f77c8e16093": {
      "name": "last_used",
      "type": "string"
    },
    "019fdc60-69c4-700a-b59e-0570e18531ff": {
      "name": "limits",
      "schema": {
        "id": "019fdc60-69c4-7013-a460-1cbc930c7a0e"
      },
      "type": "object"
    },
    "019fdc60-69c4-700b-81ba-57b7809eb9e1": {
      "name": "prefix",
      "required": true,
      "type": "string"
    },
    "019fdc60-69c4-700c-82fa-372376861e44": {
      "name": "hash",
      "required": true,
      "type": "string"
    },
    "019fdc60-69c4-700d-b674-73c3651341d1": {
      "name": "usage",
      "type": "integer"
    },
    "019fdc60-69c4-700e-a8a0-2258407eeeb8": {
      "name": "ip",
      "schema": {
        "id": "019fdc60-69c4-7014-9d4b-469f6e0509df"
      },
      "type": "object"
    },
    "019fdc60-69c4-700f-8b76-60aae5a92341": {
      "name": "name",
      "required": true,
      "type": "string"
    },
    "019fdc60-69c4-7010-bf56-dfca364fe145": {
      "name": "userId",
      "required": true,
      "type": "string"
    }
  },
  "metadata": {
    "projections": {
      "APIKeyCreate": {
        "fields": {
          "include": [
            "name",
            "environment",
            "operations",
            "expiry",
            "limits",
            "ip"
          ],
          "optional": [
            "environment",
            "operations",
            "expiry",
            "limits",
            "ip"
          ],
          "required": [
            "name"
          ],
          "tags": {
            "environment": {
              "input": "payload.{name}"
            },
            "expiry": {
              "input": "payload.{name}"
            },
            "ip": {
              "input": "payload.{name}"
            },
            "limits": {
              "input": "payload.{name}"
            },
            "name": {
              "input": "payload.{name}"
            },
            "operations": {
              "input": "payload.{name}"
            }
          }
        }
      },
      "APIKeyPublic": {
        "fields": {
          "exclude": [
            "hash"
          ]
        }
      },
      "APIKeyUpdate": {
        "fields": {
          "include": [
            "_id_",
            "name",
            "status",
            "environment",
            "operations",
            "expiry",
            "limits",
            "ip"
          ],
          "optional": [
            "name",
            "status",
            "environment",
            "operations",
            "expiry",
            "limits",
            "ip"
          ],
          "tags": {
            "_id_": {
              "input": "arguments.key_id"
            },
            "environment": {
              "input": "payload.{name}"
            },
            "expiry": {
              "input": "payload.{name}"
            },
            "ip": {
              "input": "payload.{name}"
            },
            "limits": {
              "input": "payload.{name}"
            },
            "name": {
              "input": "payload.{name}"
            },
            "operations": {
              "input": "payload.{name}"
            },
            "status": {
              "input": "payload.{name}"
            }
          }
        }
      }
    }
  },
  "name": "_api_key_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    },
    "019fdc60-69c4-7011-98b6-abdc97b94c13": {
      "name": "IPCIDR",
      "type": "string"
    },
    "019fdc60-69c4-7012-b851-0072ccca431c": {
      "name": "Operation",
      "type": "string"
    },
    "019fdc60-69c4-7013-a460-1cbc930c7a0e": {
      "fields": {
        "019f32aa-ba8b-7072-99db-4cb04c7d9562": {
          "name": "rph",
          "type": "integer"
        },
        "019f32aa-ba8b-742c-8c32-882547698cff": {
          "name": "rpm",
          "type": "integer"
        }
      },
      "name": "Limits"
    },
    "019fdc60-69c4-7014-9d4b-469f6e0509df": {
      "fields": {
        "019f32aa-ba8b-75ad-b09b-21584dd3a317": {
          "name": "whitelist",
          "schema": {
            "id": "019fdc60-69c4-7011-98b6-abdc97b94c13"
          },
          "type": "array"
        }
      },
      "name": "IPConfig"
    }
  },
  "version": "1.0.0"
}
`)

func target__api_key__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__api_key__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
