// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/settings/model/settings.schema.json
// Date: 2026-08-28T08:14:53Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _settings__0_0_0_to_1_0_0 returns a migration plan for _settings__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _settings__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__settings__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _settings__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__settings__1_0_0 is the target schema serialized from core/system/settings/model/settings.schema.json.
var target__settings__1_0_0_json = []byte(`{
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69db-7056-8ae5-ee245b54e79e": {
      "name": "updated_by",
      "type": "string"
    },
    "019fdc60-69db-7057-9a84-62a67e9a1fa1": {
      "name": "key",
      "required": true,
      "type": "string"
    },
    "019fdc60-69db-7058-b15c-51b410d2aeaf": {
      "name": "value",
      "required": true,
      "type": "record"
    },
    "019fdc60-69db-7059-9b3a-0a986d386ab6": {
      "name": "tenant_id",
      "type": "string"
    }
  },
  "indexes": {
    "019f9324-6da7-7133-860d-c2bfe7ccfb27": {
      "fields": [
        "tenant_id",
        "key"
      ],
      "name": "idx_tenant_key",
      "type": "unique"
    }
  },
  "name": "_settings_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    }
  },
  "version": "1.0.0"
}
`)

func target__settings__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__settings__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
