// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/workflows/model/workflow_definitions.schema.json
// Date: 2026-08-28T08:14:53Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _workflow_definition__0_0_0_to_1_0_0 returns a migration plan for _workflow_definition__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _workflow_definition__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__workflow_definition__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _workflow_definition__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__workflow_definition__1_0_0 is the target schema serialized from core/system/workflows/model/workflow_definitions.schema.json.
var target__workflow_definition__1_0_0_json = []byte(`{
  "description": "Workflow definition storage for the hermes workflow engine",
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "01a04762-d5d3-7605-8ff1-a16932b97e93": {
      "name": "description",
      "type": "string"
    },
    "01a04762-d5d3-7606-967c-a214d71fedd7": {
      "name": "nodes",
      "required": true,
      "type": "record"
    },
    "01a04762-d5d3-7607-af6a-f5f38343acb3": {
      "name": "tenant_id",
      "type": "string"
    },
    "01a04762-d5d3-7608-97d6-e9d4b71ae6df": {
      "name": "created_at",
      "type": "integer"
    },
    "01a04762-d5d3-7609-8cc7-b4d86686c6cf": {
      "name": "name",
      "required": true,
      "type": "string"
    },
    "01a04762-d5d3-760a-a583-0b2787c29668": {
      "name": "edges",
      "required": true,
      "type": "record"
    },
    "01a04762-d5d3-760b-8f4c-043581277d10": {
      "name": "updated_at",
      "type": "integer"
    }
  },
  "name": "_workflow_definition_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    }
  },
  "version": "1.0.0"
}
`)

func target__workflow_definition__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__workflow_definition__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
