// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/system/schedules/model/_scheduled_messages_.schema.json
// Date: 2026-08-19T08:40:10Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _scheduled_messages__0_0_0_to_1_0_0 returns a migration plan for _scheduled_messages__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _scheduled_messages__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__scheduled_messages__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _scheduled_messages__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__scheduled_messages__1_0_0 is the target schema serialized from core/system/schedules/model/_scheduled_messages_.schema.json.
var target__scheduled_messages__1_0_0_json = []byte(`{
  "description": "Cron-triggered message dispatch",
  "fields": {
    "019f4065-0a3d-7ea1-bc46-bbaeed4bfd6d": {
      "name": "_id_",
      "required": true,
      "type": "string",
      "unique": true
    },
    "019f4065-0a3d-7ecf-a2eb-7af6e1fdd6f0": {
      "name": "_metadata_",
      "schema": {
        "id": "019f4065-0a3d-7ed7-8ab1-417acc881135"
      },
      "type": "object"
    },
    "019fdc60-69d9-7050-a014-27d3b781c44c": {
      "name": "disabled",
      "type": "boolean"
    },
    "019fdc60-69d9-7051-ad50-96f5e9967253": {
      "name": "tenant_id",
      "type": "string"
    },
    "019fdc60-69d9-7052-bf86-dc7525a5d331": {
      "name": "user_id",
      "required": true,
      "type": "string"
    },
    "019fdc60-69d9-7053-bd8e-19c311677855": {
      "name": "created_at",
      "type": "integer"
    },
    "019fdc60-69d9-7054-9687-1230f39f5a54": {
      "name": "message",
      "required": true,
      "type": "string"
    },
    "019fdc60-69d9-7055-bb14-0c1fc52a4d37": {
      "name": "input",
      "type": "record"
    },
    "019fdc60-69d9-7056-8456-1e60dbe13811": {
      "name": "cron",
      "required": true,
      "type": "string"
    }
  },
  "name": "_scheduled_messages_",
  "schemas": {
    "019f4065-0a3d-7ed7-8ab1-417acc881135": {
      "fields": {
        "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
          "name": "version",
          "required": true,
          "type": "number"
        },
        "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
          "name": "updated",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-7440-b104-8d774438853a": {
          "name": "checksum",
          "required": true,
          "type": "string"
        },
        "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
          "name": "signature",
          "type": "string"
        },
        "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
          "name": "created",
          "required": true,
          "type": "string"
        },
        "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
          "name": "trace_id",
          "type": "string"
        }
      },
      "name": "_metadata_"
    }
  },
  "version": "1.0.0"
}
`)

func target__scheduled_messages__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__scheduled_messages__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
