// Code generated by anansi. DO NOT EDIT.
// Source: metadata.schema.json

package migrations

import (
	"encoding/json"
	"fmt"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

var metadata_schema_json = []byte(`{
  "name": "_metadata_",
  "fields": {
    "019f32a2-1eb3-7c39-885e-c3d545f981ac": {
      "name": "version",
      "required": true,
      "type": "number"
    },
    "019f32a2-1eb5-72a9-a0d6-086140f78a85": {
      "name": "updated",
      "required": true,
      "type": "string"
    },
    "019f32a2-1eb5-7440-b104-8d774438853a": {
      "name": "checksum",
      "required": true,
      "type": "string"
    },
    "019f32a2-1eb5-774f-abf3-09d64b4dbdd7": {
      "name": "signature",
      "type": "string"
    },
    "019f32a2-1eb5-78b8-971d-ac164c938f2f": {
      "name": "created",
      "required": true,
      "type": "string"
    },
    "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
      "name": "trace_id",
      "type": "string"
    }
  }
}`)

// MetadataSchema returns the merged _metadata_ schema: the framework's base
// fields plus every field declared in metadata.schema.json.
func MetadataSchema() *definition.NestedSchema {
	var ns definition.NestedSchema
	if err := json.Unmarshal(metadata_schema_json, &ns); err != nil {
		panic("invalid embedded metadata schema: " + err.Error())
	}
	return &ns
}

var metadata_dependencies_json = []byte(`[]`)

// MetadataDependencies returns the dependency nested schemas referenced by
// metadata fields, deduplicated by name.
func MetadataDependencies() []*definition.NestedSchema {
	var deps []*definition.NestedSchema
	if err := json.Unmarshal(metadata_dependencies_json, &deps); err != nil {
		panic("invalid embedded metadata dependencies: " + err.Error())
	}
	return deps
}
var trace_schema_json = []byte(`{
  "name": "trace",
  "fields": {
    "019fdc3a-fce9-7d1c-acec-ed552a5254b4": {
      "name": "trace_id",
      "type": "string"
    }
  }
}`)

// TraceSchema returns the schema of the "trace" provider fields.
func TraceSchema() *definition.NestedSchema {
	var ns definition.NestedSchema
	if err := json.Unmarshal(trace_schema_json, &ns); err != nil {
		panic("invalid embedded metadata schema: " + err.Error())
	}
	return &ns
}

// MetadataProviderConfigs returns the entries for DocumentFactoryConfig.Providers,
// one per provider declared in metadata.schema.json. Each entry carries the
// provider's generated schema and dependencies plus the provider func from
// providers.go — assign it straight to the factory config:
//
//	cfg.Providers = migrations.MetadataProviderConfigs()
func MetadataProviderConfigs() []data.MetadataProviderConfig {
	return []data.MetadataProviderConfig{
		{Name: "trace", Schema: TraceSchema(), Dependencies: MetadataDependencies(), Provider: TraceProvider},
	}
}

// ValidateMetadataSchema reports whether the runtime document factory's merged
// metadata schema (data.GetMetadataSchema) matches the schema generated from
// metadata.schema.json. Wire every generated provider schema into
// DocumentFactoryConfig.Providers for them to agree.
func ValidateMetadataSchema() error {
	got, _ := data.GetMetadataSchema()
	want := MetadataSchema()
	gotFields := metadataFieldMap(got)
	wantFields := metadataFieldMap(want)
	for name, f := range wantFields {
		rf, ok := gotFields[name]
		if !ok {
			return fmt.Errorf("metadata: field %q declared in metadata.schema.json is missing from the runtime factory; wire the generated provider into DocumentFactoryConfig.Providers", name)
		}
		if rf.Type != f.Type {
			return fmt.Errorf("metadata: field %q type mismatch: runtime %s vs metadata.schema.json %s", name, rf.Type, f.Type)
		}
	}
	return nil
}

func metadataFieldMap(ns *definition.NestedSchema) map[string]definition.Field {
	out := make(map[string]definition.Field, len(ns.Fields))
	for _, f := range ns.Fields {
		out[string(f.Name)] = f
	}
	return out
}
