// Code generated by anansi. DO NOT EDIT.
// Source: metadata.schema.json
// This file contains provider stubs. Stub bodies are preserved across
// regenerations; edit the bodies to produce the metadata declared for each
// provider. New providers get a stub appended on the next run.

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	rcontext "github.com/asaidimu/hestia/core/runtime/context"
)

// TraceProvider fills the "trace" metadata fields (span_id, trace_id).
func TraceProvider(ctx context.Context, doc data.Documenter) (map[string]any, error) {
	if traceID := rcontext.GetTraceID(ctx); traceID != "" {
		return map[string]any{"trace_id": traceID}, nil
	}
	return nil, nil
}
