// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"
	"sort"

	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	UUID          string
	Collection    string
	From          string
	To            string
	File          string
	Plan          func() *base.MigrationPlan
	SubMigrations []Migration // populated for squash entries
}

// Plain holds all plain (non-squashed) migrations sorted by UUID.
var Plain = []Migration{
	{UUID: "019fdc60-69e6-7baf-905f-065940790cb5", Collection: "_api_key_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e6-7baf-905f-065940790cb5__api_key__major.go", Plan: _api_key__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e7-72cb-b475-56418431fa4e", Collection: "_audit_log_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e7-72cb-b475-56418431fa4e__audit_log__major.go", Plan: _audit_log__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e7-77ed-9200-28e1d2b50d0d", Collection: "_token_blocklist_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e7-77ed-9200-28e1d2b50d0d__token_blocklist__major.go", Plan: _token_blocklist__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e7-7b2b-b9a4-926363ee0a8a", Collection: "_notifications_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e7-7b2b-b9a4-926363ee0a8a__notifications__major.go", Plan: _notifications__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e7-7dfe-9351-0280c45b5852", Collection: "_seed_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e7-7dfe-9351-0280c45b5852__seed__major.go", Plan: _seed__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e8-7253-9471-ff0de910e68d", Collection: "_iam_rule_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e8-7253-9471-ff0de910e68d__iam_rule__major.go", Plan: _iam_rule__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e8-75fe-a7f3-00c0a5c67c33", Collection: "_operation_policy_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e8-75fe-a7f3-00c0a5c67c33__operation_policy__major.go", Plan: _operation_policy__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e8-79c6-ad33-b90836a46f6d", Collection: "_scheduled_messages_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e8-79c6-ad33-b90836a46f6d__scheduled_messages__major.go", Plan: _scheduled_messages__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e8-7d11-8ff3-c5a46f1ebe5d", Collection: "_settings_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e8-7d11-8ff3-c5a46f1ebe5d__settings__major.go", Plan: _settings__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e9-7103-b414-eb8cb7b1a1a7", Collection: "_tenant_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e9-7103-b414-eb8cb7b1a1a7__tenant__major.go", Plan: _tenant__0_0_0_to_1_0_0},
	{UUID: "019fdc60-69e9-74a2-b59f-688f55124176", Collection: "_user_", From: "0.0.0", To: "1.0.0", File: "019fdc60-69e9-74a2-b59f-688f55124176__user__major.go", Plan: _user__0_0_0_to_1_0_0},
	{UUID: "019fdc6c-32ee-7344-b6d7-2c7726b4a8a6", Collection: "_user_", From: "1.0.0", To: "1.0.1", File: "019fdc6c-32ee-7344-b6d7-2c7726b4a8a6__user__patch.go", Plan: _user__1_0_0_to_1_0_1},
	{UUID: "019fdc6e-db3e-7bf6-a1fc-d22d5218fba5", Collection: "_user_", From: "1.0.1", To: "1.0.2", File: "019fdc6e-db3e-7bf6-a1fc-d22d5218fba5__user__patch.go", Plan: _user__1_0_1_to_1_0_2},
	{UUID: "019fefbd-664e-72a2-830e-df744cde3a44", Collection: "_api_key_", From: "1.0.0", To: "1.0.1", File: "019fefbd-664e-72a2-830e-df744cde3a44__api_key__patch.go", Plan: _api_key__1_0_0_to_1_0_1},
}

// Squash holds all squash migrations sorted by UUID.
var Squash = []Migration(nil)

// All merges Plain and Squash, sorted by UUID, and returns them as a single slice.
func All() []Migration {
	all := make([]Migration, 0, len(Plain)+len(Squash))
	all = append(all, Plain...)
	all = append(all, Squash...)
	sort.Slice(all, func(i, j int) bool { return all[i].UUID < all[j].UUID })
	return all
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All() {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %s: %w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %s: %w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %s: %w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %s %s->%s: %w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
