// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"
	"sort"

	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	UUID          string
	Collection    string
	From          string
	To            string
	File          string
	Plan          func() *base.MigrationPlan
	SubMigrations []Migration // populated for squash entries
}

// Plain holds all plain (non-squashed) migrations sorted by UUID.
var Plain = []Migration{
	{UUID: "01a0192d-8dec-7e49-aa26-4ed6f5346f29", Collection: "_api_key_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8dec-7e49-aa26-4ed6f5346f29__api_key__major.go", Plan: _api_key__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7138-8f73-9e849a7c18b8", Collection: "_audit_log_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7138-8f73-9e849a7c18b8__audit_log__major.go", Plan: _audit_log__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7332-875f-b66a3672a01a", Collection: "_token_blocklist_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7332-875f-b66a3672a01a__token_blocklist__major.go", Plan: _token_blocklist__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7433-b3dc-0d71f826d4a1", Collection: "_notifications_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7433-b3dc-0d71f826d4a1__notifications__major.go", Plan: _notifications__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7702-83f4-ee63c2b1f7ac", Collection: "_seed_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7702-83f4-ee63c2b1f7ac__seed__major.go", Plan: _seed__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-79d6-a7a6-c598d33e332c", Collection: "_iam_rule_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-79d6-a7a6-c598d33e332c__iam_rule__major.go", Plan: _iam_rule__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7ba7-aab9-df8ca481a7cd", Collection: "_operation_policy_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7ba7-aab9-df8ca481a7cd__operation_policy__major.go", Plan: _operation_policy__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8ded-7dbd-894f-5f61d62ed21f", Collection: "_scheduled_messages_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8ded-7dbd-894f-5f61d62ed21f__scheduled_messages__major.go", Plan: _scheduled_messages__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8dee-701e-8a61-bf969d0b9120", Collection: "_settings_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8dee-701e-8a61-bf969d0b9120__settings__major.go", Plan: _settings__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8dee-71af-8a38-c3504ab93f7d", Collection: "_tenant_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8dee-71af-8a38-c3504ab93f7d__tenant__major.go", Plan: _tenant__0_0_0_to_1_0_0},
	{UUID: "01a0192d-8def-7595-97b7-a20285ab022f", Collection: "_user_", From: "0.0.0", To: "1.0.0", File: "01a0192d-8def-7595-97b7-a20285ab022f__user__major.go", Plan: _user__0_0_0_to_1_0_0},
}

// Squash holds all squash migrations sorted by UUID.
var Squash = []Migration(nil)

// All merges Plain and Squash, sorted by UUID, and returns them as a single slice.
func All() []Migration {
	all := make([]Migration, 0, len(Plain)+len(Squash))
	all = append(all, Plain...)
	all = append(all, Squash...)
	sort.Slice(all, func(i, j int) bool { return all[i].UUID < all[j].UUID })
	return all
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All() {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %s: %w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %s: %w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %s: %w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %s %s->%s: %w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
