// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"
	"sort"

	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	UUID          string
	Collection    string
	From          string
	To            string
	File          string
	Plan          func() *base.MigrationPlan
	SubMigrations []Migration // populated for squash entries
}

// Plain holds all plain (non-squashed) migrations sorted by UUID.
var Plain = []Migration{
	{UUID: "01a0476f-a2f9-70a1-a9c4-dbd457290054", Collection: "_api_key_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2f9-70a1-a9c4-dbd457290054__api_key__major.go", Plan: _api_key__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fb-76f5-bcdb-d74757bf678c", Collection: "_audit_log_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fb-76f5-bcdb-d74757bf678c__audit_log__major.go", Plan: _audit_log__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fb-7a7a-9696-be4e77f76c0a", Collection: "_token_blocklist_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fb-7a7a-9696-be4e77f76c0a__token_blocklist__major.go", Plan: _token_blocklist__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fb-7d85-98e7-11d3784f1304", Collection: "_notifications_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fb-7d85-98e7-11d3784f1304__notifications__major.go", Plan: _notifications__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fc-7062-829e-9fbec3bbf6a2", Collection: "_seed_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fc-7062-829e-9fbec3bbf6a2__seed__major.go", Plan: _seed__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fc-7374-bd28-39d282cf1527", Collection: "_iam_rule_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fc-7374-bd28-39d282cf1527__iam_rule__major.go", Plan: _iam_rule__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fc-7634-8c04-f990a4fa91e9", Collection: "_operation_policy_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fc-7634-8c04-f990a4fa91e9__operation_policy__major.go", Plan: _operation_policy__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fc-78c5-9496-ba9a3d665afb", Collection: "_scheduled_messages_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fc-78c5-9496-ba9a3d665afb__scheduled_messages__major.go", Plan: _scheduled_messages__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fc-7b76-a9dd-840eae6d3b39", Collection: "_settings_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fc-7b76-a9dd-840eae6d3b39__settings__major.go", Plan: _settings__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fd-7023-84f4-3538792ed1ba", Collection: "_tenant_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fd-7023-84f4-3538792ed1ba__tenant__major.go", Plan: _tenant__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fd-74a8-83ef-b52ead1a28e8", Collection: "_user_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fd-74a8-83ef-b52ead1a28e8__user__major.go", Plan: _user__0_0_0_to_1_0_0},
	{UUID: "01a0476f-a2fd-772c-b04c-b2474c9e7c02", Collection: "_workflow_definition_", From: "0.0.0", To: "1.0.0", File: "01a0476f-a2fd-772c-b04c-b2474c9e7c02__workflow_definition__major.go", Plan: _workflow_definition__0_0_0_to_1_0_0},
	{UUID: "01a0623b-59bb-7dd1-b491-a7fb23cbf9d1", Collection: "_scheduled_messages_", From: "1.0.0", To: "1.1.0", File: "01a0623b-59bb-7dd1-b491-a7fb23cbf9d1__scheduled_messages__minor.go", Plan: _scheduled_messages__1_0_0_to_1_1_0},
}

// Squash holds all squash migrations sorted by UUID.
var Squash = []Migration(nil)

// All merges Plain and Squash, sorted by UUID, and returns them as a single slice.
func All() []Migration {
	all := make([]Migration, 0, len(Plain)+len(Squash))
	all = append(all, Plain...)
	all = append(all, Squash...)
	sort.Slice(all, func(i, j int) bool { return all[i].UUID < all[j].UUID })
	return all
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All() {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %s: %w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %s: %w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %s: %w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %s %s->%s: %w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
