// Code generated by cmd/hestia service generate. DO NOT EDIT.

package updates

import (
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
)

// RegisterService registers the updates service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*UpdatesService](rt, func(c abstract.Container) (*UpdatesService, error) {
		return NewUpdatesService(c)
	})
}

// Registrations returns the message registrations for the updates service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*UpdatesService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:updates:status:get",
			Description: "Get self-update status (current and staged version)",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[StatusView](),
			Handler: dispatch.HandleDocument[NoInput, *StatusView](s.Status),
		},
		{
			Name:        "system:updates:changelog:get",
			Description: "Get the staged update changelog",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[ChangelogView](),
			Handler: dispatch.HandleDocument[NoInput, *ChangelogView](s.Changelog),
		},
		{
			Name:        "system:updates:check:create",
			Description: "Check for and stage an update (legacy check-then-stage)",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[CheckView](),
			Handler: dispatch.HandleDocument[NoInput, *CheckView](s.Check),
		},
		{
			Name:        "system:updates:check:get",
			Description: "Check whether a newer version is available",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[AvailabilityView](),
			Handler: dispatch.HandleDocument[NoInput, *AvailabilityView](s.CheckAvailability),
		},
		{
			Name:        "system:updates:stage:create",
			Description: "Download and stage the latest update",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[StageView](),
			Handler: dispatch.HandleDocument[NoInput, *StageView](s.Stage),
		},
		{
			Name:        "system:updates:update:apply",
			Description: "Apply the staged update",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[ApplyView](),
			Handler: dispatch.HandleDocument[NoInput, *ApplyView](s.Apply),
		},
		{
			Name:        "system:updates:update:discard",
			Description: "Discard a staged update and clean up",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[NoInput]("input"),
			},
			Output:  dispatch.SchemaFromType[DiscardView](),
			Handler: dispatch.HandleDocument[NoInput, *DiscardView](s.Discard),
		},
	}, nil
}
