package updates

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/updater"
	"go.uber.org/zap"

	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/policies"
	usersmodel "github.com/asaidimu/hestia/core/system/users/model"
)

// @note #migrate-20260822-001 todo status=open priority=P2 tags=#codegen,#wiring : Migrate updates' hand-wired Registrations/PolicyBindings to hestia codegen
//
// Every other feature declares its messages via @hestia.register annotations
// on service methods and gets registrations.go/policies.go generated by
// `hestia generate features` (see AGENTS.md and the users reference
// service). The updates feature is wired manually here because it registers
// conditionally — only when SelfUpdate is configured (Registrations takes
// Dependencies and PolicyBindings is appended outside the static
// gen_features.go wiring) — and it predates the codegen workflow. The two
// newer messages (system:updates:check:get, system:updates:stage:create)
// already carry @hestia.register annotations on their service methods, so a
// migration needs to solve conditional registration in the generator, then
// delete this file's manual lists.
//
// CheckView is the wire shape of the legacy check-then-stage call.

// NoInput is the (empty) input for every updates message — all messages
// take no arguments.
type NoInput struct{}

type StatusView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Version                string `anansi:"version"`
	StagedVersion          string `anansi:"staged_version"`
	Prepared               bool   `anansi:"prepared"`
	LastCheck              int64  `anansi:"last_check"`
}

type ChangelogView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Version                string `anansi:"version"`
	AssetName              string `anansi:"asset_name"`
	Changelog              string `anansi:"changelog"`
}

type CheckView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Checked                bool   `anansi:"checked"`
	Staged                 bool   `anansi:"staged"`
	Version                string `anansi:"version"`
	AutoApply              bool   `anansi:"auto_apply"`
}

type ApplyView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Message                string `anansi:"message"`
}

// AvailabilityView is the wire shape of the read-only availability check.
type AvailabilityView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Available              bool   `anansi:"available"`
	Version                string `anansi:"version"`
}

// StageView is the wire shape of the download-and-stage call.
type StageView struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Staged                 bool   `anansi:"staged"`
	Version                string `anansi:"version"`
}

// Dependencies are what the updates service needs beyond the runtime. The
// service is wired manually (not via the service generator) because it is
// registered only when SelfUpdate is configured.
type Dependencies struct {
	Updater   *updater.Updater
	Store     *Store
	Notifier  abstract.Notifier
	Users     *usersmodel.SystemUsers
	Logger    *zap.Logger
	AppURL    string
	HasMailer bool
	AutoApply bool
	Version   string
	Systemd   bool
	ExePath   string
	DataDir   string
}

// Registrations returns the updates service message registrations.
func Registrations(deps Dependencies) []abstract.MessageRegistration {
	svc := NewService(deps.Updater, deps.Store, deps.Notifier, deps.Users, deps.Logger, deps.AppURL, deps.HasMailer, deps.AutoApply, deps.Version, deps.Systemd, deps.ExePath, deps.DataDir)
	return []abstract.MessageRegistration{
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:status:get",
			Description: "Get self-update status (current and staged version)",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[StatusView](),
			Handler:     dispatch.HandleDocument[NoInput, *StatusView](svc.Status),
		},
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:changelog:get",
			Description: "Get the staged update changelog",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[ChangelogView](),
			Handler:     dispatch.HandleDocument[NoInput, *ChangelogView](svc.Changelog),
		},
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:check:create",
			Description: "Check for and stage an update (legacy check-then-stage)",
			Intent:      abstract.Create,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[CheckView](),
			Handler:     dispatch.HandleDocument[NoInput, *CheckView](svc.Check),
		},
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:check:get",
			Description: "Check whether a newer version is available (read-only, no download)",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[AvailabilityView](),
			Handler:     dispatch.HandleDocument[NoInput, *AvailabilityView](svc.CheckAvailability),
		},
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:stage:create",
			Description: "Download and stage the latest update without applying it",
			Intent:      abstract.Create,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[StageView](),
			Handler:     dispatch.HandleDocument[NoInput, *StageView](svc.Stage),
		},
		{
			Input:       abstract.Input{Schema: dispatch.SchemaFromType[NoInput]()},
			Name:        "system:updates:update:apply",
			Description: "Apply the staged update",
			Intent:      abstract.Create,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[ApplyView](),
			Handler:     dispatch.HandleDocument[NoInput, *ApplyView](svc.Apply),
		},
	}
}

// PolicyBindings binds the updates messages to the administrator rule.
// They are appended conditionally (only when SelfUpdate is configured), never
// through the static allPolicyBindings in gen_features.go.
func PolicyBindings() []policies.Binding {
	return []policies.Binding{
		{Name: "system:updates:status:get", RuleKey: "administrator", Description: "Get self-update status"},
		{Name: "system:updates:changelog:get", RuleKey: "administrator", Description: "Get the staged update changelog"},
		{Name: "system:updates:check:create", RuleKey: "administrator", Description: "Check for and stage an update"},
		{Name: "system:updates:check:get", RuleKey: "administrator", Description: "Check for update availability"},
		{Name: "system:updates:stage:create", RuleKey: "administrator", Description: "Stage an update"},
		{Name: "system:updates:update:apply", RuleKey: "administrator", Description: "Apply the staged update"},
	}
}
