// Code generated by cmd/hestia service generate. DO NOT EDIT.

package users

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the users service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:users:user:create", RuleKey: "administrator", Description: "Create a new user"},
		{Name: "system:users:user:get", RuleKey: "administrator", Description: "Get user by ID"},
		{Name: "system:users:user:update", RuleKey: "administrator", Description: "Update user profile"},
		{Name: "system:users:password:change", RuleKey: "administrator", Description: "Change account password"},
		{Name: "system:users:user:delete", RuleKey: "administrator", Description: "Delete user account"},
	}
}
