// Code generated by cmd/hestia service generate. DO NOT EDIT.

package users

import (
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/users/model"
)

// RegisterService registers the users service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*UsersService](rt, func(c abstract.Container) (*UsersService, error) {
		return NewUsersService(c)
	})
}

// Registrations returns the message registrations for the users service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*UsersService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:users:user:create",
			Description: "Create a new user",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.UserRegisterInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.SystemUser](),
			Handler: dispatch.HandleDocument[model.UserRegisterInput, *model.SystemUser](s.CreateUser),
		},
		{
			Name:        "system:users:user:get",
			Description: "Get user by ID",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.UserGetInput]("input"),
				ResourceIDField: "user_id",
			},
			Output:  dispatch.SchemaFromType[model.SystemUser](),
			Handler: dispatch.HandleDocument[model.UserGetInput, *model.SystemUser](s.GetUser),
		},
		{
			Name:        "system:users:user:update",
			Description: "Update user profile",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.UserUpdateInput]("input"),
				ResourceIDField: "user_id",
			},
			Output:  dispatch.SchemaFromType[model.SystemUser](),
			Handler: dispatch.HandleDocument[model.UserUpdateInput, *model.SystemUser](s.UpdateUser),
		},
		{
			Name:        "system:users:password:change",
			Description: "Change account password",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.UserChangePasswordInput]("input"),
				ResourceIDField: "user_id",
			},
			Handler: dispatch.HandleEmpty[model.UserChangePasswordInput](s.ChangePassword),
		},
		{
			Name:        "system:users:user:delete",
			Description: "Delete user account",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.UserDeleteInput]("input"),
				ResourceIDField: "user_id",
			},
			Handler: dispatch.HandleEmpty[model.UserDeleteInput](s.DeleteUser),
		},
	}, nil
}
