// Code generated by cmd/hestia service generate. DO NOT EDIT.

package auth

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the auth service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:auth:session:create", RuleKey: "public", Description: "Authenticate and receive a session token"},
		{Name: "system:auth:session:delete", RuleKey: "authenticated", Description: "Logout"},
		{Name: "system:auth:password:reset", RuleKey: "authenticated", Description: "Request password reset email"},
		{Name: "system:auth:password:confirm", RuleKey: "public", Description: "Confirm password reset with token"},
		{Name: "system:auth:session:validate", RuleKey: "public", Description: "Validate a session token"},
		{Name: "system:auth:apikey:validate", RuleKey: "public", Description: "Validate an API key"},
		{Name: "system:auth:bootstrap:password:set", RuleKey: "administrator", Description: "Set bootstrap admin password"},
		{Name: "system:auth:token:elevate", RuleKey: "public", Description: "Issue an ephemeral API key for privilege elevation"},
		{Name: "system:auth:token:blocklist:prune", RuleKey: "public", Description: "Prune expired token blocklist entries"},
	}
}
