// Code generated by cmd/hestia service generate. DO NOT EDIT.

package auth

import (
	"context"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/auth/model"
)

// RegisterService registers the auth service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*AuthService](rt, func(c abstract.Container) (*AuthService, error) {
		return NewAuthService(c)
	})
}

// Registrations returns the message registrations for the auth service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*AuthService](rt)
	return []abstract.MessageRegistration{
		{
			Name:          "system:auth:session:create",
			Description:   "Authenticate and receive a session token",
			Intent:        abstract.Create,
			Enabled:       true,
			BootstrapSafe: true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.LoginInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.LoginOutput](),
			Handler: dispatch.Handle[model.LoginInput](s.CreateSession),
		},
		{
			Name:          "system:auth:session:delete",
			Description:   "Logout",
			Intent:        abstract.Delete,
			Enabled:       true,
			BootstrapSafe: true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.DeleteSessionInput]("input"),
			},
			Handler: dispatch.HandleEmpty[model.DeleteSessionInput](s.DeleteSession),
		},
		{
			Name:        "system:auth:password:reset",
			Description: "Request password reset email",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PasswordResetInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleEmpty[model.PasswordResetInput](s.PasswordReset),
		},
		{
			Name:        "system:auth:password:confirm",
			Description: "Confirm password reset with token",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PasswordConfirmInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleEmpty[model.PasswordConfirmInput](s.PasswordConfirm),
		},
		{
			Name:        "system:auth:session:validate",
			Description: "Validate a session token",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Output:      dispatch.SchemaFromType[model.ClaimsOutput](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				model, err := s.ValidateSession(ctx, msg)
				if err != nil {
					return nil, err
				}
				doc, err := model.Document()
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentResult(doc), nil
			},
		},
		{
			Name:        "system:auth:apikey:validate",
			Description: "Validate an API key",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Output:      dispatch.SchemaFromType[model.ClaimsOutput](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				model, err := s.ValidateAPIKey(ctx, msg)
				if err != nil {
					return nil, err
				}
				doc, err := model.Document()
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentResult(doc), nil
			},
		},
		{
			Name:          "system:auth:bootstrap:password:set",
			Description:   "Set bootstrap admin password",
			Intent:        abstract.Update,
			Enabled:       true,
			BootstrapSafe: true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BootstrapPasswordInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleEmpty[model.BootstrapPasswordInput](s.SetBootstrapPassword),
		},
		{
			Name:        "system:auth:token:elevate",
			Description: "Issue an ephemeral API key for privilege elevation",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.ElevateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.ElevateOutput](),
			Handler: dispatch.HandleDocument[model.ElevateInput, *model.ElevateDocumentView](s.ElevateToken),
		},
	}, nil
}
