package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemTenant model in separate Go files,
// using filenames that reflect their purpose (e.g., system_tenant_validation.go,
// system_tenant_serialization.go). Avoid throwing all logic into a
// single system_tenant_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemTenantMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemTenant struct {
	document.DocumentModel
	ID            string                `anansi:"_id_,required=true" json:"_id_"`
	Name          string                `anansi:"name,required=true" json:"name"`
	ModelMetadata *SystemTenantMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	Domain        *string               `anansi:"domain,required=false,omitempty" json:"domain,omitempty"`
	Metadata      map[string]any        `anansi:"metadata,required=false,omitempty" json:"metadata,omitempty"`
	Status        *string               `anansi:"status,required=false,default=active,omitempty" json:"status,omitempty"`
}

// GetID returns the document identifier for SystemTenant.
func (m *SystemTenant) GetID() string {
	return m.ID
}

// NewSystemTenant creates and initializes a new SystemTenant
func NewSystemTenant(model SystemTenant) *SystemTenant {
	return document.New(&model)
}

// SystemTenants is a type-safe collection for SystemTenant
type SystemTenants struct {
	*collection.ModelCollection[*SystemTenant]
}

const SystemTenantsCollectionName = "_tenant_"

var (
	systemTenantsModelMu sync.Mutex
	systemTenantsModel   *SystemTenants
)

// InitSystemTenantsModel must be called once at startup to configure and
// construct the SystemTenant model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemTenantsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemTenant]) (*SystemTenants, error) {
	systemTenantsModelMu.Lock()
	defer systemTenantsModelMu.Unlock()
	if systemTenantsModel != nil {
		return systemTenantsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemTenantsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTenantsModel").
			WithPath("_tenant_")
	}
	mc, err := collection.NewModelCollection[*SystemTenant](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTenantsModel").
			WithPath("_tenant_")
	}
	systemTenantsModel = &SystemTenants{ModelCollection: mc}
	return systemTenantsModel, nil
}

// SystemTenantsModel returns the singleton SystemTenant model.
func SystemTenantsModel() (*SystemTenants, error) {
	systemTenantsModelMu.Lock()
	defer systemTenantsModelMu.Unlock()
	if systemTenantsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemTenantsModel not initialized — call InitSystemTenantsModel first").
			WithOperation("SystemTenantsModel")
	}
	return systemTenantsModel, nil
}

// Deprecated: DangerouslyResetSystemTenantsModel clears the cached singleton so
// InitSystemTenantsModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemTenantsModel() {
	systemTenantsModelMu.Lock()
	defer systemTenantsModelMu.Unlock()
	if systemTenantsModel == nil {
		return
	}
	_ = systemTenantsModel.Close()
	systemTenantsModel = nil
}
