package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_tenant_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemTenant struct {
	data.DocumentModel
	Domain   string         `anansi:"domain" json:"domain"`
	Status   string         `anansi:"status,default=active" json:"status"`
	Name     string         `anansi:"name" json:"name"`
	Metadata map[string]any `anansi:"metadata" json:"metadata"`
}

// NewSystemTenant creates and initializes a new SystemTenant
func NewSystemTenant(model SystemTenant) *SystemTenant {
	return data.New(&model)
}

// SystemTenants is a type-safe collection for SystemTenant
type SystemTenants struct {
	base.ModelCollection[SystemTenant, *SystemTenant]
}

const SystemTenantsCollectionName = "_tenant_"

var (
	systemTenantsModelMu sync.Mutex
	systemTenantsModel   *SystemTenants
)

// InitSystemTenantsModel must be called once at startup to configure and
// construct the SystemTenant model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemTenantsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemTenant, *SystemTenant]) (*SystemTenants, error) {
	systemTenantsModelMu.Lock()
	defer systemTenantsModelMu.Unlock()
	if systemTenantsModel != nil {
		return systemTenantsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemTenantsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTenantsModel").
			WithPath("_tenant_")
	}
	mc, err := collection.NewModelCollection[SystemTenant, *SystemTenant](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTenantsModel").
			WithPath("_tenant_")
	}
	systemTenantsModel = &SystemTenants{ModelCollection: mc}
	return systemTenantsModel, nil
}

// SystemTenantsModel returns the singleton SystemTenant model.
func SystemTenantsModel() (*SystemTenants, error) {
	systemTenantsModelMu.Lock()
	defer systemTenantsModelMu.Unlock()
	if systemTenantsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemTenantsModel not initialized — call InitSystemTenantsModel first").
			WithOperation("SystemTenantsModel")
	}
	return systemTenantsModel, nil
}
