// Code generated by cmd/hestia service generate. DO NOT EDIT.

package notifications

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the notifications service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:notifications:notification:list", RuleKey: "authenticated", Description: "List notifications for the current user"},
		{Name: "system:notifications:notification:read", RuleKey: "authenticated", Description: "Mark a notification as read"},
		{Name: "system:notifications:read:all", RuleKey: "authenticated", Description: "Mark all notifications as read"},
		{Name: "system:notifications:unread:count", RuleKey: "authenticated", Description: "Count unread notifications"},
	}
}
