// Code generated by cmd/hestia service generate. DO NOT EDIT.

package notifications

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/notifications/model"
)

// RegisterService registers the notifications service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*NotificationsService](rt, func(c abstract.Container) (*NotificationsService, error) {
		return NewNotificationsService(c)
	})
}

// Registrations returns the message registrations for the notifications service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*NotificationsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:notifications:notification:list",
			Description: "List notifications for the current user",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.NotificationListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[model.NotificationListInput](s.ListNotifications),
		},
		{
			Name:        "system:notifications:notification:read",
			Description: "Mark a notification as read",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.NotificationReadInput]("input"),
				ResourceIDField: "notification_id",
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleDocument[model.NotificationReadInput, *model.MessageOutput](s.MarkRead),
		},
		{
			Name:        "system:notifications:read:all",
			Description: "Mark all notifications as read",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.NotificationMarkAllReadInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleDocument[model.NotificationMarkAllReadInput, *model.MessageOutput](s.MarkAllRead),
		},
		{
			Name:        "system:notifications:unread:count",
			Description: "Count unread notifications",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.NotificationUnreadCountInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.UnreadCountDocument](),
			Handler: dispatch.HandleDocument[model.NotificationUnreadCountInput, *model.UnreadCountDocument](s.CountUnread),
		},
	}, nil
}
