// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/settings/schema/settings.schema.json
// Date: 2026-07-24T08:01:05Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _settings__1_0_0_to_2_0_0 returns a migration plan for _settings__1_0_0_to_2_0_0 (1.0.0 → 2.0.0).
func _settings__1_0_0_to_2_0_0() *base.MigrationPlan {
	desc := "auto migration from 1.0.0 to 2.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__settings__2_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _settings__1_0_0_to_2_0_0: implement transformer or remove this line")
	}
	return m
}

// target__settings__2_0_0 is the target schema serialized from core/internal/feature/settings/schema/settings.schema.json.
var target__settings__2_0_0_json = []byte(`{"version":"1.0.0","name":"_settings_","fields":{"019f9324-6da7-712f-a893-902d54379c60":{"name":"key","required":true,"type":"string"},"019f9324-6da7-7130-b318-65ab997951ab":{"name":"value","required":true,"type":"unknown"},"019f9324-6da7-7131-9d67-ae03742fd8ea":{"name":"tenant_id","type":"string"},"019f9324-6da7-7132-a6b7-2d5baef9299c":{"name":"updated_by","type":"string"}},"indexes":{"019f9324-6da7-7133-860d-c2bfe7ccfb27":{"name":"idx_tenant_key","type":"unique","fields":["tenant_id","key"]}}}`)

func target__settings__2_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__settings__2_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
