// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/notifications/schema/notification.schema.json
// Date: 2026-07-25T08:18:39Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _notification__3_0_0_to_3_1_0 returns a migration plan for _notification__3_0_0_to_3_1_0 (3.0.0 → 3.1.0).
func _notification__3_0_0_to_3_1_0() *base.MigrationPlan {
	desc := "auto migration from 3.0.0 to 3.1.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__notification__3_1_0(),
		VersionBump: definition.BumpMinor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		// tenant_id changed from required to optional. Existing docs already have
		// the field set from earlier migrations — nothing to backfill.
		return doc, nil
	}
	return m
}

// target__notification__3_1_0 is the target schema serialized from core/internal/feature/notifications/schema/notification.schema.json.
var target__notification__3_1_0_json = []byte(`{"version":"1.0.0","name":"_notification_","fields":{"019f9324-1677-7dbd-8cec-2ecff311dd9f":{"name":"read_at","type":"integer"},"019f9324-1677-7dbf-8a3b-b0c5d7b7d35c":{"name":"tenant_id","type":"string"},"019f9324-1677-7dc1-ab1f-32b54005fd80":{"name":"title","required":true,"type":"string"},"019f9324-1677-7dc4-8eef-2864bcbdbaf0":{"name":"body","type":"string"},"019f9324-1677-7dc5-9616-56491553393f":{"name":"link","type":"string"},"019f9324-1677-7dc2-9f28-751b3d614581":{"name":"read","type":"boolean","default":false},"019f9324-1677-7dbe-9a0a-9a8f10523cca":{"name":"metadata","type":"record"},"019f9324-1677-7dc0-baed-6c9719b8ffe8":{"name":"user_id","required":true,"type":"string"},"019f9324-1677-7dc3-b92c-c3ab3ec15fb2":{"name":"type","required":true,"type":"string"}},"indexes":{"019f9324-1677-7dc6-8667-470452519a7a":{"name":"idx_user_unread","type":"normal","fields":["tenant_id","user_id","read"]}}}`)

func target__notification__3_1_0() *definition.Schema {
	s, err := definition.FromJSON(target__notification__3_1_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
