// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/tenants/schema/tenant.schema.json
// Date: 2026-07-24T08:01:05Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _tenant__1_0_0_to_2_0_0 returns a migration plan for _tenant__1_0_0_to_2_0_0 (1.0.0 → 2.0.0).
func _tenant__1_0_0_to_2_0_0() *base.MigrationPlan {
	desc := "auto migration from 1.0.0 to 2.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__tenant__2_0_0(),
		VersionBump: definition.BumpMajor,
	}

	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _tenant__1_0_0_to_2_0_0: implement transformer or remove this line")
	}
	return m
}

// target__tenant__2_0_0 is the target schema serialized from core/internal/feature/tenants/schema/tenant.schema.json.
var target__tenant__2_0_0_json = []byte(`{"version":"1.0.0","name":"_tenant_","fields":{"019f9324-6da7-7134-a0ab-1186a7ad2ccd":{"name":"metadata","type":"unknown"},"019f9324-6da7-7135-8b0d-693af7e7560a":{"name":"name","required":true,"unique":true,"type":"string"},"019f9324-6da7-7136-a935-7acfc1aad4cd":{"name":"domain","unique":true,"type":"string"},"019f9324-6da7-7137-a78b-fcff82470c8c":{"name":"status","type":"string","default":"active"}}}`)

func target__tenant__2_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__tenant__2_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
