// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/settings/schema/settings.schema.json
// Date: 2026-07-24T07:59:54Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _settings__0_0_0_to_1_0_0 returns a migration plan for _settings__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _settings__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__settings__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _settings__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__settings__1_0_0 is the target schema serialized from core/internal/feature/settings/schema/settings.schema.json.
var target__settings__1_0_0_json = []byte(`{"version":"1.0.0","name":"_settings_","description":"Key-value settings store. Settings can be global (tenant_id=null) or scoped to a tenant.","fields":{"019f9323-56fd-7370-8396-1dc906d6493d":{"name":"updated_by","description":"User ID who last updated this setting","type":"string"},"019f9323-56fd-7371-a995-4d389487069f":{"name":"key","description":"Setting key (dot-separated namespace, e.g. 'cors.origins')","required":true,"type":"string"},"019f9323-56fd-7372-9f9c-bcadeccab761":{"name":"value","description":"Arbitrary JSON value","required":true,"type":"unknown"},"019f9323-56fd-7373-992b-4d8fa95ab903":{"name":"tenant_id","description":"Tenant scope — null means global setting","type":"string"},"019f9323-56fd-7374-b40e-acdbbfaf21bc":{"name":"updated_at","type":"integer"}},"indexes":{"019f9323-56fd-7375-aeb9-5da1451fb172":{"name":"idx_tenant_key","type":"unique","fields":["tenant_id","key"]}}}`)

func target__settings__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__settings__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
