// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/policies/schema/operation_policy.schema.json
// Date: 2026-07-28T10:01:15Z

package migrations

import (
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _operation_policy__3_1_0_to_3_2_0 returns a migration plan for _operation_policy__3_1_0_to_3_2_0 (3.1.0 → 3.2.0).
func _operation_policy__3_1_0_to_3_2_0() *base.MigrationPlan {
	desc := "auto migration from 3.1.0 to 3.2.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__operation_policy__3_2_0(),
		VersionBump: definition.BumpMinor,
	}
	
	return m
}

// target__operation_policy__3_2_0 is the target schema serialized from core/internal/feature/policies/schema/operation_policy.schema.json.
var target__operation_policy__3_2_0_json = []byte(`{"version":"1.0.0","name":"_operation_policy_","fields":{"019fa82b-e174-7446-bbd8-a78a7b4c38b3":{"name":"throttle_limit","type":"number"},"019fa82b-e174-744c-b480-06fa110bcee8":{"name":"rate_refill","type":"number"},"019f32aa-ba8b-7e81-82df-b9f34eddb05d":{"name":"intentType","type":"string"},"019fa82b-e174-7445-bc15-2b6b8c4dbfc8":{"name":"rate_capacity","type":"number"},"019fa82b-e174-7448-a245-62d91bc6f793":{"name":"throttle_action_msg","type":"string"},"019fa82b-e174-744b-b33e-d8c3b10fbc61":{"name":"rate_identity","type":"string"},"019f32aa-ba8b-7dd9-baef-3fe342578ecc":{"name":"rule","required":true,"type":"string"},"019fa82b-e174-7444-97cf-1f019bcbba0c":{"name":"rate_limit_enabled","type":"boolean"},"019f75c6-e69c-7b8a-85b0-36efff9a58f6":{"name":"enabled","type":"boolean"},"019fa82b-e174-7447-968a-f519fb04c110":{"name":"throttle_window","type":"number"},"019f936c-1b9b-72f1-be3c-1e65f5964c49":{"name":"tenant_id","type":"string"},"019f32aa-ba8b-797a-bc32-17574381a3b4":{"name":"operation","required":true,"type":"string"},"019f32aa-ba8b-7db8-817e-7de94fe1ae3d":{"name":"protected","type":"boolean"},"019f32aa-ba8b-748c-8f2b-68c940329ed0":{"name":"description","type":"string"},"019fa82b-e174-7449-b368-47db69033ee9":{"name":"throttle_action_input","type":"record"},"019fa82b-e174-744a-bf83-8f3e24762a02":{"name":"rate_period","type":"number"},"019f936c-1b9b-72f2-831d-967f284f1fda":{"name":"key","type":"string"}}}`)

func target__operation_policy__3_2_0() *definition.Schema {
	s, err := definition.FromJSON(target__operation_policy__3_2_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
