// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/schedules/schema/_scheduled_messages_.schema.json
// Date: 2026-07-28T06:57:40Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _scheduled_messages__0_0_0_to_1_0_0 returns a migration plan for _scheduled_messages__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _scheduled_messages__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__scheduled_messages__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		return doc, nil
	}
	return m
}

// target__scheduled_messages__1_0_0 is the target schema serialized from core/internal/feature/schedules/schema/_scheduled_messages_.schema.json.
var target__scheduled_messages__1_0_0_json = []byte(`{"version":"1.0.0","name":"_scheduled_messages_","description":"Scheduled message dispatch queue","fields":{"019fa783-cc47-7eda-8c24-e5ebade936a3":{"name":"type","required":true,"type":"string"},"019fa783-cc47-7ed2-90cf-f641e208f891":{"name":"data","type":"record"},"019fa783-cc47-7ed3-a81a-7739bd63f247":{"name":"send_at","required":true,"type":"integer"},"019fa783-cc47-7ed6-82f3-a60b5a48f594":{"name":"sent","type":"boolean"},"019fa783-cc47-7ed7-9fff-124eb1a05564":{"name":"tenant_id","type":"string"},"019fa783-cc47-7ed9-b9f1-89ae38252551":{"name":"user_id","required":true,"type":"string"},"019fa783-cc47-7ed1-9710-88068d570686":{"name":"channel","type":"string"},"019fa783-cc47-7ed4-9327-f1aed10a509d":{"name":"sent_at","type":"integer"},"019fa783-cc47-7ed5-9c61-d39f3e0a4e2e":{"name":"error_","type":"string"},"019fa783-cc47-7ed8-8d66-b583034ba56c":{"name":"created_at","type":"integer"}},"indexes":{"019fa783-cc47-7edb-b494-6d08ff6100d2":{"name":"idx_tenant","type":"normal","fields":["tenant_id","send_at"]},"019fa783-cc47-7edc-bd96-9c346e9d4305":{"name":"idx_due","type":"normal","fields":["send_at","sent"]}}}`)

func target__scheduled_messages__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__scheduled_messages__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
