// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/tenants/schema/tenant.schema.json
// Date: 2026-07-24T07:59:54Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _tenant__0_0_0_to_1_0_0 returns a migration plan for _tenant__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _tenant__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__tenant__1_0_0(),
		VersionBump: definition.BumpMajor,
	}

	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _tenant__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__tenant__1_0_0 is the target schema serialized from core/internal/feature/tenants/schema/tenant.schema.json.
var target__tenant__1_0_0_json = []byte(`{"version":"1.0.0","name":"_tenant_","description":"Multi-tenant organization definitions. The platform root tenant uses id='root'. The public fallback tenant uses id='public'.","fields":{"019f9323-56fd-7378-9cc3-95e422b90404":{"name":"created_at","type":"integer"},"019f9323-56fd-7379-9d26-dd7aac1f7891":{"name":"metadata","description":"Arbitrary tenant metadata (branding, settings overrides)","type":"unknown"},"019f9323-56fd-737a-ad2f-57573e8c53ff":{"name":"name","description":"Human-readable tenant name (e.g. 'Acme Corp')","required":true,"unique":true,"type":"string"},"019f9323-56fd-7376-8a92-f3a58cf3cc70":{"name":"domain","description":"Optional DNS domain for automatic tenant resolution","unique":true,"type":"string"},"019f9323-56fd-7377-b864-f4125de2a781":{"name":"status","type":"string","default":"active"}}}`)

func target__tenant__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__tenant__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
