// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/users/schema/user.schema.json
// Date: 2026-07-24T07:39:47Z

package migrations

import (
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _user__2_0_0_to_2_1_0 returns a migration plan for _user__2_0_0_to_2_1_0 (2.0.0 → 2.1.0).
func _user__2_0_0_to_2_1_0() *base.MigrationPlan {
	desc := "auto migration from 2.0.0 to 2.1.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__user__2_1_0(),
		VersionBump: definition.BumpMinor,
	}
	
	return m
}

// target__user__2_1_0 is the target schema serialized from core/internal/feature/users/schema/user.schema.json.
var target__user__2_1_0_json = []byte(`{"version":"1.0.0","name":"_user_","fields":{"019f32aa-ba8c-73a6-8fed-a5f84b19ab3b":{"name":"name","required":true,"type":"string"},"019f32aa-ba8c-7f38-bce4-d3fa440c9881":{"name":"verified","type":"boolean"},"019f32aa-ba8c-7957-a27c-e2f64c8aabd1":{"name":"permissions","type":"array","schema":{"id":"019f32aa-ba8c-7488-a799-bb6645acaeb4"}},"019f32aa-ba8c-7602-84a7-00db460db25b":{"name":"deleted","type":"string"},"019f9310-ed56-7530-9741-959cfd29d275":{"name":"token_version","type":"integer","default":0},"019f32aa-ba8c-7679-957f-588144ddbb2b":{"name":"email","required":true,"unique":true,"type":"string"},"019f32aa-ba8c-7cb6-ab3f-262b49e3a2bf":{"name":"password","required":true,"type":"string"}},"schemas":{"019f32aa-ba8c-7488-a799-bb6645acaeb4":{"name":"Permission","type":"string"}}}`)

func target__user__2_1_0() *definition.Schema {
	s, err := definition.FromJSON(target__user__2_1_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
