// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/notifications/schema/notification.schema.json
// Date: 2026-07-24T07:59:54Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _notification__0_0_0_to_1_0_0 returns a migration plan for _notification__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _notification__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__notification__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _notification__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__notification__1_0_0 is the target schema serialized from core/internal/feature/notifications/schema/notification.schema.json.
var target__notification__1_0_0_json = []byte(`{"version":"1.0.0","name":"_notification_","description":"Per-user in-app notifications. Supports read tracking and per-tenant isolation.","fields":{"019f9323-56fd-7369-8c05-aab473ef0a9c":{"name":"read_at","type":"integer"},"019f9323-56fd-736a-8d42-a451b2b3b616":{"name":"tenant_id","required":true,"type":"string"},"019f9323-56fd-736b-9f0f-f2bddd5689a2":{"name":"type","description":"Notification type/category (e.g. 'info', 'alert', 'mention')","required":true,"type":"string"},"019f9323-56fd-736d-ada7-7a47c0289808":{"name":"body","type":"string"},"019f9323-56fd-7366-aec9-4b51c4de732d":{"name":"metadata","description":"Arbitrary structured data (e.g. { 'actor_id': '...', 'resource_id': '...' })","type":"unknown"},"019f9323-56fd-7367-bf54-bc013363df3a":{"name":"user_id","required":true,"type":"string"},"019f9323-56fd-736c-a1b2-7c35eef6dd5a":{"name":"title","required":true,"type":"string"},"019f9323-56fd-7364-8b16-a1504f968acd":{"name":"link","description":"Deep link to the resource this notification refers to","type":"string"},"019f9323-56fd-7365-9495-0da31ec3e6f8":{"name":"created_at","type":"integer"},"019f9323-56fd-7368-bb31-d9ccd3c945c2":{"name":"read","type":"boolean","default":false}},"indexes":{"019f9323-56fd-736e-b2a0-08f5da6088ca":{"name":"idx_user_unread","type":"normal","fields":["tenant_id","user_id","read"]},"019f9323-56fd-736f-9e83-0e0d3bed44d6":{"name":"idx_created","type":"normal","order":"desc","fields":["created_at"]}}}`)

func target__notification__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__notification__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
