// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/policies/schema/operation_policy.schema.json
// Date: 2026-07-18T15:09:57Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _operation_policy__1_0_1_to_2_0_0 returns a migration plan for _operation_policy__1_0_1_to_2_0_0 (1.0.1 → 2.0.0).
func _operation_policy__1_0_1_to_2_0_0() *base.MigrationPlan {
	desc := "auto migration from 1.0.1 to 2.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__operation_policy__2_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		name, _ := doc.GetString("name")
		ruleKey, _ := doc.GetString("ruleKey")
		desc, _ := doc.GetString("description")
		intentType, _ := doc.GetString("intentType")
		protected, _ := doc.GetBool("protected")

		fields := map[string]any{
			"operation":   name,
			"rule":        ruleKey,
			"description": desc,
			"intentType":  intentType,
			"protected":   protected,
			"enabled":     true,
		}
		newDoc, err := data.NewDocument(fields, ctx)
		if err != nil {
			return doc, err
		}
		return *newDoc, nil
	}
	return m
}

// target__operation_policy__2_0_0 is the target schema serialized from internal/app/policies/schema/operation_policy.schema.json.
var target__operation_policy__2_0_0_json = []byte(`{"version":"1.0.0","name":"_operation_policy_","fields":{"019f32aa-ba8b-797a-bc32-17574381a3b4":{"name":"operation","required":true,"type":"string"},"019f32aa-ba8b-7dd9-baef-3fe342578ecc":{"name":"rule","required":true,"type":"string"},"019f32aa-ba8b-748c-8f2b-68c940329ed0":{"name":"description","type":"string"},"019f32aa-ba8b-7e81-82df-b9f34eddb05d":{"name":"intentType","type":"string"},"019f32aa-ba8b-7db8-817e-7de94fe1ae3d":{"name":"protected","type":"unknown"},"019f75c6-e69c-7b8a-85b0-36efff9a58f6":{"name":"enabled","type":"unknown"}}}`)

func target__operation_policy__2_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__operation_policy__2_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
