// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/schedules/schema/_scheduled_messages_.schema.json
// Date: 2026-07-29T07:57:59Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _scheduled_messages__1_0_0_to_2_0_0 returns a migration plan for _scheduled_messages__1_0_0_to_2_0_0 (1.0.0 → 2.0.0).
func _scheduled_messages__1_0_0_to_2_0_0() *base.MigrationPlan {
	desc := "auto migration from 1.0.0 to 2.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__scheduled_messages__2_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		for _, old := range []string{"send_at", "sent", "sent_at", "error_", "channel"} {
			doc.Delete(old)
		}
		if v, err := doc.Get("type"); err == nil && v != nil {
			doc.Set("message", v)
			doc.Delete("type")
		}
		if _, err := doc.Get("input"); err != nil {
			if v, err := doc.Get("data"); err == nil && v != nil {
				doc.Set("input", v)
			}
			doc.Delete("data")
		}
		return doc, nil
	}
	return m
}

// target__scheduled_messages__2_0_0 is the target schema serialized from core/internal/feature/schedules/schema/_scheduled_messages_.schema.json.
var target__scheduled_messages__2_0_0_json = []byte(`{"version":"1.0.0","name":"_scheduled_messages_","description":"Cron-triggered message dispatch","fields":{"019fa783-cc47-7ed7-9fff-124eb1a05564":{"name":"tenant_id","type":"string"},"019fa783-cc47-7ed9-b9f1-89ae38252551":{"name":"user_id","required":true,"type":"string"},"019fa783-cc47-7ed8-8d66-b583034ba56c":{"name":"created_at","type":"integer"},"019fa783-cc47-7eda-8c24-e5ebade936a3":{"name":"message","required":true,"type":"string"},"019fa783-cc47-7ed2-90cf-f641e208f891":{"name":"input","type":"record"},"019fa783-cc47-7ed3-a81a-7739bd63f247":{"name":"cron","required":true,"type":"string"},"019fa783-cc47-7ed6-82f3-a60b5a48f594":{"name":"disabled","type":"boolean"}}}`)

func target__scheduled_messages__2_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__scheduled_messages__2_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
