// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/users/schema/user.schema.json
// Date: 2026-07-29T11:04:09Z

package migrations

import (
	"context"
	"time"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _user__5_2_0_to_6_0_0 returns a migration plan for _user__5_2_0_to_6_0_0 (5.2.0 → 6.0.0).
func _user__5_2_0_to_6_0_0() *base.MigrationPlan {
	desc := "auto migration from 5.2.0 to 6.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__user__6_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		deleted, _ := doc.GetString("deleted")
		doc.Unset("deleted")
		if _, err := doc.Get("disabled"); err != nil {
			if deleted != "" {
				t, parseErr := time.Parse(time.RFC3339, deleted)
				if parseErr != nil {
					doc.Set("disabled", time.Now().Unix())
				} else {
					doc.Set("disabled", t.Unix())
				}
			} else {
				doc.Set("disabled", int64(0))
			}
		}
		return doc, nil
	}
	return m
}

// target__user__6_0_0 is the target schema serialized from core/internal/feature/users/schema/user.schema.json.
var target__user__6_0_0_json = []byte(`{"version":"1.0.0","name":"_user_","fields":{"019fad8b-d14f-735c-b5e7-8eb4fc6657d3":{"name":"disabled","type":"boolean"},"019f32aa-ba8c-7957-a27c-e2f64c8aabd1":{"name":"permissions","type":"array","schema":{"id":"019f32aa-ba8c-7488-a799-bb6645acaeb4"}},"019f32aa-ba8c-7cb6-ab3f-262b49e3a2bf":{"name":"password","required":true,"type":"string"},"019f9323-56fe-737a-b225-4740d68e6d02":{"name":"tenant_id","type":"string"},"019f32aa-ba8c-7f38-bce4-d3fa440c9881":{"name":"verified","type":"boolean"},"019f32aa-ba8c-7679-957f-588144ddbb2b":{"name":"email","required":true,"unique":true,"type":"string"},"019fa30d-3a09-7493-b907-316c3c34fead":{"name":"data","type":"record"},"019f9310-ed56-7530-9741-959cfd29d275":{"name":"token_version","type":"integer","default":0},"019f32aa-ba8c-73a6-8fed-a5f84b19ab3b":{"name":"name","required":true,"type":"string"},"019f9323-56fe-737b-9a01-bdc7da91cc88":{"name":"settings","type":"record"}},"schemas":{"019f32aa-ba8c-7488-a799-bb6645acaeb4":{"name":"Permission","type":"string"}}}`)

func target__user__6_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__user__6_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
