// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: core/internal/feature/notifications/schema/_notifications_.schema.json
// Date: 2026-07-28T06:10:00Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _notifications__0_0_0_to_1_0_0 returns a migration plan for _notifications__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _notifications__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__notifications__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _notifications__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__notifications__1_0_0 is the target schema serialized from core/internal/feature/notifications/schema/_notifications_.schema.json.
var target__notifications__1_0_0_json = []byte(`{"version":"0.1.0","name":"_notifications_","description":"In-app notification inbox per user","fields":{"019fa758-299e-75d4-ae08-88411a38fb6c":{"name":"created_at","type":"integer"},"019fa758-299e-75d5-99a0-6233d3661d54":{"name":"user_id","required":true,"type":"string"},"019fa758-299e-75d6-9fc2-3e42db15adf0":{"name":"type","required":true,"type":"string"},"019fa758-299e-75d7-8074-153f58b15221":{"name":"subject","required":true,"type":"string"},"019fa758-299e-75d8-a990-d008ab12411e":{"name":"body","type":"string"},"019fa758-299e-75d1-8954-71aefd2e5426":{"name":"data","type":"record"},"019fa758-299e-75d2-9134-9599d25e75f8":{"name":"read","type":"boolean"},"019fa758-299e-75d3-905b-733a0f6123f8":{"name":"tenant_id","type":"string"}},"indexes":{"019fa758-299e-75da-9019-c8e52fc44412":{"name":"idx_user_created","type":"normal","fields":["user_id","created_at"]},"019fa758-299e-75d9-8bf0-3cec9be7c963":{"name":"idx_user_read","type":"normal","fields":["user_id","read"]}}}`)

func target__notifications__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__notifications__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
