// Code generated by cmd/hestia service generate. DO NOT EDIT.

package settings

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/settings/model"
)

// RegisterService registers the settings service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*SettingsService](rt, func(c abstract.Container) (*SettingsService, error) {
		return NewSettingsService(c)
	})
}

// Registrations returns the message registrations for the settings service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*SettingsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:settings:list",
			Description: "List all settings",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.SettingListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[model.SettingListInput](s.ListSettings),
		},
		{
			Name:        "system:settings:get",
			Description: "Get a setting by key",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.SettingKeyInput]("input"),
				ResourceIDField: "key",
			},
			Output:  dispatch.SchemaFromType[model.SettingDocumentView](),
			Handler: dispatch.HandleDocument[model.SettingKeyInput, *model.SettingDocumentView](s.GetSetting),
		},
		{
			Name:        "system:settings:set",
			Description: "Create or update a setting",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.SetSettingInput]("input"),
				ResourceIDField: "key",
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleDocument[model.SetSettingInput, *model.MessageOutput](s.SetSetting),
		},
		{
			Name:        "system:settings:delete",
			Description: "Delete a setting",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.SettingKeyInput]("input"),
				ResourceIDField: "key",
			},
			Handler: dispatch.HandleEmpty[model.SettingKeyInput](s.DeleteSetting),
		},
	}, nil
}
