package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemSeed model in separate Go files,
// using filenames that reflect their purpose (e.g., system_seed_validation.go,
// system_seed_serialization.go). Avoid throwing all logic into a
// single system_seed_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemSeedMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemSeed struct {
	document.DocumentModel
	ID       string              `anansi:"_id_,required=true" json:"_id_"`
	Key      string              `anansi:"key,required=true" json:"key"`
	Metadata *SystemSeedMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	Value    *string             `anansi:"value,required=false,omitempty" json:"value,omitempty"`
}

// GetID returns the document identifier for SystemSeed.
func (m *SystemSeed) GetID() string {
	return m.ID
}

// NewSystemSeed creates and initializes a new SystemSeed
func NewSystemSeed(model SystemSeed) *SystemSeed {
	return document.New(&model)
}

// SystemSeeds is a type-safe collection for SystemSeed
type SystemSeeds struct {
	*collection.ModelCollection[*SystemSeed]
}

const SystemSeedsCollectionName = "_seed_"

var (
	systemSeedsModelMu sync.Mutex
	systemSeedsModel   *SystemSeeds
)

// InitSystemSeedsModel must be called once at startup to configure and
// construct the SystemSeed model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemSeedsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemSeed]) (*SystemSeeds, error) {
	systemSeedsModelMu.Lock()
	defer systemSeedsModelMu.Unlock()
	if systemSeedsModel != nil {
		return systemSeedsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemSeedsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSeedsModel").
			WithPath("_seed_")
	}
	mc, err := collection.NewModelCollection[*SystemSeed](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSeedsModel").
			WithPath("_seed_")
	}
	systemSeedsModel = &SystemSeeds{ModelCollection: mc}
	return systemSeedsModel, nil
}

// SystemSeedsModel returns the singleton SystemSeed model.
func SystemSeedsModel() (*SystemSeeds, error) {
	systemSeedsModelMu.Lock()
	defer systemSeedsModelMu.Unlock()
	if systemSeedsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemSeedsModel not initialized — call InitSystemSeedsModel first").
			WithOperation("SystemSeedsModel")
	}
	return systemSeedsModel, nil
}

// Deprecated: DangerouslyResetSystemSeedsModel clears the cached singleton so
// InitSystemSeedsModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemSeedsModel() {
	systemSeedsModelMu.Lock()
	defer systemSeedsModelMu.Unlock()
	if systemSeedsModel == nil {
		return
	}
	_ = systemSeedsModel.Close()
	systemSeedsModel = nil
}
