package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/asaidimu/hestia/core"
	httpapi "github.com/asaidimu/hestia/core/interface/http"
	"github.com/asaidimu/hestia/core/runtime"
)

func main() {
	tmpDir, err := os.MkdirTemp("", "hestia-gen-routes-*")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(tmpDir)

	app, err := hestia.Setup(hestia.SetupConfig{
		DataDir:           tmpDir,
		DBPath:            ":memory:",
		SessionSecret:     "gen-routes-secret",
		ForceBootstrapped: true,
		AdminEmail:        "gen@routes.local",
		AdminPassword:     "password123",
		BuildInterfaces:   func(a *hestia.Application) []runtime.Interface { return nil },
	})
	if err != nil {
		panic(err)
	}
	defer app.Close()

	regs := app.Registrations()

	type routeDoc struct {
		Method    string
		Route     string
		Arguments []string
	}

	table := make(map[string]routeDoc)

	for _, r := range regs {
		if r.Internal {
			continue
		}
		method := httpapi.IntentToHTTPMethod(r.Intent)
		httpPath := httpapi.DeriveRoute(r.Name, r.Input.Args())
		route := httpapi.IntentToHTTPPath(r.Intent, httpPath)

		args := make([]string, len(r.Input.Args()))
		for i, a := range r.Input.Args() {
			args[i] = a.Name
		}

		table[r.Name] = routeDoc{
			Method:    method,
			Route:     route,
			Arguments: args,
		}
	}

	var lines []string
	names := make([]string, 0, len(table))
	for name := range table {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, n := range names {
		doc := table[n]
		argsJSON := "[]"
		if len(doc.Arguments) > 0 {
			argsJSON = fmt.Sprintf(`["%s"]`, strings.Join(doc.Arguments, `", "`))
		}
		lines = append(lines, fmt.Sprintf(`  %q: { method: %q, route: %q, arguments: %s },`, n, doc.Method, doc.Route, argsJSON))
	}

	out := fmt.Sprintf(`// Code generated by cmd/gen-routes. DO NOT EDIT.

export interface RouteDoc {
  method: string;
  route: string;
  arguments: string[];
}

export const ROUTE_TABLE = {
%s
} as const;

export type RouteName = keyof typeof ROUTE_TABLE;
`, strings.Join(lines, "\n"))

	root := projectRoot()
	if root == "" {
		fmt.Fprintln(os.Stderr, "could not find project root (go.mod)")
		os.Exit(1)
	}

	clientDir := filepath.Join(root, "client", "core")
	os.MkdirAll(clientDir, 0755)
	outPath := filepath.Join(clientDir, "routes.gen.ts")
	if err := os.WriteFile(outPath, []byte(out), 0644); err != nil {
		panic(err)
	}

	fmt.Printf("Generated %s with %d routes\n", outPath, len(table))
}

func projectRoot() string {
	wd, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return ""
		}
		wd = parent
	}
}
