package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemNotifications model in separate Go files,
// using filenames that reflect their purpose (e.g., system_notifications_validation.go,
// system_notifications_serialization.go). Avoid throwing all logic into a
// single system_notifications_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type NotificationAction struct {
	Label     string         `anansi:"label,required=true" json:"label"`
	Arguments map[string]any `anansi:"arguments,required=false,omitempty" json:"arguments,omitempty"`
	Message   *string        `anansi:"message,required=false,omitempty" json:"message,omitempty"`
	URL       *string        `anansi:"url,required=false,omitempty" json:"url,omitempty"`
}

type SystemNotificationsMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemNotifications struct {
	document.DocumentModel
	Actions   []NotificationAction         `anansi:"actions,required=false,omitempty" json:"actions,omitempty"`
	ID        string                       `anansi:"_id_,required=true" json:"_id_"`
	Subject   string                       `anansi:"subject,required=true" json:"subject"`
	Type      string                       `anansi:"type,required=true" json:"type"`
	UserID    string                       `anansi:"user_id,required=true" json:"user_id"`
	Metadata  *SystemNotificationsMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	Body      *string                      `anansi:"body,required=false,omitempty" json:"body,omitempty"`
	CreatedAt *int64                       `anansi:"created_at,required=false,omitempty" json:"created_at,omitempty"`
	Data      map[string]any               `anansi:"data,required=false,omitempty" json:"data,omitempty"`
	ExpiresAt *int64                       `anansi:"expires_at,required=false,omitempty" json:"expires_at,omitempty"`
	Read      *bool                        `anansi:"read,required=false,omitempty" json:"read,omitempty"`
	TenantID  *string                      `anansi:"tenant_id,required=false,omitempty" json:"tenant_id,omitempty"`
}

// GetID returns the document identifier for SystemNotifications.
func (m *SystemNotifications) GetID() string {
	return m.ID
}

// NewSystemNotifications creates and initializes a new SystemNotifications
func NewSystemNotifications(model SystemNotifications) *SystemNotifications {
	return document.New(&model)
}

// SystemNotificationss is a type-safe collection for SystemNotifications
type SystemNotificationss struct {
	*collection.ModelCollection[*SystemNotifications]
}

const SystemNotificationssCollectionName = "_notifications_"

var (
	systemNotificationssModelMu sync.Mutex
	systemNotificationssModel   *SystemNotificationss
)

// InitSystemNotificationssModel must be called once at startup to configure and
// construct the SystemNotifications model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemNotificationssModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemNotifications]) (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel != nil {
		return systemNotificationssModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemNotificationssCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	mc, err := collection.NewModelCollection[*SystemNotifications](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	systemNotificationssModel = &SystemNotificationss{ModelCollection: mc}
	return systemNotificationssModel, nil
}

// SystemNotificationssModel returns the singleton SystemNotifications model.
func SystemNotificationssModel() (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemNotificationssModel not initialized — call InitSystemNotificationssModel first").
			WithOperation("SystemNotificationssModel")
	}
	return systemNotificationssModel, nil
}

// Deprecated: DangerouslyResetSystemNotificationssModel clears the cached singleton so
// InitSystemNotificationssModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemNotificationssModel() {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel == nil {
		return
	}
	_ = systemNotificationssModel.Close()
	systemNotificationssModel = nil
}
