// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/policies/schema/iam_rule.schema.json
// Date: 2026-07-15T14:48:54Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _iam_rule__0_0_0_to_1_0_0 returns a migration plan for _iam_rule__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _iam_rule__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__iam_rule__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _iam_rule__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__iam_rule__1_0_0 is the target schema serialized from internal/app/policies/schema/iam_rule.schema.json.
var target__iam_rule__1_0_0_json = []byte(`{"version":"1.1.0","name":"_iam_rule_","fields":{"019f32aa-ba8b-7377-ba7c-fd634b2d83f3":{"name":"ruleType","type":"string"},"019f32aa-ba8b-743d-86a5-28354af49391":{"name":"syntax","type":"string"},"019f32aa-ba8b-7cf3-82bd-dacc49029e71":{"name":"expression","type":"string"},"019f32aa-ba8b-7b04-8d18-bf364d909a62":{"name":"rules","type":"string"},"019f32aa-ba8b-7f76-b7e5-cd8c43218d6b":{"name":"description","type":"string"},"019f32aa-ba8b-758b-90c9-f6d64f28bf4d":{"name":"protected","type":"unknown"},"019f32aa-ba8b-727e-a7d5-a7c4412bb37b":{"name":"name","required":true,"type":"string"}}}`)

func target__iam_rule__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__iam_rule__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
