// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/feature/audit/schema/access_log.schema.json
// Date: 2026-07-14T13:50:42Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _access_log__0_0_0_to_1_0_0 returns a migration plan for _access_log__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _access_log__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__access_log__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _access_log__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__access_log__1_0_0 is the target schema serialized from internal/app/feature/audit/schema/access_log.schema.json.
var target__access_log__1_0_0_json = []byte(`{"version":"1.0.0","name":"_access_log_","fields":{"019f32aa-ba8a-7aba-bcee-0c734aaa846d":{"name":"timestamp","required":true,"type":"string"},"019f32aa-ba8a-7a91-8521-8d0a4abda16e":{"name":"request_id","type":"string"},"019f56ff-10d9-7c0d-bfb7-3d132c66c805":{"name":"message_id","type":"string"},"019f32aa-ba8a-7f0a-99ba-546948c78a64":{"name":"error","type":"string"},"019f32aa-ba8a-7789-b8ae-5e67490ea6db":{"name":"latency_ms","type":"integer"},"019f32aa-ba8a-7b67-b241-2f424c6ea04c":{"name":"user_id","type":"string"},"019f32aa-ba8a-73c4-9711-047a4fb3b9ad":{"name":"credential","type":"string"},"019f32aa-ba8a-735c-85af-feac4956ae12":{"name":"message_name","required":true,"type":"string"},"019f32aa-ba8a-7519-873e-c51e4619b4d1":{"name":"status","type":"string"},"019f32aa-ba8a-7a77-980b-379d4d9099f1":{"name":"transport","type":"record"}},"indexes":{"019f32aa-ba8a-7830-bb04-906a46328400":{"name":"idx_timestamp","type":"normal","fields":["timestamp"]},"019f32aa-ba8a-78c2-abc5-454d4ebf9756":{"name":"idx_user_id","type":"normal","fields":["user_id"]},"019f32aa-ba8a-792a-8b3d-485a47188c4a":{"name":"idx_request_id","type":"normal","fields":["request_id"]},"019f32aa-ba8a-7ace-9d7d-088b44709d11":{"name":"idx_message","type":"normal","fields":["message_name"]},"019f32aa-ba8a-7d4f-8953-ad5c4d1ab8af":{"name":"idx_status","type":"normal","fields":["status"]}}}`)

func target__access_log__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__access_log__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
