// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/policies/schema/iam_rule.schema.json
// Date: 2026-07-16T14:51:23Z

package migrations

import (
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _iam_rule__1_0_0_to_1_0_1 returns a migration plan for _iam_rule__1_0_0_to_1_0_1 (1.0.0 → 1.0.1).
func _iam_rule__1_0_0_to_1_0_1() *base.MigrationPlan {
	desc := "auto migration from 1.0.0 to 1.0.1"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__iam_rule__1_0_1(),
		VersionBump: definition.BumpPatch,
	}
	
	return m
}

// target__iam_rule__1_0_1 is the target schema serialized from internal/app/policies/schema/iam_rule.schema.json.
var target__iam_rule__1_0_1_json = []byte(`{"version":"1.1.0","name":"_iam_rule_","fields":{"019f32aa-ba8b-727e-a7d5-a7c4412bb37b":{"name":"name","required":true,"type":"string"},"019f32aa-ba8b-7377-ba7c-fd634b2d83f3":{"name":"ruleType","type":"string"},"019f32aa-ba8b-743d-86a5-28354af49391":{"name":"syntax","type":"string"},"019f32aa-ba8b-7cf3-82bd-dacc49029e71":{"name":"expression","type":"string"},"019f32aa-ba8b-7b04-8d18-bf364d909a62":{"name":"rules","type":"string"},"019f32aa-ba8b-7f76-b7e5-cd8c43218d6b":{"name":"description","type":"string"},"019f32aa-ba8b-758b-90c9-f6d64f28bf4d":{"name":"protected","type":"unknown"}}}`)

func target__iam_rule__1_0_1() *definition.Schema {
	s, err := definition.FromJSON(target__iam_rule__1_0_1_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
