// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/operations/schema/seed.schema.json
// Date: 2026-07-15T14:48:54Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _seed__0_0_0_to_1_0_0 returns a migration plan for _seed__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _seed__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__seed__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _seed__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__seed__1_0_0 is the target schema serialized from internal/app/operations/schema/seed.schema.json.
var target__seed__1_0_0_json = []byte(`{"version":"1.0.0","name":"_seed_","fields":{"019f32aa-ba89-7b6e-98f3-7e2f4867b0f2":{"name":"key","required":true,"type":"string"},"019f32aa-ba89-7151-994b-fed14dc4b1ac":{"name":"value","type":"string"}},"indexes":{"019f32aa-ba8a-733c-80be-12f048d896cd":{"name":"idx_key","type":"unique","fields":["key"]}}}`)

func target__seed__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__seed__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
