// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/feature/policies/schema/policy_operation.schema.json
// Date: 2026-07-14T13:50:42Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _policy_operation__0_0_0_to_1_0_0 returns a migration plan for _policy_operation__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _policy_operation__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__policy_operation__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _policy_operation__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__policy_operation__1_0_0 is the target schema serialized from internal/app/feature/policies/schema/policy_operation.schema.json.
var target__policy_operation__1_0_0_json = []byte(`{"version":"1.0.0","name":"_policy_operation_","fields":{"019f32aa-ba8b-748c-8f2b-68c940329ed0":{"name":"description","type":"string"},"019f32aa-ba8b-7e81-82df-b9f34eddb05d":{"name":"intentType","type":"string"},"019f32aa-ba8b-7db8-817e-7de94fe1ae3d":{"name":"protected","type":"unknown"},"019f32aa-ba8b-797a-bc32-17574381a3b4":{"name":"name","required":true,"type":"string"},"019f32aa-ba8b-7dd9-baef-3fe342578ecc":{"name":"ruleKey","required":true,"type":"string"}}}`)

func target__policy_operation__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__policy_operation__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
