// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/policies/schema/operation_policy.schema.json
// Date: 2026-07-16T14:51:23Z

package migrations

import (
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _operation_policy__1_0_0_to_1_0_1 returns a migration plan for _operation_policy__1_0_0_to_1_0_1 (1.0.0 → 1.0.1).
func _operation_policy__1_0_0_to_1_0_1() *base.MigrationPlan {
	desc := "auto migration from 1.0.0 to 1.0.1"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__operation_policy__1_0_1(),
		VersionBump: definition.BumpPatch,
	}
	
	return m
}

// target__operation_policy__1_0_1 is the target schema serialized from internal/app/policies/schema/operation_policy.schema.json.
var target__operation_policy__1_0_1_json = []byte(`{"version":"1.0.0","name":"_operation_policy_","fields":{"019f32aa-ba8b-797a-bc32-17574381a3b4":{"name":"name","required":true,"type":"string"},"019f32aa-ba8b-7dd9-baef-3fe342578ecc":{"name":"ruleKey","required":true,"type":"string"},"019f32aa-ba8b-748c-8f2b-68c940329ed0":{"name":"description","type":"string"},"019f32aa-ba8b-7e81-82df-b9f34eddb05d":{"name":"intentType","type":"string"},"019f32aa-ba8b-7db8-817e-7de94fe1ae3d":{"name":"protected","type":"unknown"}}}`)

func target__operation_policy__1_0_1() *definition.Schema {
	s, err := definition.FromJSON(target__operation_policy__1_0_1_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
