// Code generated by anansi schema migrate. DO NOT EDIT.
// Source: internal/app/feature/apikeys/schema/api_key.schema.json
// Date: 2026-07-14T13:50:42Z

package migrations

import (
	"context"

	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// _api_key__0_0_0_to_1_0_0 returns a migration plan for _api_key__0_0_0_to_1_0_0 (0.0.0 → 1.0.0).
func _api_key__0_0_0_to_1_0_0() *base.MigrationPlan {
	desc := "auto migration from 0.0.0 to 1.0.0"
	m := &base.MigrationPlan{
		Description: desc,
		Target:      target__api_key__1_0_0(),
		VersionBump: definition.BumpMajor,
	}
	
	m.Transformer = func(ctx context.Context, doc data.Document) (data.Document, error) {
		panic("migrations: _api_key__0_0_0_to_1_0_0: implement transformer or remove this line")
	}
	return m
}

// target__api_key__1_0_0 is the target schema serialized from internal/app/feature/apikeys/schema/api_key.schema.json.
var target__api_key__1_0_0_json = []byte(`{"version":"1.0.0","name":"_api_key_","fields":{"019f32aa-ba8a-7137-a802-606e4d06a033":{"name":"prefix","required":true,"type":"string"},"019f32aa-ba8a-75c8-9aa9-cb904e77891f":{"name":"hash","required":true,"type":"string"},"019f32aa-ba8a-7ce2-9ec2-dd6f4d2f8a15":{"name":"scopes","type":"array","schema":{"id":"019f32aa-ba8a-7226-9382-2607406fb689"}},"019f32aa-ba8a-797f-9766-755f4bfa93fc":{"name":"status","type":"string"},"019f32aa-ba8a-7fc6-b756-ec714d9a8c4a":{"name":"last_used","type":"string"},"019f32aa-ba8a-76db-922d-d3534a208904":{"name":"usage","type":"integer"},"019f32aa-ba8a-7c52-a286-d4de4ee69c69":{"name":"limits","type":"object","schema":{"id":"019f32aa-ba8b-7397-a13f-ce3d4d539f39"}},"019f32aa-ba8a-7acb-adf9-a94f426a9c1e":{"name":"name","required":true,"type":"string"},"019f32aa-ba8a-7418-a2f0-8a84464d9e7c":{"name":"environment","type":"string"},"019f32aa-ba8a-77a7-8a35-cc7048d887bf":{"name":"expiry","type":"string"},"019f32aa-ba8b-78df-9ed2-d5f246c3a93a":{"name":"ip","type":"object","schema":{"id":"019f32aa-ba8b-7d31-9e87-a7e34d2da347"}},"019f32aa-ba8a-7e37-add0-cf5d489ea2b4":{"name":"userId","required":true,"type":"string"}},"schemas":{"019f32aa-ba8b-7397-a13f-ce3d4d539f39":{"name":"Limits","fields":{"019f32aa-ba8b-7072-99db-4cb04c7d9562":{"name":"rph","type":"integer"},"019f32aa-ba8b-742c-8c32-882547698cff":{"name":"rpm","type":"integer"}}},"019f32aa-ba8b-7d31-9e87-a7e34d2da347":{"name":"IPConfig","fields":{"019f32aa-ba8b-75ad-b09b-21584dd3a317":{"name":"whitelist","type":"array","schema":{"id":"019f32aa-ba8b-77a9-b368-358446c283ae"}}}},"019f32aa-ba8b-77a9-b368-358446c283ae":{"name":"IPCIDR","type":"string"},"019f32aa-ba8a-7226-9382-2607406fb689":{"name":"Scope","type":"string"}}}`)

func target__api_key__1_0_0() *definition.Schema {
	s, err := definition.FromJSON(target__api_key__1_0_0_json)
	if err != nil {
		panic("invalid embedded target schema: " + err.Error())
	}
	return s
}
