// Code generated by anansi schema migrate. DO NOT EDIT.
package migrations

import (
	"context"
	"fmt"
	"sort"

	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/schema/definition"
)

// Migration describes a single schema migration.
type Migration struct {
	UUID          string
	Collection    string
	From          string
	To            string
	File          string
	Plan          func() *base.MigrationPlan
	SubMigrations []Migration // populated for squash entries
}

// Plain holds all plain (non-squashed) migrations sorted by UUID.
var Plain = []Migration{
	{UUID: "019f60e4-eaf4-71b3-b94b-8e909b11a8ff", Collection: "_api_key_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-71b3-b94b-8e909b11a8ff__api_key__major.go", Plan: _api_key__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-72f7-bf13-9a98e3831764", Collection: "_access_log_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-72f7-bf13-9a98e3831764__access_log__major.go", Plan: _access_log__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-739e-b796-5a3f84ec2a82", Collection: "_token_blocklist_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-739e-b796-5a3f84ec2a82__token_blocklist__major.go", Plan: _token_blocklist__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-7422-9fbe-e671d38e62d7", Collection: "_seed_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-7422-9fbe-e671d38e62d7__seed__major.go", Plan: _seed__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-74b3-b1f1-c98bad00dbbd", Collection: "_policy_operation_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-74b3-b1f1-c98bad00dbbd__policy_operation__major.go", Plan: _policy_operation__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-7555-8355-7ce436acf5e8", Collection: "_policy_rule_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-7555-8355-7ce436acf5e8__policy_rule__major.go", Plan: _policy_rule__0_0_0_to_1_0_0},
	{UUID: "019f60e4-eaf4-75dd-99dd-3d97c4a71d9c", Collection: "_user_", From: "0.0.0", To: "1.0.0", File: "019f60e4-eaf4-75dd-99dd-3d97c4a71d9c__user__major.go", Plan: _user__0_0_0_to_1_0_0},
}

// Squash holds all squash migrations sorted by UUID.
var Squash = []Migration(nil)

// All merges Plain and Squash, sorted by UUID, and returns them as a single slice.
func All() []Migration {
	all := make([]Migration, 0, len(Plain)+len(Squash))
	all = append(all, Plain...)
	all = append(all, Squash...)
	sort.Slice(all, func(i, j int) bool { return all[i].UUID < all[j].UUID })
	return all
}

// Apply reconciles the database with every registered migration.
//
// For each collection:
//   - If it does not exist, it is created from the first migration's
//     target schema, then remaining migrations are applied in order.
//   - If it exists at a version that matches a migration's From, that
//     migration (and any subsequent pending ones) is applied.
//
// Usage:
//
//	p, cleanup := anansi.Playground(...)
//	defer cleanup()
//	migrations.Apply(ctx, p)
func Apply(ctx context.Context, p base.Persistence) error {
	collMigrations := make(map[string][]Migration)
	for _, m := range All() {
		collMigrations[m.Collection] = append(collMigrations[m.Collection], m)
	}

	for _, ms := range collMigrations {
		name := ms[0].Collection

		exists, err := p.HasCollection(ctx, name)
		if err != nil {
			return fmt.Errorf("check %s: %w", name, err)
		}

		if !exists {
			// Bootstrap from the first migration's target, then apply the rest.
			first := ms[0].Plan().Target
			if err := p.CreateCollections(ctx, []*definition.Schema{first}); err != nil {
				return fmt.Errorf("create %s: %w", name, err)
			}
			ms = ms[1:] // don't re-apply the bootstrap migration
		}

		for _, m := range ms {
			sc, err := p.Schema(ctx, name)
			if err != nil {
				return fmt.Errorf("schema %s: %w", name, err)
			}
			if sc.Version.String() != m.From {
				continue
			}
			plan := m.Plan()
			if _, err := p.Migrate(ctx, name, plan, nil); err != nil {
				return fmt.Errorf("migrate %s %s->%s: %w", name, m.From, m.To, err)
			}
		}
	}
	return nil
}
