package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_settings_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemSettings struct {
	data.DocumentModel
	TenantID  string         `anansi:"tenant_id" json:"tenant_id"`
	UpdatedBy string         `anansi:"updated_by" json:"updated_by"`
	Key       string         `anansi:"key" json:"key"`
	Value     map[string]any `anansi:"value" json:"value"`
}

// NewSystemSettings creates and initializes a new SystemSettings
func NewSystemSettings(model SystemSettings) *SystemSettings {
	return data.New(&model)
}

// SystemSettingss is a type-safe collection for SystemSettings
type SystemSettingss struct {
	base.ModelCollection[SystemSettings, *SystemSettings]
}

const SystemSettingssCollectionName = "_settings_"

var (
	systemSettingssModelMu sync.Mutex
	systemSettingssModel   *SystemSettingss
)

// InitSystemSettingssModel must be called once at startup to configure and
// construct the SystemSettings model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemSettingssModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemSettings, *SystemSettings]) (*SystemSettingss, error) {
	systemSettingssModelMu.Lock()
	defer systemSettingssModelMu.Unlock()
	if systemSettingssModel != nil {
		return systemSettingssModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemSettingssCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSettingssModel").
			WithPath("_settings_")
	}
	mc, err := collection.NewModelCollection[SystemSettings, *SystemSettings](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemSettingssModel").
			WithPath("_settings_")
	}
	systemSettingssModel = &SystemSettingss{ModelCollection: mc}
	return systemSettingssModel, nil
}

// SystemSettingssModel returns the singleton SystemSettings model.
func SystemSettingssModel() (*SystemSettingss, error) {
	systemSettingssModelMu.Lock()
	defer systemSettingssModelMu.Unlock()
	if systemSettingssModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemSettingssModel not initialized — call InitSystemSettingssModel first").
			WithOperation("SystemSettingssModel")
	}
	return systemSettingssModel, nil
}
