// Code generated by cmd/hestia service generate. DO NOT EDIT.

package collections

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the collections service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:collections:collection:list", RuleKey: "root", Description: "List collections"},
		{Name: "system:collections:collection:get", RuleKey: "root", Description: "Get collection"},
		{Name: "system:collections:collection:create", RuleKey: "root", Description: "Create collection via API"},
		{Name: "system:collections:collection:delete", RuleKey: "root", Description: "Delete collection via API"},
		{Name: "system:collections:document:query", RuleKey: "root", Description: "Query collection documents"},
		{Name: "system:collections:document:create", RuleKey: "root", Description: "Create document in collection"},
		{Name: "system:collections:document:get", RuleKey: "root", Description: "Get document from collection"},
		{Name: "system:collections:document:update", RuleKey: "root", Description: "Update document in collection"},
		{Name: "system:collections:document:delete", RuleKey: "root", Description: "Delete document from collection"},
		{Name: "system:collections:document:update_many", RuleKey: "root", Description: "Update documents by filter"},
		{Name: "system:collections:_user:read", RuleKey: "root", Description: "Query users collection"},
		{Name: "system:collections:_api_key:read", RuleKey: "root", Description: "Query API keys collection"},
		{Name: "system:collections:_operation_policy:read", RuleKey: "root", Description: "Query policy operations"},
		{Name: "system:collections:_iam_rule:read", RuleKey: "root", Description: "Query policy rules"},
		{Name: "system:collections:_access_log:read", RuleKey: "root", Description: "Query access logs"},
		{Name: "system:collections:user:query", RuleKey: "root", Description: "Query users collection"},
		{Name: "system:collections:audit_log:query", RuleKey: "root", Description: "Query audit logs"},
		{Name: "system:audit:log:export", RuleKey: "root", Description: "Export audit logs"},
		{Name: "system:collections:operation_policy:query", RuleKey: "root", Description: "Query operation policies"},
		{Name: "system:collections:view:create", RuleKey: "root", Description: "Create view backed by a stored query"},
		{Name: "system:collections:view:refresh", RuleKey: "root", Description: "Refresh materialized view snapshot"},
	}
}
