// Code generated by cmd/hestia service generate. DO NOT EDIT.

package collections

import (
	"context"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	auditmodel "github.com/asaidimu/hestia/core/system/audit/model"
	"github.com/asaidimu/hestia/core/system/collections/model"
	usersmodel "github.com/asaidimu/hestia/core/system/users/model"
)

// RegisterService registers the collections service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*CollectionsService](rt, func(c abstract.Container) (*CollectionsService, error) {
		return NewCollectionsService(c)
	})
}

// Registrations returns the message registrations for the collections service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*CollectionsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:collections:collection:list",
			Description: "List collections",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[model.CollectionListOutput](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ListCollections(ctx, msg)
			},
		},
		{
			Name:        "system:collections:collection:get",
			Description: "Get collection",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CollectionGetInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.CollectionOutput](),
			Handler: dispatch.Handle[model.CollectionGetInput](s.GetCollection),
		},
		{
			Name:        "system:collections:collection:create",
			Description: "Create collection via API",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.CollectionCreateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.CollectionOutput](),
			Handler: dispatch.Handle[model.CollectionCreateInput](s.CreateCollection),
		},
		{
			Name:        "system:collections:collection:delete",
			Description: "Delete collection via API",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CollectionDeleteInput]("input"),
				ResourceIDField: "name",
			},
			Handler: dispatch.Handle[model.CollectionDeleteInput](s.DeleteCollection),
		},
		{
			Name:        "system:collections:document:query",
			Description: "Query collection documents",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.CollectionDocQueryInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.CollectionQueryOutput](),
			Handler: dispatch.Handle[model.CollectionDocQueryInput](s.QueryDocuments),
		},
		{
			Name:        "system:collections:document:create",
			Description: "Create document in collection",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.CollectionDocCreateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.CollectionDocumentOutput](),
			Handler: dispatch.Handle[model.CollectionDocCreateInput](s.CreateDocument),
		},
		{
			Name:        "system:collections:document:get",
			Description: "Get document from collection",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CollectionDocGetInput]("input"),
				ResourceIDField: "doc_id",
			},
			Output:  dispatch.SchemaFromType[model.CollectionDocumentOutput](),
			Handler: dispatch.Handle[model.CollectionDocGetInput](s.GetDocument),
		},
		{
			Name:        "system:collections:document:update",
			Description: "Update document in collection",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CollectionDocUpdateInput]("input"),
				ResourceIDField: "doc_id",
			},
			Output:  dispatch.SchemaFromType[model.CollectionDocumentOutput](),
			Handler: dispatch.Handle[model.CollectionDocUpdateInput](s.UpdateDocument),
		},
		{
			Name:        "system:collections:document:delete",
			Description: "Delete document from collection",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CollectionDocDeleteInput]("input"),
				ResourceIDField: "doc_id",
			},
			Handler: dispatch.Handle[model.CollectionDocDeleteInput](s.DeleteDocument),
		},
		{
			Name:        "system:collections:_user:read",
			Description: "Query users collection",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ReadCollection(ctx, msg)
			},
		},
		{
			Name:        "system:collections:_api_key:read",
			Description: "Query API keys collection",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ReadCollection(ctx, msg)
			},
		},
		{
			Name:        "system:collections:_operation_policy:read",
			Description: "Query policy operations",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ReadCollection(ctx, msg)
			},
		},
		{
			Name:        "system:collections:_iam_rule:read",
			Description: "Query policy rules",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ReadCollection(ctx, msg)
			},
		},
		{
			Name:        "system:collections:_access_log:read",
			Description: "Query access logs",
			Intent:      abstract.Read,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ReadCollection(ctx, msg)
			},
		},
		{
			Name:        "system:collections:user:query",
			Description: "Query users collection",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[usersmodel.UserQueryInput]("input"),
			},
			Output:  dispatch.SchemaFromType[usersmodel.UserQueryOutput](),
			Handler: dispatch.Handle[usersmodel.UserQueryInput](s.QueryUsers),
		},
		{
			Name:        "system:collections:audit_log:query",
			Description: "Query audit logs",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[auditmodel.LogQueryInput]("input"),
			},
			Output:  dispatch.SchemaFromType[auditmodel.LogQueryOutput](),
			Handler: dispatch.Handle[auditmodel.LogQueryInput](s.QueryAuditLogs),
		},
		{
			Name:        "system:audit:log:export",
			Description: "Export audit logs",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[auditmodel.LogQueryInput]("input"),
			},
			Output:  dispatch.SchemaFromType[auditmodel.LogQueryOutput](),
			Handler: dispatch.Handle[auditmodel.LogQueryInput](s.ExportAuditLogs),
		},
	}, nil
}
