package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemUser model in separate Go files,
// using filenames that reflect their purpose (e.g., system_user_validation.go,
// system_user_serialization.go). Avoid throwing all logic into a
// single system_user_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemUser struct {
	data.DocumentModel
	Permissions  []string       `anansi:"permissions,required=false" json:"permissions,omitempty"`
	Email        string         `anansi:"email,required=true" json:"email"`
	Name         string         `anansi:"name,required=true" json:"name"`
	Password     string         `anansi:"password,required=true" json:"password"`
	Data         map[string]any `anansi:"data,required=false" json:"data,omitempty"`
	Disabled     *int64         `anansi:"disabled,required=false,default=-1" json:"disabled,omitempty"`
	Settings     map[string]any `anansi:"settings,required=false" json:"settings,omitempty"`
	TenantID     *string        `anansi:"tenant_id,required=false" json:"tenant_id,omitempty"`
	TokenVersion *int64         `anansi:"token_version,required=false,default=0" json:"token_version,omitempty"`
	Verified     *bool          `anansi:"verified,required=false" json:"verified,omitempty"`
}

// NewSystemUser creates and initializes a new SystemUser
func NewSystemUser(model SystemUser) *SystemUser {
	return data.New(&model)
}

// SystemUsers is a type-safe collection for SystemUser
type SystemUsers struct {
	*collection.ModelCollection[*SystemUser]
}

const SystemUsersCollectionName = "_user_"

var (
	systemUsersModelMu sync.Mutex
	systemUsersModel   *SystemUsers
)

// InitSystemUsersModel must be called once at startup to configure and
// construct the SystemUser model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemUsersModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemUser]) (*SystemUsers, error) {
	systemUsersModelMu.Lock()
	defer systemUsersModelMu.Unlock()
	if systemUsersModel != nil {
		return systemUsersModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemUsersCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemUsersModel").
			WithPath("_user_")
	}
	mc, err := collection.NewModelCollection[*SystemUser](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemUsersModel").
			WithPath("_user_")
	}
	systemUsersModel = &SystemUsers{ModelCollection: mc}
	return systemUsersModel, nil
}

// SystemUsersModel returns the singleton SystemUser model.
func SystemUsersModel() (*SystemUsers, error) {
	systemUsersModelMu.Lock()
	defer systemUsersModelMu.Unlock()
	if systemUsersModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemUsersModel not initialized — call InitSystemUsersModel first").
			WithOperation("SystemUsersModel")
	}
	return systemUsersModel, nil
}

type UserPublic struct {
	data.DocumentModel
	Permissions  []string       `anansi:"permissions,required=false" json:"permissions,omitempty"`
	Email        string         `anansi:"email,required=true" json:"email"`
	Name         string         `anansi:"name,required=true" json:"name"`
	Data         map[string]any `anansi:"data,required=false" json:"data,omitempty"`
	Disabled     *int64         `anansi:"disabled,required=false,default=-1" json:"disabled,omitempty"`
	Settings     map[string]any `anansi:"settings,required=false" json:"settings,omitempty"`
	TenantID     *string        `anansi:"tenant_id,required=false" json:"tenant_id,omitempty"`
	TokenVersion *int64         `anansi:"token_version,required=false,default=0" json:"token_version,omitempty"`
	Verified     *bool          `anansi:"verified,required=false" json:"verified,omitempty"`
}

type UserRegister struct {
	data.DocumentModel
	Email    string         `anansi:"email,required=true" json:"email" input:"payload.email"`
	Name     string         `anansi:"name,required=true" json:"name" input:"payload.name"`
	Password string         `anansi:"password,required=true" json:"password" input:"payload.password"`
	Data     map[string]any `anansi:"data,required=false" json:"data,omitempty" input:"payload.data"`
	TenantID *string        `anansi:"tenant_id,required=false" json:"tenant_id,omitempty" input:"payload.tenant_id"`
}

type UserUpdate struct {
	data.DocumentModel
	Permissions []string       `anansi:"permissions,required=false" json:"permissions,omitempty" input:"payload.permissions"`
	Data        map[string]any `anansi:"data,required=false" json:"data,omitempty" input:"payload.data"`
	Disabled    *int64         `anansi:"disabled,required=false,default=-1" json:"disabled,omitempty" input:"payload.disabled"`
	Email       *string        `anansi:"email,required=false" json:"email,omitempty" input:"payload.email"`
	Name        *string        `anansi:"name,required=false" json:"name,omitempty" input:"payload.name"`
	Settings    map[string]any `anansi:"settings,required=false" json:"settings,omitempty" input:"payload.settings"`
	Verified    *bool          `anansi:"verified,required=false" json:"verified,omitempty" input:"payload.verified"`
}
