package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_user_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemUser struct {
	data.DocumentModel
	Permissions  []string       `anansi:"permissions" json:"permissions"`
	Name         string         `anansi:"name" json:"name"`
	TenantID     string         `anansi:"tenant_id" json:"tenant_id"`
	Email        string         `anansi:"email" json:"email"`
	Password     string         `anansi:"password" json:"password"`
	Data         map[string]any `anansi:"data" json:"data"`
	TokenVersion int64          `anansi:"token_version,default=0" json:"token_version"`
	Settings     map[string]any `anansi:"settings" json:"settings"`
	Disabled     int64          `anansi:"disabled,default=-1" json:"disabled"`
	Verified     bool           `anansi:"verified" json:"verified"`
}

// NewSystemUser creates and initializes a new SystemUser
func NewSystemUser(model SystemUser) *SystemUser {
	return data.New(&model)
}

// SystemUsers is a type-safe collection for SystemUser
type SystemUsers struct {
	base.ModelCollection[SystemUser, *SystemUser]
}

const SystemUsersCollectionName = "_user_"

var (
	systemUsersModelMu sync.Mutex
	systemUsersModel   *SystemUsers
)

// InitSystemUsersModel must be called once at startup to configure and
// construct the SystemUser model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemUsersModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemUser, *SystemUser]) (*SystemUsers, error) {
	systemUsersModelMu.Lock()
	defer systemUsersModelMu.Unlock()
	if systemUsersModel != nil {
		return systemUsersModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemUsersCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemUsersModel").
			WithPath("_user_")
	}
	mc, err := collection.NewModelCollection[SystemUser, *SystemUser](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemUsersModel").
			WithPath("_user_")
	}
	systemUsersModel = &SystemUsers{ModelCollection: mc}
	return systemUsersModel, nil
}

// SystemUsersModel returns the singleton SystemUser model.
func SystemUsersModel() (*SystemUsers, error) {
	systemUsersModelMu.Lock()
	defer systemUsersModelMu.Unlock()
	if systemUsersModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemUsersModel not initialized — call InitSystemUsersModel first").
			WithOperation("SystemUsersModel")
	}
	return systemUsersModel, nil
}
