package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemWorkflowDefinition model in separate Go files,
// using filenames that reflect their purpose (e.g., system_workflow_definition_validation.go,
// system_workflow_definition_serialization.go). Avoid throwing all logic into a
// single system_workflow_definition_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemWorkflowDefinitionMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemWorkflowDefinition struct {
	document.DocumentModel
	ID          string                            `anansi:"_id_,required=true" json:"_id_"`
	Name        string                            `anansi:"name,required=true" json:"name"`
	Metadata    *SystemWorkflowDefinitionMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	CreatedAt   *int64                            `anansi:"created_at,required=false,omitempty" json:"created_at,omitempty"`
	Description *string                           `anansi:"description,required=false,omitempty" json:"description,omitempty"`
	Edges       map[string]any                    `anansi:"edges,required=true" json:"edges"`
	Nodes       map[string]any                    `anansi:"nodes,required=true" json:"nodes"`
	TenantID    *string                           `anansi:"tenant_id,required=false,omitempty" json:"tenant_id,omitempty"`
	UpdatedAt   *int64                            `anansi:"updated_at,required=false,omitempty" json:"updated_at,omitempty"`
}

// GetID returns the document identifier for SystemWorkflowDefinition.
func (m *SystemWorkflowDefinition) GetID() string {
	return m.ID
}

// NewSystemWorkflowDefinition creates and initializes a new SystemWorkflowDefinition
func NewSystemWorkflowDefinition(model SystemWorkflowDefinition) *SystemWorkflowDefinition {
	return document.New(&model)
}

// SystemWorkflowDefinitions is a type-safe collection for SystemWorkflowDefinition
type SystemWorkflowDefinitions struct {
	*collection.ModelCollection[*SystemWorkflowDefinition]
}

const SystemWorkflowDefinitionsCollectionName = "_workflow_definition_"

var (
	systemWorkflowDefinitionsModelMu sync.Mutex
	systemWorkflowDefinitionsModel   *SystemWorkflowDefinitions
)

// InitSystemWorkflowDefinitionsModel must be called once at startup to configure and
// construct the SystemWorkflowDefinition model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemWorkflowDefinitionsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemWorkflowDefinition]) (*SystemWorkflowDefinitions, error) {
	systemWorkflowDefinitionsModelMu.Lock()
	defer systemWorkflowDefinitionsModelMu.Unlock()
	if systemWorkflowDefinitionsModel != nil {
		return systemWorkflowDefinitionsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemWorkflowDefinitionsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemWorkflowDefinitionsModel").
			WithPath("_workflow_definition_")
	}
	mc, err := collection.NewModelCollection[*SystemWorkflowDefinition](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemWorkflowDefinitionsModel").
			WithPath("_workflow_definition_")
	}
	systemWorkflowDefinitionsModel = &SystemWorkflowDefinitions{ModelCollection: mc}
	return systemWorkflowDefinitionsModel, nil
}

// SystemWorkflowDefinitionsModel returns the singleton SystemWorkflowDefinition model.
func SystemWorkflowDefinitionsModel() (*SystemWorkflowDefinitions, error) {
	systemWorkflowDefinitionsModelMu.Lock()
	defer systemWorkflowDefinitionsModelMu.Unlock()
	if systemWorkflowDefinitionsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemWorkflowDefinitionsModel not initialized — call InitSystemWorkflowDefinitionsModel first").
			WithOperation("SystemWorkflowDefinitionsModel")
	}
	return systemWorkflowDefinitionsModel, nil
}

// Deprecated: DangerouslyResetSystemWorkflowDefinitionsModel clears the cached singleton so
// InitSystemWorkflowDefinitionsModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemWorkflowDefinitionsModel() {
	systemWorkflowDefinitionsModelMu.Lock()
	defer systemWorkflowDefinitionsModelMu.Unlock()
	if systemWorkflowDefinitionsModel == nil {
		return
	}
	_ = systemWorkflowDefinitionsModel.Close()
	systemWorkflowDefinitionsModel = nil
}
