package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemOperationPolicy model in separate Go files,
// using filenames that reflect their purpose (e.g., system_operation_policy_validation.go,
// system_operation_policy_serialization.go). Avoid throwing all logic into a
// single system_operation_policy_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemOperationPolicyMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemOperationPolicy struct {
	document.DocumentModel
	Operation           string                         `anansi:"operation,required=true" json:"operation"`
	Rule                string                         `anansi:"rule,required=true" json:"rule"`
	ID                  string                         `anansi:"_id_,required=true" json:"_id_"`
	RateCapacity        *float64                       `anansi:"rate_capacity,required=false,omitempty" json:"rate_capacity,omitempty"`
	RateLimitEnabled    *bool                          `anansi:"rate_limit_enabled,required=false,omitempty" json:"rate_limit_enabled,omitempty"`
	Key                 *string                        `anansi:"key,required=false,omitempty" json:"key,omitempty"`
	Enabled             *bool                          `anansi:"enabled,required=false,omitempty" json:"enabled,omitempty"`
	Protected           *bool                          `anansi:"protected,required=false,omitempty" json:"protected,omitempty"`
	Description         *string                        `anansi:"description,required=false,omitempty" json:"description,omitempty"`
	RateIdentity        *string                        `anansi:"rate_identity,required=false,omitempty" json:"rate_identity,omitempty"`
	IntentType          *string                        `anansi:"intentType,required=false,omitempty" json:"intentType,omitempty"`
	RatePeriod          *float64                       `anansi:"rate_period,required=false,omitempty" json:"rate_period,omitempty"`
	RateRefill          *float64                       `anansi:"rate_refill,required=false,omitempty" json:"rate_refill,omitempty"`
	Metadata            *SystemOperationPolicyMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	TenantID            *string                        `anansi:"tenant_id,required=false,omitempty" json:"tenant_id,omitempty"`
	ThrottleActionInput map[string]any                 `anansi:"throttle_action_input,required=false,omitempty" json:"throttle_action_input,omitempty"`
	ThrottleActionMsg   *string                        `anansi:"throttle_action_msg,required=false,omitempty" json:"throttle_action_msg,omitempty"`
	ThrottleLimit       *float64                       `anansi:"throttle_limit,required=false,omitempty" json:"throttle_limit,omitempty"`
	ThrottleWindow      *float64                       `anansi:"throttle_window,required=false,omitempty" json:"throttle_window,omitempty"`
}

// GetID returns the document identifier for SystemOperationPolicy.
func (m *SystemOperationPolicy) GetID() string {
	return m.ID
}

// NewSystemOperationPolicy creates and initializes a new SystemOperationPolicy
func NewSystemOperationPolicy(model SystemOperationPolicy) *SystemOperationPolicy {
	return document.New(&model)
}

// SystemOperationPolicys is a type-safe collection for SystemOperationPolicy
type SystemOperationPolicys struct {
	*collection.ModelCollection[*SystemOperationPolicy]
}

const SystemOperationPolicysCollectionName = "_operation_policy_"

var (
	systemOperationPolicysModelMu sync.Mutex
	systemOperationPolicysModel   *SystemOperationPolicys
)

// InitSystemOperationPolicysModel must be called once at startup to configure and
// construct the SystemOperationPolicy model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemOperationPolicysModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemOperationPolicy]) (*SystemOperationPolicys, error) {
	systemOperationPolicysModelMu.Lock()
	defer systemOperationPolicysModelMu.Unlock()
	if systemOperationPolicysModel != nil {
		return systemOperationPolicysModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemOperationPolicysCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemOperationPolicysModel").
			WithPath("_operation_policy_")
	}
	mc, err := collection.NewModelCollection[*SystemOperationPolicy](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemOperationPolicysModel").
			WithPath("_operation_policy_")
	}
	systemOperationPolicysModel = &SystemOperationPolicys{ModelCollection: mc}
	return systemOperationPolicysModel, nil
}

// SystemOperationPolicysModel returns the singleton SystemOperationPolicy model.
func SystemOperationPolicysModel() (*SystemOperationPolicys, error) {
	systemOperationPolicysModelMu.Lock()
	defer systemOperationPolicysModelMu.Unlock()
	if systemOperationPolicysModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemOperationPolicysModel not initialized — call InitSystemOperationPolicysModel first").
			WithOperation("SystemOperationPolicysModel")
	}
	return systemOperationPolicysModel, nil
}

// Deprecated: DangerouslyResetSystemOperationPolicysModel clears the cached singleton so
// InitSystemOperationPolicysModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemOperationPolicysModel() {
	systemOperationPolicysModelMu.Lock()
	defer systemOperationPolicysModelMu.Unlock()
	if systemOperationPolicysModel == nil {
		return
	}
	_ = systemOperationPolicysModel.Close()
	systemOperationPolicysModel = nil
}
