package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemAPIKey model in separate Go files,
// using filenames that reflect their purpose (e.g., system_a_p_i_key_validation.go,
// system_a_p_i_key_serialization.go). Avoid throwing all logic into a
// single system_a_p_i_key_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type IPCIDR = string
type Operation = string

type IPConfig struct {
	Whitelist []IPCIDR `anansi:"whitelist,required=false,omitempty" json:"whitelist,omitempty"`
}

type Limits struct {
	Rph *int64 `anansi:"rph,required=false,omitempty" json:"rph,omitempty"`
	Rpm *int64 `anansi:"rpm,required=false,omitempty" json:"rpm,omitempty"`
}

type SystemAPIKeyMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemAPIKey struct {
	document.DocumentModel
	Operations  []Operation           `anansi:"operations,required=false,omitempty" json:"operations,omitempty"`
	Name        string                `anansi:"name,required=true" json:"name"`
	UserID      string                `anansi:"userId,required=true" json:"userId"`
	Prefix      string                `anansi:"prefix,required=true" json:"prefix"`
	ID          string                `anansi:"_id_,required=true" json:"_id_"`
	Hash        string                `anansi:"hash,required=true" json:"hash"`
	Expiry      *string               `anansi:"expiry,required=false,omitempty" json:"expiry,omitempty"`
	Limits      *Limits               `anansi:"limits,required=false,omitempty" json:"limits,omitempty"`
	LastUsed    *string               `anansi:"last_used,required=false,omitempty" json:"last_used,omitempty"`
	Ip          *IPConfig             `anansi:"ip,required=false,omitempty" json:"ip,omitempty"`
	Environment *string               `anansi:"environment,required=false,omitempty" json:"environment,omitempty"`
	Status      *string               `anansi:"status,required=false,omitempty" json:"status,omitempty"`
	Usage       *int64                `anansi:"usage,required=false,omitempty" json:"usage,omitempty"`
	Metadata    *SystemAPIKeyMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
}

// GetID returns the document identifier for SystemAPIKey.
func (m *SystemAPIKey) GetID() string {
	return m.ID
}

// NewSystemAPIKey creates and initializes a new SystemAPIKey
func NewSystemAPIKey(model SystemAPIKey) *SystemAPIKey {
	return document.New(&model)
}

// SystemAPIKeys is a type-safe collection for SystemAPIKey
type SystemAPIKeys struct {
	*collection.ModelCollection[*SystemAPIKey]
}

const SystemAPIKeysCollectionName = "_api_key_"

var (
	systemAPIKeysModelMu sync.Mutex
	systemAPIKeysModel   *SystemAPIKeys
)

// InitSystemAPIKeysModel must be called once at startup to configure and
// construct the SystemAPIKey model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemAPIKeysModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemAPIKey]) (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel != nil {
		return systemAPIKeysModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemAPIKeysCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	mc, err := collection.NewModelCollection[*SystemAPIKey](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	systemAPIKeysModel = &SystemAPIKeys{ModelCollection: mc}
	return systemAPIKeysModel, nil
}

// SystemAPIKeysModel returns the singleton SystemAPIKey model.
func SystemAPIKeysModel() (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemAPIKeysModel not initialized — call InitSystemAPIKeysModel first").
			WithOperation("SystemAPIKeysModel")
	}
	return systemAPIKeysModel, nil
}

// Deprecated: DangerouslyResetSystemAPIKeysModel clears the cached singleton so
// InitSystemAPIKeysModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemAPIKeysModel() {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel == nil {
		return
	}
	_ = systemAPIKeysModel.Close()
	systemAPIKeysModel = nil
}

type APIKeyCreate struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Operations             []Operation `anansi:"operations,required=false,omitempty" json:"operations,omitempty" input:"payload.operations"`
	Name                   string      `anansi:"name,required=true" json:"name" input:"payload.name"`
	Environment            *string     `anansi:"environment,required=false,omitempty" json:"environment,omitempty" input:"payload.environment"`
	Expiry                 *string     `anansi:"expiry,required=false,omitempty" json:"expiry,omitempty" input:"payload.expiry"`
	Ip                     *IPConfig   `anansi:"ip,required=false,omitempty" json:"ip,omitempty" input:"payload.ip"`
	Limits                 *Limits     `anansi:"limits,required=false,omitempty" json:"limits,omitempty" input:"payload.limits"`
}

type APIKeyPublic struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Operations             []Operation           `anansi:"operations,required=false,omitempty" json:"operations,omitempty"`
	Name                   string                `anansi:"name,required=true" json:"name"`
	UserID                 string                `anansi:"userId,required=true" json:"userId"`
	Prefix                 string                `anansi:"prefix,required=true" json:"prefix"`
	ID                     string                `anansi:"_id_,required=true" json:"_id_"`
	Expiry                 *string               `anansi:"expiry,required=false,omitempty" json:"expiry,omitempty"`
	Limits                 *Limits               `anansi:"limits,required=false,omitempty" json:"limits,omitempty"`
	LastUsed               *string               `anansi:"last_used,required=false,omitempty" json:"last_used,omitempty"`
	Ip                     *IPConfig             `anansi:"ip,required=false,omitempty" json:"ip,omitempty"`
	Environment            *string               `anansi:"environment,required=false,omitempty" json:"environment,omitempty"`
	Status                 *string               `anansi:"status,required=false,omitempty" json:"status,omitempty"`
	Usage                  *int64                `anansi:"usage,required=false,omitempty" json:"usage,omitempty"`
	Metadata               *SystemAPIKeyMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
}

type APIKeyUpdate struct {
	document.DocumentModel `json:"-" anansi:"-"`
	Operations             []Operation `anansi:"operations,required=false,omitempty" json:"operations,omitempty" input:"payload.operations"`
	ID                     string      `anansi:"_id_,required=true" json:"_id_" input:"arguments.key_id"`
	Environment            *string     `anansi:"environment,required=false,omitempty" json:"environment,omitempty" input:"payload.environment"`
	Expiry                 *string     `anansi:"expiry,required=false,omitempty" json:"expiry,omitempty" input:"payload.expiry"`
	Ip                     *IPConfig   `anansi:"ip,required=false,omitempty" json:"ip,omitempty" input:"payload.ip"`
	Limits                 *Limits     `anansi:"limits,required=false,omitempty" json:"limits,omitempty" input:"payload.limits"`
	Name                   *string     `anansi:"name,required=false,omitempty" json:"name,omitempty" input:"payload.name"`
	Status                 *string     `anansi:"status,required=false,omitempty" json:"status,omitempty" input:"payload.status"`
}
