// Code generated by cmd/hestia service generate. DO NOT EDIT.

package apikeys

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/apikeys/model"
)

// RegisterService registers the apikeys service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*APIKeysService](rt, func(c abstract.Container) (*APIKeysService, error) {
		return NewAPIKeysService(c)
	})
}

// Registrations returns the message registrations for the apikeys service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*APIKeysService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:apikeys:key:list",
			Description: "List own API keys",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.APIKeyListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[model.APIKeyListInput](s.ListAPIKeys),
		},
		{
			Name:        "system:apikeys:key:get",
			Description: "Get own API key details",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.APIKeyGetInput]("input"),
				ResourceIDField: "key_id",
			},
			Output:  dispatch.SchemaFromType[model.SystemAPIKey](),
			Handler: dispatch.HandleDocument[model.APIKeyGetInput, *model.SystemAPIKey](s.GetAPIKey),
		},
		{
			Name:        "system:apikeys:key:create",
			Description: "Create a new API key",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.APIKeyCreate]("input"),
			},
			Output:  dispatch.SchemaFromType[model.APIKeyCreatedOutput](),
			Handler: dispatch.HandleDocument[model.APIKeyCreate, *model.APIKeyCreatedOutput](s.CreateAPIKey),
		},
		{
			Name:        "system:apikeys:key:update",
			Description: "Update API key metadata",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.APIKeyUpdate]("input"),
				ResourceIDField: "key_id",
			},
			Output:  dispatch.SchemaFromType[model.SystemAPIKey](),
			Handler: dispatch.HandleDocument[model.APIKeyUpdate, *model.SystemAPIKey](s.UpdateAPIKey),
		},
		{
			Name:        "system:apikeys:key:delete",
			Description: "Delete an API key",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.APIKeyDeleteInput]("input"),
				ResourceIDField: "key_id",
			},
			Handler: dispatch.HandleEmpty[model.APIKeyDeleteInput](s.DeleteAPIKey),
		},
		{
			Name:        "system:apikeys:key:rotate",
			Description: "Rotate API key material",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.APIKeyRotateInput]("input"),
				ResourceIDField: "key_id",
			},
			Output:  dispatch.SchemaFromType[model.APIKeyCreatedOutput](),
			Handler: dispatch.HandleDocument[model.APIKeyRotateInput, *model.APIKeyCreatedOutput](s.RotateAPIKey),
		},
	}, nil
}
