// Code generated by cmd/hestia service generate. DO NOT EDIT.

package blobs

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the blobs service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:blobs:namespace:list", RuleKey: "root", Description: "List blob namespaces"},
		{Name: "system:blobs:namespace:create", RuleKey: "root", Description: "Create a blob namespace"},
		{Name: "system:blobs:namespace:delete", RuleKey: "root", Description: "Delete a blob namespace"},
		{Name: "system:blobs:blob:list", RuleKey: "root", Description: "List blobs in a namespace"},
		{Name: "system:blobs:blob:head", RuleKey: "root", Description: "Get blob metadata"},
		{Name: "system:blobs:blob:upload", RuleKey: "root", Description: "Upload a blob"},
		{Name: "system:blobs:blob:download", RuleKey: "root", Description: "Download a blob"},
		{Name: "system:blobs:blob:delete", RuleKey: "root", Description: "Delete a blob"},
		{Name: "system:blobs:blob:update", RuleKey: "root", Description: "Update blob metadata"},
		{Name: "system:blobs:blob:begin", RuleKey: "root", Description: "Begin a resumable blob upload"},
		{Name: "system:blobs:blob:chunk", RuleKey: "root", Description: "Upload a chunk of a resumable blob upload"},
		{Name: "system:blobs:blob:complete", RuleKey: "root", Description: "Complete a resumable blob upload"},
		{Name: "system:blobs:blob:progress", RuleKey: "root", Description: "Report progress of a resumable blob upload"},
		{Name: "system:blobs:blob:abort", RuleKey: "root", Description: "Abort a resumable blob upload"},
		{Name: "system:blobs:blob:rename", RuleKey: "root", Description: "Rename a blob key"},
		{Name: "system:blobs:namespace:stats", RuleKey: "root", Description: "Get namespace stats"},
		{Name: "system:blobs:namespace:verify", RuleKey: "root", Description: "Verify namespace integrity"},
		{Name: "system:blobs:namespace:compact", RuleKey: "root", Description: "Compact a namespace to reclaim space"},
	}
}
