// Code generated by cmd/hestia service generate. DO NOT EDIT.

package blobs

import (
	"context"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/blobs/model"
)

// RegisterService registers the blobs service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*BlobsService](rt, func(c abstract.Container) (*BlobsService, error) {
		return NewBlobsService(c)
	})
}

// Registrations returns the message registrations for the blobs service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*BlobsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:blobs:namespace:list",
			Description: "List blob namespaces",
			Intent:      abstract.Query,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[model.NamespaceListOutput](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				return s.ListNamespaces(ctx, msg)
			},
		},
		{
			Name:        "system:blobs:namespace:create",
			Description: "Create a blob namespace",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.NsCreateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.NamespaceOutput](),
			Handler: dispatch.Handle[model.NsCreateInput](s.CreateNamespace),
		},
		{
			Name:        "system:blobs:namespace:delete",
			Description: "Delete a blob namespace",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.NsInput]("input"),
				ResourceIDField: "ns",
			},
			Handler: dispatch.Handle[model.NsInput](s.DeleteNamespace),
		},
		{
			Name:        "system:blobs:blob:list",
			Description: "List blobs in a namespace",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.BlobListOutput](),
			Handler: dispatch.Handle[model.BlobListInput](s.ListBlobs),
		},
		{
			Name:        "system:blobs:blob:head",
			Description: "Get blob metadata",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.BlobKeyInput]("input"),
				ResourceIDField: "key",
			},
			Output:  dispatch.SchemaFromType[model.BlobMetaOutput](),
			Handler: dispatch.Handle[model.BlobKeyInput](s.HeadBlob),
		},
		{
			Name:        "system:blobs:blob:upload",
			Description: "Upload a blob",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.BlobUploadInput]("input"),
				ResourceIDField: "key",
				HeaderFields: map[string]string{
					"Content-Type": "content_type",
				},
			},
			Output:  dispatch.SchemaFromType[model.BlobMetaOutput](),
			Handler: dispatch.Handle[model.BlobUploadInput](s.UploadBlob),
		},
		{
			Name:        "system:blobs:blob:download",
			Description: "Download a blob",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.BlobKeyInput]("input"),
				ResourceIDField: "key",
			},
			Handler: dispatch.Handle[model.BlobKeyInput](s.DownloadBlob),
		},
		{
			Name:        "system:blobs:blob:delete",
			Description: "Delete a blob",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.BlobKeyInput]("input"),
				ResourceIDField: "key",
			},
			Handler: dispatch.Handle[model.BlobKeyInput](s.DeleteBlob),
		},
		{
			Name:        "system:blobs:blob:update",
			Description: "Update blob metadata",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.BlobUpdateInput]("input"),
				ResourceIDField: "key",
			},
			Output:  dispatch.SchemaFromType[model.BlobMetaOutput](),
			Handler: dispatch.Handle[model.BlobUpdateInput](s.UpdateBlob),
		},
		{
			Name:        "system:blobs:blob:begin",
			Description: "Begin a resumable blob upload",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobBeginInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.UploadBeginOutput](),
			Handler: dispatch.Handle[model.BlobBeginInput](s.BeginUpload),
		},
		{
			Name:        "system:blobs:blob:chunk",
			Description: "Upload a chunk of a resumable blob upload",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobChunkInput]("input"),
				HeaderFields: map[string]string{
					"X-Chunk-SHA256": "sha256",
					"X-Offset":       "offset",
					"X-Session-ID":   "session_id",
				},
			},
			Output:  dispatch.SchemaFromType[model.UploadChunkOutput](),
			Handler: dispatch.Handle[model.BlobChunkInput](s.UploadChunk),
		},
		{
			Name:        "system:blobs:blob:complete",
			Description: "Complete a resumable blob upload",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobCompleteInput]("input"),
				HeaderFields: map[string]string{
					"X-Session-ID": "session_id",
				},
			},
			Output:  dispatch.SchemaFromType[model.BlobMetaOutput](),
			Handler: dispatch.Handle[model.BlobCompleteInput](s.CompleteUpload),
		},
		{
			Name:        "system:blobs:blob:progress",
			Description: "Report progress of a resumable blob upload",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobProgressInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.UploadProgressOutput](),
			Handler: dispatch.Handle[model.BlobProgressInput](s.ProgressUpload),
		},
		{
			Name:        "system:blobs:blob:abort",
			Description: "Abort a resumable blob upload",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.BlobAbortInput]("input"),
				HeaderFields: map[string]string{
					"X-Session-ID": "session_id",
				},
			},
			Handler: dispatch.Handle[model.BlobAbortInput](s.AbortUpload),
		},
	}, nil
}
