// Code generated by cmd/hestia service generate. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	"github.com/asaidimu/hestia/core/runtime"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/operations/model"
)

// RegisterService registers the operations service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*OperationsService](rt, func(c abstract.Container) (*OperationsService, error) {
		return NewOperationsService(c)
	})
}

// Registrations returns the message registrations for the operations service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*OperationsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:          "system:core:heartbeat",
			Description:   "Session keepalive — does not count as a health check",
			Intent:        abstract.Read,
			Enabled:       true,
			BootstrapSafe: true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				if err := s.Heartbeat(ctx, msg); err != nil {
					return nil, err
				}
				return &abstract.Result{}, nil
			},
		},
		{
			Name:          "system:core:health:check",
			Description:   "Check system health and bootstrap status",
			Intent:        abstract.Read,
			Enabled:       true,
			BootstrapSafe: true,
			Output:        dispatch.SchemaFromType[model.HealthView](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				model, err := s.HealthCheck(ctx, msg)
				if err != nil {
					return nil, err
				}
				doc, err := model.Document()
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentResult(doc), nil
			},
		},
		{
			Name:        "system:core:capability:list",
			Description: "List all registered commands and queries with descriptions and enabled status",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[runtime.CapabilitiesDocument](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				model, err := s.ListCapabilities(ctx, msg)
				if err != nil {
					return nil, err
				}
				doc, err := model.Document()
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentResult(doc), nil
			},
		},
		{
			Name:        "system:core:capability:set",
			Description: "Enable or disable a registered command or query",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.CapabilityNameInput]("input"),
				ResourceIDField: "name",
			},
			Handler: dispatch.HandleEmpty[model.CapabilityNameInput](s.SetCapability),
		},
		{
			Name:        "system:core:audit:log",
			Description: "Log an API access entry",
			Intent:      abstract.Create,
			Enabled:     true,
			Internal:    true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				if err := s.LogAccess(ctx, msg); err != nil {
					return nil, err
				}
				return &abstract.Result{}, nil
			},
		},
		{
			Name:          "system:core:docs:list",
			Description:   "List all registered API endpoints with metadata",
			Intent:        abstract.Read,
			Enabled:       true,
			BootstrapSafe: true,
			Output:        dispatch.SchemaFromType[document.Document](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				docs, err := s.DocsList(ctx, msg)
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentsResult(docs), nil
			},
		},
		{
			Name:          "system:core:bootstrap:mark",
			Description:   "Mark system as bootstrapped",
			Intent:        abstract.Create,
			Enabled:       true,
			BootstrapSafe: true,
			Internal:      true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				if err := s.MarkBootstrapped(ctx, msg); err != nil {
					return nil, err
				}
				return &abstract.Result{}, nil
			},
		},
		{
			Name:        "system:core:reset",
			Description: "Reset system to initial state",
			// S-21: a state-changing operation declared as Read maps to GET,
			// inviting prefetchers/crawlers to wipe the system. DELETE requires
			// an explicit request.
			Intent:      abstract.Delete,
			Enabled:     true,
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				if err := s.Reset(ctx, msg); err != nil {
					return nil, err
				}
				return &abstract.Result{}, nil
			},
		},
		{
			Name:        "system:scheduler:job:list",
			Description: "List all registered scheduler jobs",
			Intent:      abstract.Read,
			Enabled:     true,
			Output:      dispatch.SchemaFromType[document.Document](),
			Handler: func(ctx context.Context, msg abstract.Message) (*abstract.Result, error) {
				docs, err := s.SchedulerJobs(ctx, msg)
				if err != nil {
					return nil, err
				}
				return dispatch.NewDocumentsResult(docs), nil
			},
		},
	}, nil
}
