package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemAuditLog model in separate Go files,
// using filenames that reflect their purpose (e.g., system_audit_log_validation.go,
// system_audit_log_serialization.go). Avoid throwing all logic into a
// single system_audit_log_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type ActorType string

const (
	ActorTypeUser      ActorType = "user"
	ActorTypeService   ActorType = "service"
	ActorTypeSystem    ActorType = "system"
	ActorTypeAnonymous ActorType = "anonymous"
)

type AuthMethod string

const (
	AuthMethodPassword       AuthMethod = "password"
	AuthMethodOauth          AuthMethod = "oauth"
	AuthMethodAPIKey         AuthMethod = "api_key"
	AuthMethodMtls           AuthMethod = "mtls"
	AuthMethodSso            AuthMethod = "sso"
	AuthMethodServiceAccount AuthMethod = "service_account"
	AuthMethodNone           AuthMethod = "none"
)

type Operation string

const (
	OperationCreate  Operation = "create"
	OperationRead    Operation = "read"
	OperationUpdate  Operation = "update"
	OperationDelete  Operation = "delete"
	OperationLogin   Operation = "login"
	OperationLogout  Operation = "logout"
	OperationGrant   Operation = "grant"
	OperationRevoke  Operation = "revoke"
	OperationExecute Operation = "execute"
	OperationOther   Operation = "other"
)

type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityCritical Severity = "critical"
)

type Status string

const (
	StatusSuccess Status = "success"
	StatusFailure Status = "failure"
	StatusDenied  Status = "denied"
	StatusError   Status = "error"
)

type SystemAuditLogMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemAuditLog struct {
	document.DocumentModel
	EventName     string                  `anansi:"event_name,required=true" json:"event_name"`
	ServiceName   string                  `anansi:"service_name,required=true" json:"service_name"`
	ActorID       string                  `anansi:"actor_id,required=true" json:"actor_id"`
	ResourceType  string                  `anansi:"resource_type,required=true" json:"resource_type"`
	RecordedAt    string                  `anansi:"recorded_at,required=true" json:"recorded_at"`
	OccurredAt    string                  `anansi:"occurred_at,required=true" json:"occurred_at"`
	ID            string                  `anansi:"_id_,required=true" json:"_id_"`
	EventID       string                  `anansi:"event_id,required=true" json:"event_id"`
	ErrorMessage  *string                 `anansi:"error_message,required=false,omitempty" json:"error_message,omitempty"`
	RequestID     *string                 `anansi:"request_id,required=false,omitempty" json:"request_id,omitempty"`
	LatencyMs     *int64                  `anansi:"latency_ms,required=false,omitempty" json:"latency_ms,omitempty"`
	Metadata      map[string]any          `anansi:"metadata,required=false,omitempty" json:"metadata,omitempty"`
	ErrorCode     *string                 `anansi:"error_code,required=false,omitempty" json:"error_code,omitempty"`
	OnBehalfOfID  *string                 `anansi:"on_behalf_of_id,required=false,omitempty" json:"on_behalf_of_id,omitempty"`
	Operation     Operation               `anansi:"operation,required=true,type=enum" json:"operation"`
	AuthMethod    *AuthMethod             `anansi:"auth_method,required=false,type=enum,omitempty" json:"auth_method,omitempty"`
	Region        *string                 `anansi:"region,required=false,omitempty" json:"region,omitempty"`
	IntegrityHash *string                 `anansi:"integrity_hash,required=false,omitempty" json:"integrity_hash,omitempty"`
	ResourceID    *string                 `anansi:"resource_id,required=false,omitempty" json:"resource_id,omitempty"`
	ActorType     ActorType               `anansi:"actor_type,required=true,type=enum" json:"actor_type"`
	ModelMetadata *SystemAuditLogMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	SessionID     *string                 `anansi:"session_id,required=false,omitempty" json:"session_id,omitempty"`
	Severity      *Severity               `anansi:"severity,required=false,type=enum,omitempty" json:"severity,omitempty"`
	SourceIp      *string                 `anansi:"source_ip,required=false,omitempty" json:"source_ip,omitempty"`
	Status        Status                  `anansi:"status,required=true,type=enum" json:"status"`
	TraceID       *string                 `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	UserAgent     *string                 `anansi:"user_agent,required=false,omitempty" json:"user_agent,omitempty"`
}

// GetID returns the document identifier for SystemAuditLog.
func (m *SystemAuditLog) GetID() string {
	return m.ID
}

// NewSystemAuditLog creates and initializes a new SystemAuditLog
func NewSystemAuditLog(model SystemAuditLog) *SystemAuditLog {
	return document.New(&model)
}

// SystemAuditLogs is a type-safe collection for SystemAuditLog
type SystemAuditLogs struct {
	*collection.ModelCollection[*SystemAuditLog]
}

const SystemAuditLogsCollectionName = "_audit_log_"

var (
	systemAuditLogsModelMu sync.Mutex
	systemAuditLogsModel   *SystemAuditLogs
)

// InitSystemAuditLogsModel must be called once at startup to configure and
// construct the SystemAuditLog model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemAuditLogsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemAuditLog]) (*SystemAuditLogs, error) {
	systemAuditLogsModelMu.Lock()
	defer systemAuditLogsModelMu.Unlock()
	if systemAuditLogsModel != nil {
		return systemAuditLogsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemAuditLogsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAuditLogsModel").
			WithPath("_audit_log_")
	}
	mc, err := collection.NewModelCollection[*SystemAuditLog](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAuditLogsModel").
			WithPath("_audit_log_")
	}
	systemAuditLogsModel = &SystemAuditLogs{ModelCollection: mc}
	return systemAuditLogsModel, nil
}

// SystemAuditLogsModel returns the singleton SystemAuditLog model.
func SystemAuditLogsModel() (*SystemAuditLogs, error) {
	systemAuditLogsModelMu.Lock()
	defer systemAuditLogsModelMu.Unlock()
	if systemAuditLogsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemAuditLogsModel not initialized — call InitSystemAuditLogsModel first").
			WithOperation("SystemAuditLogsModel")
	}
	return systemAuditLogsModel, nil
}

// Deprecated: DangerouslyResetSystemAuditLogsModel clears the cached singleton so
// InitSystemAuditLogsModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemAuditLogsModel() {
	systemAuditLogsModelMu.Lock()
	defer systemAuditLogsModelMu.Unlock()
	if systemAuditLogsModel == nil {
		return
	}
	_ = systemAuditLogsModel.Close()
	systemAuditLogsModel = nil
}
