// Code generated by cmd/hestia service generate. DO NOT EDIT.

package workflows

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the workflows service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:workflows:definition:compile", RuleKey: "root", Description: "Compile a workflow graph into a pipeline definition"},
		{Name: "system:workflows:definition:create", RuleKey: "root", Description: "Store and register a workflow definition"},
		{Name: "system:workflows:definition:delete", RuleKey: "root", Description: "Deregister a workflow definition"},
		{Name: "system:workflows:definition:update", RuleKey: "root", Description: "Update a workflow definition"},
		{Name: "system:workflows:definition:list", RuleKey: "root", Description: "List all workflow definitions"},
		{Name: "system:workflows:definition:get", RuleKey: "root", Description: "Get a workflow definition by ID"},
		{Name: "system:workflows:runtime:run", RuleKey: "root", Description: "Compile and run a workflow graph"},
		{Name: "system:workflows:runtime:events", RuleKey: "root", Description: "Emit a trigger event to the workflow runtime"},
		{Name: "system:workflows:runtime:abort", RuleKey: "root", Description: "Abort a running workflow"},
		{Name: "system:workflows:run:list", RuleKey: "root", Description: "List all workflow runs"},
		{Name: "system:workflows:run:get", RuleKey: "root", Description: "Get workflow run metadata"},
		{Name: "system:workflows:run:outcome", RuleKey: "root", Description: "Get workflow run outcome"},
		{Name: "system:workflows:run:events", RuleKey: "root", Description: "Get timeline events for a workflow run"},
		{Name: "system:workflows:run:store", RuleKey: "root", Description: "Get the live state of a workflow run"},
		{Name: "system:workflows:run:stream", RuleKey: "root", Description: "Stream workflow run events in real-time via SSE"},
		{Name: "system:workflows:registry:list", RuleKey: "root", Description: "List all registered workflow node kind definitions"},
		{Name: "system:workflows:registry:get", RuleKey: "root", Description: "Get a single workflow node kind definition"},
		{Name: "system:workflows:registry:handles", RuleKey: "root", Description: "Get the raw JS handle computation functions for all node kinds"},
		{Name: "system:workflows:runtime:has", RuleKey: "root", Description: "Check if a workflow is registered in the runtime"},
		{Name: "system:workflows:runtime:list", RuleKey: "root", Description: "List IDs of all registered (active) workflows"},
		{Name: "system:workflows:runtime:invoke", RuleKey: "root", Description: "Invoke a registered workflow's trigger directly"},
		{Name: "system:workflows:runtime:resume", RuleKey: "root", Description: "Resume a paused workflow run"},
	}
}
