// Code generated by cmd/hestia service generate. DO NOT EDIT.

package workflows

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the workflows service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:workflows:definition:compile", RuleKey: "administrator", Description: "Compile a workflow graph into a pipeline definition"},
		{Name: "system:workflows:definition:create", RuleKey: "administrator", Description: "Store and register a workflow definition"},
		{Name: "system:workflows:definition:delete", RuleKey: "administrator", Description: "Deregister a workflow definition"},
		{Name: "system:workflows:definition:list", RuleKey: "administrator", Description: "List all workflow definitions"},
		{Name: "system:workflows:definition:get", RuleKey: "administrator", Description: "Get a workflow definition by ID"},
		{Name: "system:workflows:runtime:run", RuleKey: "administrator", Description: "Compile and run a workflow graph"},
		{Name: "system:workflows:runtime:events", RuleKey: "administrator", Description: "Emit a trigger event to the workflow runtime"},
		{Name: "system:workflows:runtime:abort", RuleKey: "administrator", Description: "Abort a running workflow"},
		{Name: "system:workflows:run:list", RuleKey: "administrator", Description: "List all workflow runs"},
		{Name: "system:workflows:run:get", RuleKey: "administrator", Description: "Get workflow run metadata"},
		{Name: "system:workflows:run:outcome", RuleKey: "administrator", Description: "Get workflow run outcome"},
		{Name: "system:workflows:run:events", RuleKey: "administrator", Description: "Get timeline events for a workflow run"},
		{Name: "system:workflows:run:store", RuleKey: "administrator", Description: "Get the live state of a workflow run"},
	}
}
