// Code generated by cmd/hestia service generate. DO NOT EDIT.

package workflows

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
)

// RegisterService registers the workflows service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*WorkflowsService](rt, func(c abstract.Container) (*WorkflowsService, error) {
		return NewWorkflowsService(c)
	})
}

// Registrations returns the message registrations for the workflows service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*WorkflowsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:workflows:definition:compile",
			Description: "Compile a workflow graph into a pipeline definition",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowCompileInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowCompiledView](),
			Handler: dispatch.HandleDocument[WorkflowCompileInput, *WorkflowCompiledView](s.Compile),
		},
		{
			Name:        "system:workflows:definition:create",
			Description: "Store and register a workflow definition",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRegisterInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRegisteredView](),
			Handler: dispatch.HandleDocument[WorkflowRegisterInput, *WorkflowRegisteredView](s.Register),
		},
		{
			Name:        "system:workflows:definition:delete",
			Description: "Deregister a workflow definition",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowDefinitionDeleteInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowMessageOutput](),
			Handler: dispatch.HandleDocument[WorkflowDefinitionDeleteInput, *WorkflowMessageOutput](s.Deregister),
		},
		{
			Name:        "system:workflows:definition:update",
			Description: "Update a workflow definition",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowDefinitionUpdateInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowMessageOutput](),
			Handler: dispatch.HandleDocument[WorkflowDefinitionUpdateInput, *WorkflowMessageOutput](s.Update),
		},
		{
			Name:        "system:workflows:definition:list",
			Description: "List all workflow definitions",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowDefinitionListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[WorkflowDefinitionListInput](s.ListDefinitions),
		},
		{
			Name:        "system:workflows:definition:get",
			Description: "Get a workflow definition by ID",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowDefinitionGetInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowDefinitionView](),
			Handler: dispatch.HandleDocument[WorkflowDefinitionGetInput, *WorkflowDefinitionView](s.GetDefinition),
		},
		{
			Name:        "system:workflows:runtime:run",
			Description: "Compile and run a workflow graph",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRunInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRunStartedView](),
			Handler: dispatch.HandleDocument[WorkflowRunInput, *WorkflowRunStartedView](s.Run),
		},
		{
			Name:        "system:workflows:runtime:events",
			Description: "Emit a trigger event to the workflow runtime",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowEventInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowEventEmittedView](),
			Handler: dispatch.HandleDocument[WorkflowEventInput, *WorkflowEventEmittedView](s.EmitEvent),
		},
		{
			Name:        "system:workflows:runtime:abort",
			Description: "Abort a running workflow",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowAbortInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowAbortedView](),
			Handler: dispatch.HandleDocument[WorkflowAbortInput, *WorkflowAbortedView](s.Abort),
		},
		{
			Name:        "system:workflows:run:list",
			Description: "List all workflow runs",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRunListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[WorkflowRunListInput](s.ListRuns),
		},
		{
			Name:        "system:workflows:run:get",
			Description: "Get workflow run metadata",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunGetInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunMetadataView](),
			Handler: dispatch.HandleDocument[WorkflowRunGetInput, *WorkflowRunMetadataView](s.GetRun),
		},
		{
			Name:        "system:workflows:run:outcome",
			Description: "Get workflow run outcome",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunOutcomeInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunOutcomeView](),
			Handler: dispatch.HandleDocument[WorkflowRunOutcomeInput, *WorkflowRunOutcomeView](s.GetOutcome),
		},
		{
			Name:        "system:workflows:run:events",
			Description: "Get timeline events for a workflow run",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunEventsInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunEventsView](),
			Handler: dispatch.HandleDocument[WorkflowRunEventsInput, *WorkflowRunEventsView](s.GetRunEvents),
		},
		{
			Name:        "system:workflows:run:store",
			Description: "Get the live state of a workflow run",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunStoreInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunStoreView](),
			Handler: dispatch.HandleDocument[WorkflowRunStoreInput, *WorkflowRunStoreView](s.GetRunStore),
		},
		{
			Name:        "system:workflows:run:stream",
			Description: "Stream workflow run events in real-time via SSE",
			Intent:      abstract.Stream,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunStreamInput]("input"),
				ResourceIDField: "run_id",
			},
			Handler: dispatch.Handle[WorkflowRunStreamInput](s.Stream),
		},
		{
			Name:        "system:workflows:registry:list",
			Description: "List all registered workflow node kind definitions",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRegistryListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[NodeRegistryListView](),
			Handler: dispatch.HandleDocument[WorkflowRegistryListInput, *NodeRegistryListView](s.ListRegisteredNodeKinds),
		},
		{
			Name:        "system:workflows:registry:get",
			Description: "Get a single workflow node kind definition",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRegistryGetInput]("input"),
				ResourceIDField: "kind",
			},
			Output:  dispatch.SchemaFromType[NodeRegistryGetView](),
			Handler: dispatch.HandleDocument[WorkflowRegistryGetInput, *NodeRegistryGetView](s.GetRegisteredNodeKind),
		},
		{
			Name:        "system:workflows:registry:handles",
			Description: "Get the raw JS handle computation functions for all node kinds",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRegistryHandlesInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRegistryHandlesView](),
			Handler: dispatch.HandleDocument[WorkflowRegistryHandlesInput, *WorkflowRegistryHandlesView](s.NodeHandlesJS),
		},
		{
			Name:        "system:workflows:runtime:has",
			Description: "Check if a workflow is registered in the runtime",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRuntimeHasInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRuntimeHasView](),
			Handler: dispatch.HandleDocument[WorkflowRuntimeHasInput, *WorkflowRuntimeHasView](s.RuntimeHas),
		},
		{
			Name:        "system:workflows:runtime:list",
			Description: "List IDs of all registered (active) workflows",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRuntimeListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRuntimeListView](),
			Handler: dispatch.HandleDocument[WorkflowRuntimeListInput, *WorkflowRuntimeListView](s.RuntimeListWorkflows),
		},
		{
			Name:        "system:workflows:runtime:invoke",
			Description: "Invoke a registered workflow's trigger directly",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRuntimeInvokeInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRuntimeInvokeView](),
			Handler: dispatch.HandleDocument[WorkflowRuntimeInvokeInput, *WorkflowRuntimeInvokeView](s.RuntimeInvoke),
		},
		{
			Name:        "system:workflows:runtime:resume",
			Description: "Resume a paused workflow run",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRuntimeResumeInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRuntimeResumeView](),
			Handler: dispatch.HandleDocument[WorkflowRuntimeResumeInput, *WorkflowRuntimeResumeView](s.RuntimeResume),
		},
	}, nil
}
