// Code generated by cmd/hestia service generate. DO NOT EDIT.

package workflows

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
)

// RegisterService registers the workflows service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*WorkflowsService](rt, func(c abstract.Container) (*WorkflowsService, error) {
		return NewWorkflowsService(c)
	})
}

// Registrations returns the message registrations for the workflows service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*WorkflowsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:workflows:definition:compile",
			Description: "Compile a workflow graph into a pipeline definition",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowCompileInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowCompiledView](),
			Handler: dispatch.HandleDocument[WorkflowCompileInput, *WorkflowCompiledView](s.Compile),
		},
		{
			Name:        "system:workflows:definition:create",
			Description: "Store and register a workflow definition",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRegisterInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRegisteredView](),
			Handler: dispatch.HandleDocument[WorkflowRegisterInput, *WorkflowRegisteredView](s.Register),
		},
		{
			Name:        "system:workflows:definition:delete",
			Description: "Deregister a workflow definition",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowDefinitionDeleteInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowMessageOutput](),
			Handler: dispatch.HandleDocument[WorkflowDefinitionDeleteInput, *WorkflowMessageOutput](s.Deregister),
		},
		{
			Name:        "system:workflows:definition:list",
			Description: "List all workflow definitions",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowDefinitionListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[WorkflowDefinitionListInput](s.ListDefinitions),
		},
		{
			Name:        "system:workflows:definition:get",
			Description: "Get a workflow definition by ID",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowDefinitionGetInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[WorkflowDefinitionView](),
			Handler: dispatch.HandleDocument[WorkflowDefinitionGetInput, *WorkflowDefinitionView](s.GetDefinition),
		},
		{
			Name:        "system:workflows:runtime:run",
			Description: "Compile and run a workflow graph",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRunInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowRunStartedView](),
			Handler: dispatch.HandleDocument[WorkflowRunInput, *WorkflowRunStartedView](s.Run),
		},
		{
			Name:        "system:workflows:runtime:events",
			Description: "Emit a trigger event to the workflow runtime",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowEventInput]("input"),
			},
			Output:  dispatch.SchemaFromType[WorkflowEventEmittedView](),
			Handler: dispatch.HandleDocument[WorkflowEventInput, *WorkflowEventEmittedView](s.EmitEvent),
		},
		{
			Name:        "system:workflows:runtime:abort",
			Description: "Abort a running workflow",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowAbortInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowAbortedView](),
			Handler: dispatch.HandleDocument[WorkflowAbortInput, *WorkflowAbortedView](s.Abort),
		},
		{
			Name:        "system:workflows:run:list",
			Description: "List all workflow runs",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[WorkflowRunListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[WorkflowRunListInput](s.ListRuns),
		},
		{
			Name:        "system:workflows:run:get",
			Description: "Get workflow run metadata",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunGetInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunMetadataView](),
			Handler: dispatch.HandleDocument[WorkflowRunGetInput, *WorkflowRunMetadataView](s.GetRun),
		},
		{
			Name:        "system:workflows:run:outcome",
			Description: "Get workflow run outcome",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunOutcomeInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunOutcomeView](),
			Handler: dispatch.HandleDocument[WorkflowRunOutcomeInput, *WorkflowRunOutcomeView](s.GetOutcome),
		},
		{
			Name:        "system:workflows:run:events",
			Description: "Get timeline events for a workflow run",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunEventsInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunEventsView](),
			Handler: dispatch.HandleDocument[WorkflowRunEventsInput, *WorkflowRunEventsView](s.GetRunEvents),
		},
		{
			Name:        "system:workflows:run:store",
			Description: "Get the live state of a workflow run",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[WorkflowRunStoreInput]("input"),
				ResourceIDField: "run_id",
			},
			Output:  dispatch.SchemaFromType[WorkflowRunStoreView](),
			Handler: dispatch.HandleDocument[WorkflowRunStoreInput, *WorkflowRunStoreView](s.GetRunStore),
		},
	}, nil
}
