// Code generated by cmd/hestia service generate. DO NOT EDIT.

package system

import "github.com/asaidimu/go-anansi/v8/core/sanitize"

import (
	"github.com/asaidimu/hestia/core/system/apikeys"
	"github.com/asaidimu/hestia/core/system/audit"
	"github.com/asaidimu/hestia/core/system/auth"
	"github.com/asaidimu/hestia/core/system/blobs"
	"github.com/asaidimu/hestia/core/system/collections"
	"github.com/asaidimu/hestia/core/system/logs"
	"github.com/asaidimu/hestia/core/system/notifications"
	"github.com/asaidimu/hestia/core/system/operations"
	"github.com/asaidimu/hestia/core/system/policies"
	"github.com/asaidimu/hestia/core/system/schedules"
	"github.com/asaidimu/hestia/core/system/settings"
	"github.com/asaidimu/hestia/core/system/updates"
	"github.com/asaidimu/hestia/core/system/users"
	"github.com/asaidimu/hestia/core/system/workflows"
)

// allSanitizationRules aggregates every feature's sanitization rules,
// keyed by feature scope. A feature appears here when its package declares
// SanitizationRules() in sanitization.go; add rules for sensitive
// properties by editing that file - never this generated collector.
var allSanitizationRules = func() map[string]*sanitize.FieldMaskConfig {
	m := make(map[string]*sanitize.FieldMaskConfig)
	m["apikeys"] = apikeys.SanitizationRules()
	m["audit"] = audit.SanitizationRules()
	m["auth"] = auth.SanitizationRules()
	m["blobs"] = blobs.SanitizationRules()
	m["collections"] = collections.SanitizationRules()
	m["logs"] = logs.SanitizationRules()
	m["notifications"] = notifications.SanitizationRules()
	m["operations"] = operations.SanitizationRules()
	m["policies"] = policies.SanitizationRules()
	m["schedules"] = schedules.SanitizationRules()
	m["settings"] = settings.SanitizationRules()
	m["updates"] = updates.SanitizationRules()
	m["users"] = users.SanitizationRules()
	m["workflows"] = workflows.SanitizationRules()
	return m
}()
