// Code generated by cmd/hestia service generate. DO NOT EDIT.

package system

import (
	"github.com/asaidimu/hestia/core/abstract"
	"github.com/asaidimu/hestia/core/system/apikeys"
	"github.com/asaidimu/hestia/core/system/auth"
	"github.com/asaidimu/hestia/core/system/blobs"
	"github.com/asaidimu/hestia/core/system/collections"
	"github.com/asaidimu/hestia/core/system/notifications"
	"github.com/asaidimu/hestia/core/system/operations"
	"github.com/asaidimu/hestia/core/system/policies"
	"github.com/asaidimu/hestia/core/system/schedules"
	"github.com/asaidimu/hestia/core/system/settings"
	"github.com/asaidimu/hestia/core/system/updates"
	"github.com/asaidimu/hestia/core/system/users"
)

// RegisterServices registers every service provider into the runtime DI
// container. Call this during module Setup, after runtime-level providers
// (persistence, logger, etc.) have been registered and before the container
// is sealed by the boot phase.
func RegisterServices(rt abstract.Container) error {
	if err := apikeys.RegisterService(rt); err != nil {
		return err
	}
	if err := auth.RegisterService(rt); err != nil {
		return err
	}
	if err := blobs.RegisterService(rt); err != nil {
		return err
	}
	if err := collections.RegisterService(rt); err != nil {
		return err
	}
	if err := notifications.RegisterService(rt); err != nil {
		return err
	}
	if err := operations.RegisterService(rt); err != nil {
		return err
	}
	if err := policies.RegisterService(rt); err != nil {
		return err
	}
	if err := schedules.RegisterService(rt); err != nil {
		return err
	}
	if err := settings.RegisterService(rt); err != nil {
		return err
	}
	if err := updates.RegisterService(rt); err != nil {
		return err
	}
	if err := users.RegisterService(rt); err != nil {
		return err
	}
	return nil
}

// CollectServiceRegistrations returns all message registrations from every
// service. Call this after the container has been sealed, so services can be
// resolved and their registrations collected.
func CollectServiceRegistrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	var regs []abstract.MessageRegistration
	serviceRegs, err := apikeys.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = auth.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = blobs.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = collections.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = notifications.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = operations.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = policies.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = schedules.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = settings.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = updates.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	serviceRegs, err = users.Registrations(rt)
	if err != nil {
		return nil, err
	}
	regs = append(regs, serviceRegs...)
	return regs, nil
}
