package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemIamRule model in separate Go files,
// using filenames that reflect their purpose (e.g., system_iam_rule_validation.go,
// system_iam_rule_serialization.go). Avoid throwing all logic into a
// single system_iam_rule_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemIamRuleMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemIamRule struct {
	document.DocumentModel
	ID          string                 `anansi:"_id_,required=true" json:"_id_"`
	Name        string                 `anansi:"name,required=true" json:"name"`
	Metadata    *SystemIamRuleMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	Description *string                `anansi:"description,required=false,omitempty" json:"description,omitempty"`
	Expression  *string                `anansi:"expression,required=false,omitempty" json:"expression,omitempty"`
	Protected   *bool                  `anansi:"protected,required=false,omitempty" json:"protected,omitempty"`
	RuleType    *string                `anansi:"ruleType,required=false,omitempty" json:"ruleType,omitempty"`
	Rules       *string                `anansi:"rules,required=false,omitempty" json:"rules,omitempty"`
	Syntax      *string                `anansi:"syntax,required=false,omitempty" json:"syntax,omitempty"`
}

// GetID returns the document identifier for SystemIamRule.
func (m *SystemIamRule) GetID() string {
	return m.ID
}

// NewSystemIamRule creates and initializes a new SystemIamRule
func NewSystemIamRule(model SystemIamRule) *SystemIamRule {
	return document.New(&model)
}

// SystemIamRules is a type-safe collection for SystemIamRule
type SystemIamRules struct {
	*collection.ModelCollection[*SystemIamRule]
}

const SystemIamRulesCollectionName = "_iam_rule_"

var (
	systemIamRulesModelMu sync.Mutex
	systemIamRulesModel   *SystemIamRules
)

// InitSystemIamRulesModel must be called once at startup to configure and
// construct the SystemIamRule model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemIamRulesModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemIamRule]) (*SystemIamRules, error) {
	systemIamRulesModelMu.Lock()
	defer systemIamRulesModelMu.Unlock()
	if systemIamRulesModel != nil {
		return systemIamRulesModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemIamRulesCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemIamRulesModel").
			WithPath("_iam_rule_")
	}
	mc, err := collection.NewModelCollection[*SystemIamRule](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemIamRulesModel").
			WithPath("_iam_rule_")
	}
	systemIamRulesModel = &SystemIamRules{ModelCollection: mc}
	return systemIamRulesModel, nil
}

// SystemIamRulesModel returns the singleton SystemIamRule model.
func SystemIamRulesModel() (*SystemIamRules, error) {
	systemIamRulesModelMu.Lock()
	defer systemIamRulesModelMu.Unlock()
	if systemIamRulesModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemIamRulesModel not initialized — call InitSystemIamRulesModel first").
			WithOperation("SystemIamRulesModel")
	}
	return systemIamRulesModel, nil
}

// Deprecated: DangerouslyResetSystemIamRulesModel clears the cached singleton so
// InitSystemIamRulesModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemIamRulesModel() {
	systemIamRulesModelMu.Lock()
	defer systemIamRulesModelMu.Unlock()
	if systemIamRulesModel == nil {
		return
	}
	_ = systemIamRulesModel.Close()
	systemIamRulesModel = nil
}
