package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_scheduled_messages_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemScheduledMessages struct {
	data.DocumentModel
	UserID    string         `anansi:"user_id" json:"user_id"`
	Message   string         `anansi:"message" json:"message"`
	Cron      string         `anansi:"cron" json:"cron"`
	TenantID  string         `anansi:"tenant_id" json:"tenant_id"`
	CreatedAt int64          `anansi:"created_at" json:"created_at"`
	Input     map[string]any `anansi:"input" json:"input"`
	Disabled  bool           `anansi:"disabled" json:"disabled"`
}

// NewSystemScheduledMessages creates and initializes a new SystemScheduledMessages
func NewSystemScheduledMessages(model SystemScheduledMessages) *SystemScheduledMessages {
	return data.New(&model)
}

// SystemScheduledMessagess is a type-safe collection for SystemScheduledMessages
type SystemScheduledMessagess struct {
	base.ModelCollection[SystemScheduledMessages, *SystemScheduledMessages]
}

const SystemScheduledMessagessCollectionName = "_scheduled_messages_"

var (
	systemScheduledMessagessModelMu sync.Mutex
	systemScheduledMessagessModel   *SystemScheduledMessagess
)

// InitSystemScheduledMessagessModel must be called once at startup to configure and
// construct the SystemScheduledMessages model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemScheduledMessagessModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemScheduledMessages, *SystemScheduledMessages]) (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel != nil {
		return systemScheduledMessagessModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemScheduledMessagessCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	mc, err := collection.NewModelCollection[SystemScheduledMessages, *SystemScheduledMessages](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	systemScheduledMessagessModel = &SystemScheduledMessagess{ModelCollection: mc}
	return systemScheduledMessagessModel, nil
}

// SystemScheduledMessagessModel returns the singleton SystemScheduledMessages model.
func SystemScheduledMessagessModel() (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemScheduledMessagessModel not initialized — call InitSystemScheduledMessagessModel first").
			WithOperation("SystemScheduledMessagessModel")
	}
	return systemScheduledMessagessModel, nil
}
