package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemScheduledMessages model in separate Go files,
// using filenames that reflect their purpose (e.g., system_scheduled_messages_validation.go,
// system_scheduled_messages_serialization.go). Avoid throwing all logic into a
// single system_scheduled_messages_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemScheduledMessages struct {
	data.DocumentModel
	Cron      string         `anansi:"cron,required=true" json:"cron"`
	Message   string         `anansi:"message,required=true" json:"message"`
	UserID    string         `anansi:"user_id,required=true" json:"user_id"`
	CreatedAt *int64         `anansi:"created_at,required=false" json:"created_at,omitempty"`
	Disabled  *bool          `anansi:"disabled,required=false" json:"disabled,omitempty"`
	Input     map[string]any `anansi:"input,required=false" json:"input,omitempty"`
	TenantID  *string        `anansi:"tenant_id,required=false" json:"tenant_id,omitempty"`
}

// NewSystemScheduledMessages creates and initializes a new SystemScheduledMessages
func NewSystemScheduledMessages(model SystemScheduledMessages) *SystemScheduledMessages {
	return data.New(&model)
}

// SystemScheduledMessagess is a type-safe collection for SystemScheduledMessages
type SystemScheduledMessagess struct {
	*collection.ModelCollection[*SystemScheduledMessages]
}

const SystemScheduledMessagessCollectionName = "_scheduled_messages_"

var (
	systemScheduledMessagessModelMu sync.Mutex
	systemScheduledMessagessModel   *SystemScheduledMessagess
)

// InitSystemScheduledMessagessModel must be called once at startup to configure and
// construct the SystemScheduledMessages model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemScheduledMessagessModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemScheduledMessages]) (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel != nil {
		return systemScheduledMessagessModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemScheduledMessagessCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	mc, err := collection.NewModelCollection[*SystemScheduledMessages](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	systemScheduledMessagessModel = &SystemScheduledMessagess{ModelCollection: mc}
	return systemScheduledMessagessModel, nil
}

// SystemScheduledMessagessModel returns the singleton SystemScheduledMessages model.
func SystemScheduledMessagessModel() (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemScheduledMessagessModel not initialized — call InitSystemScheduledMessagessModel first").
			WithOperation("SystemScheduledMessagessModel")
	}
	return systemScheduledMessagessModel, nil
}
