package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemTokenBlocklist model in separate Go files,
// using filenames that reflect their purpose (e.g., system_token_blocklist_validation.go,
// system_token_blocklist_serialization.go). Avoid throwing all logic into a
// single system_token_blocklist_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemTokenBlocklist struct {
	data.DocumentModel
	Jti    string `anansi:"jti,required=true" json:"jti"`
	UserID string `anansi:"user_id,required=true" json:"user_id"`
	Exp    int64  `anansi:"exp,required=true" json:"exp"`
}

// NewSystemTokenBlocklist creates and initializes a new SystemTokenBlocklist
func NewSystemTokenBlocklist(model SystemTokenBlocklist) *SystemTokenBlocklist {
	return data.New(&model)
}

// SystemTokenBlocklists is a type-safe collection for SystemTokenBlocklist
type SystemTokenBlocklists struct {
	*collection.ModelCollection[*SystemTokenBlocklist]
}

const SystemTokenBlocklistsCollectionName = "_token_blocklist_"

var (
	systemTokenBlocklistsModelMu sync.Mutex
	systemTokenBlocklistsModel   *SystemTokenBlocklists
)

// InitSystemTokenBlocklistsModel must be called once at startup to configure and
// construct the SystemTokenBlocklist model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemTokenBlocklistsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemTokenBlocklist]) (*SystemTokenBlocklists, error) {
	systemTokenBlocklistsModelMu.Lock()
	defer systemTokenBlocklistsModelMu.Unlock()
	if systemTokenBlocklistsModel != nil {
		return systemTokenBlocklistsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemTokenBlocklistsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTokenBlocklistsModel").
			WithPath("_token_blocklist_")
	}
	mc, err := collection.NewModelCollection[*SystemTokenBlocklist](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemTokenBlocklistsModel").
			WithPath("_token_blocklist_")
	}
	systemTokenBlocklistsModel = &SystemTokenBlocklists{ModelCollection: mc}
	return systemTokenBlocklistsModel, nil
}

// SystemTokenBlocklistsModel returns the singleton SystemTokenBlocklist model.
func SystemTokenBlocklistsModel() (*SystemTokenBlocklists, error) {
	systemTokenBlocklistsModelMu.Lock()
	defer systemTokenBlocklistsModelMu.Unlock()
	if systemTokenBlocklistsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemTokenBlocklistsModel not initialized — call InitSystemTokenBlocklistsModel first").
			WithOperation("SystemTokenBlocklistsModel")
	}
	return systemTokenBlocklistsModel, nil
}
