// Code generated by cmd/hestia service generate. DO NOT EDIT.

package policies

import (
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/policies/model"
)

// RegisterService registers the policies service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*PoliciesService](rt, func(c abstract.Container) (*PoliciesService, error) {
		return NewPoliciesService(c)
	})
}

// Registrations returns the message registrations for the policies service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*PoliciesService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:policies:binding:get",
			Description: "Get binding info",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyBindingGetInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.BindingView](),
			Handler: dispatch.HandleDocument[model.PolicyBindingGetInput, *model.BindingView](s.GetBinding),
		},
		{
			Name:        "system:policies:binding:list",
			Description: "List all bindings",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PolicyBindingListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.BindingListDocument](),
			Handler: dispatch.HandleDocument[model.PolicyBindingListInput, *model.BindingListDocument](s.ListBindings),
		},
		{
			Name:        "system:policies:rule:validate",
			Description: "Validate a CEL rule expression",
			Intent:      abstract.Check,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PolicyValidateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.PolicyValidateResult](),
			Handler: dispatch.HandleDocument[model.PolicyValidateInput, *model.PolicyValidateResult](s.ValidateRule),
		},
		{
			Name:        "system:policies:rule:list",
			Description: "List all rules",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PolicyRuleListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.RuleListDocument](),
			Handler: dispatch.HandleDocument[model.PolicyRuleListInput, *model.RuleListDocument](s.ListRules),
		},
		{
			Name:        "system:policies:rule:get",
			Description: "Get a policy rule",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyRuleGetInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.PolicyRuleView](),
			Handler: dispatch.HandleDocument[model.PolicyRuleGetInput, *model.PolicyRuleView](s.GetRule),
		},
		{
			Name:        "system:policies:rule:create",
			Description: "Create a policy rule",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyRuleCreateInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.PolicyRuleView](),
			Handler: dispatch.HandleDocument[model.PolicyRuleCreateInput, *model.PolicyRuleView](s.CreateRule),
		},
		{
			Name:        "system:policies:rule:update",
			Description: "Update a policy rule",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyRuleUpdateInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.PolicyRuleView](),
			Handler: dispatch.HandleDocument[model.PolicyRuleUpdateInput, *model.PolicyRuleView](s.UpdateRule),
		},
		{
			Name:        "system:policies:rule:delete",
			Description: "Delete a policy rule",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyRuleDeleteInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.RuleDeletedResult](),
			Handler: dispatch.HandleDocument[model.PolicyRuleDeleteInput, *model.RuleDeletedResult](s.DeleteRule),
		},
		{
			Name:        "system:policies:reload",
			Description: "Reload policies from database",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PolicyReloadInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.PolicyReloadResult](),
			Handler: dispatch.HandleDocument[model.PolicyReloadInput, *model.PolicyReloadResult](s.Reload),
		},
		{
			Name:        "system:policies:policy:create",
			Description: "Create a policy binding",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyCreateInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.PolicyView](),
			Handler: dispatch.HandleDocument[model.PolicyCreateInput, *model.PolicyView](s.CreatePolicy),
		},
		{
			Name:        "system:policies:policy:update",
			Description: "Update a policy — set rule, enabled, or both",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.PolicyUpdateInput]("input"),
				ResourceIDField: "name",
			},
			Output:  dispatch.SchemaFromType[model.PolicyView](),
			Handler: dispatch.HandleDocument[model.PolicyUpdateInput, *model.PolicyView](s.UpdatePolicy),
		},
		{
			Name:        "system:policies:policy:list",
			Description: "List all policy bindings",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.PolicyListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.PolicyListDocument](),
			Handler: dispatch.HandleDocument[model.PolicyListInput, *model.PolicyListDocument](s.ListPolicies),
		},
	}, nil
}
