package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// commandFuncName derives the generated Go function name for a command:
// "worker" -> "WorkerModules", "my-app" -> "MyAppModules".
func commandFuncName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '-' || r == '_' || r == ' ' || r == '.'
	})
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String() + "Modules"
}

// commandStubFileName returns the generated file name for a command:
// "worker" -> "worker_modules.go".
func commandStubFileName(name string) string {
	safe := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(name, "-", "_"), " ", "_"))
	return safe + "_modules.go"
}

// commandMainContent returns the main.go source for a command entry point.
func commandMainContent(modulePath, autogenDir, projectName, funcName string) string {
	return fmt.Sprintf(`package main

import (
	"os"

	hestia "github.com/asaidimu/hestia/core"
	%q
)

var version = "dev"

func main() {
	app, err := hestia.Setup(hestia.SetupConfig{
		Version:      version,
		ProjectName:  %q,
		Modules: autogen.%s(),
	})

	if err != nil {
		panic(err)
	}

	if err := app.Start(); err != nil {
		panic(err)
	}
	defer app.Close()

	os.Stdout.Sync()
	select {}
}
`, modulePath+"/"+filepath.ToSlash(autogenDir), projectName, funcName)
}

// writeCommandStub writes the per-command <name>_modules.go stub returning
// nil. Core modules and feature modules from the command's uses list are
// filled in when modules are added or hestia generate runs.
func writeCommandStub(root string, cfg Config, cmdName string) error {
	funcName := commandFuncName(cmdName)
	content := fmt.Sprintf(`// Code generated by cmd/hestia; DO NOT EDIT.

package autogen

import hestia "github.com/asaidimu/hestia/core"

func %s() []hestia.Module {
	return nil
}
`, funcName)
	outPath := filepath.Join(root, cfg.AutogenResolved(), commandStubFileName(cmdName))
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return err
	}
	fmt.Printf("Wrote %s\n", outPath)
	return nil
}

// isHestiaModule walks up from root looking for go.mod declaring the hestia
// library module path.
func isHestiaModule(root string) bool {
	dir := root
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			for i := 0; i < len(data); i++ {
				if data[i] == '\n' || data[i] == '\r' || i == len(data)-1 {
					end := i
					if i == len(data)-1 {
						end = i + 1
					}
					line := string(data[:end])
					if strings.HasPrefix(line, "module ") {
						return strings.TrimSpace(line[7:]) == hestiaLibraryModule
					}
					return false
				}
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return false
		}
		dir = parent
	}
}

const hestiaLibraryModule = "github.com/asaidimu/hestia"
