package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/asaidimu/hestia/cmd/hestia/core/gen"
)

func init() {
	AddCmd.AddCommand(scaffoldModuleCmd)
}

var scaffoldModuleCmd = &cobra.Command{
	Use:   "module <module-name> [feature-name]",
	Short: "Add a new external module",
	Args:  cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		requireRoot()
		if isHestiaModule(rootDir) {
			fmt.Println("Skipping: 'add module' is for downstream projects, not for the hestia library repo itself")
			return
		}
		modName := args[0]
		featureName := modName
		if len(args) >= 2 {
			featureName = args[1]
		}

		modDir := filepath.Join(rootDir, modulesTarget(), modName)
		featureDir := filepath.Join(modDir, featureName)

		if _, err := os.Stat(modDir); err == nil {
			fmt.Fprintf(os.Stderr, "Module %q already exists at %s\n", modName, modDir)
			os.Exit(1)
		}

		os.MkdirAll(featureDir, 0755)

		writeFile(filepath.Join(modDir, "module.go"), scaffoldModule(modName))
		writeFile(filepath.Join(featureDir, "handler.go"), scaffoldHandler(modName, featureName))
		writeFile(filepath.Join(featureDir, "model.go"), scaffoldModel(featureName))

		if err := gen.Generate(featureDir); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to generate initial registrations for %s: %v\n", featureName, err)
			os.Exit(1)
		}
		refreshCollector(modDir)

		fmt.Printf("Scaffolded module %q at %s\n", modName, modDir)
		genModuleRegistry()
	},
}

func writeFile(path, content string) {
	if err := os.WriteFile(path, []byte(content+"\n"), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", path, err)
		os.Exit(1)
	}
}

// scaffoldModule emits module.go. It delegates Setup/Capabilities to the
// generated services.go collector (RegisterServices/CollectServiceRegistrations)
// in the same package, so services added later via 'hestia service new' are
// picked up automatically.
func scaffoldModule(modName string) string {
	return fmt.Sprintf(`package %s

import (
	"context"

	"github.com/asaidimu/hestia/core/abstract"
	module "github.com/asaidimu/hestia/core/runtime/module"
)

type Module struct {
	module.BaseModule
}

func New() *Module {
	return &Module{}
}

func (m *Module) Name() string { return %q }

func (m *Module) Setup(ctx context.Context, rt abstract.Container) error {
	return RegisterServices(rt)
}

func (m *Module) Capabilities(rt abstract.Container) ([]abstract.Capability, error) {
	regs, err := CollectServiceRegistrations(rt)
	if err != nil {
		return nil, err
	}
	return []abstract.Capability{
		{Name: %q, Messages: regs},
	}, nil
}
`, modName, modName, modName)
}

func scaffoldHandler(modName, featureName string) string {
	t := title(featureName)
	return fmt.Sprintf(`package %s

import (
	"context"

	"github.com/asaidimu/hestia/core/abstract"
)

// %sService is the service for the %s domain. Add message handlers as methods
// and annotate them with @hestia.register to have registrations.go and
// policies.go generated by 'hestia service generate'.
type %sService struct {
	store *%sStore
}

func New%sService(rt abstract.Container) (*%sService, error) {
	return &%sService{store: New%sStore()}, nil
}

// Ping answers a liveness check.
//
// @hestia.register(
//   name="%s:%s:ping:check",
//   intent="read",
//   rule="authenticated",
//   description="Ping",
// )
func (s *%sService) Ping(ctx context.Context, msg abstract.Message, input *%sPingInput) (*%sPingResult, error) {
	return &%sPingResult{Pong: true}, nil
}
`,
		featureName, t, featureName,
		t, t, t, t, t, t,
		modName, featureName,
		t, t, t, t,
	)
}

func scaffoldModel(featureName string) string {
	t := title(featureName)
	return fmt.Sprintf(`package %s

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
)

// %sStore is the feature's storage. Replace with a real persistence model
// (see core/system/<feature>/model for the pattern).
type %sStore struct{}

func New%sStore() *%sStore {
	return &%sStore{}
}

// %sPingInput binds the ping request.
type %sPingInput struct {
	Message string `+"`input:\"payload.message\"`"+`
}

// %sPingResult is the ping response. It embeds document.DocumentModel so it
// can be returned from a dispatch.HandleDocument handler.
type %sPingResult struct {
	document.DocumentModel
	Pong bool
}
`, featureName, t, t, t, t, t, t, t, t, t)
}

func title(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
