package core

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/asaidimu/hestia/cmd/hestia/core/gen"
)

var scaffoldModuleCore bool

func init() {
	scaffoldModuleCmd.Flags().BoolVar(&scaffoldModuleCore, "core", false, "Create a shared core module (always loaded) instead of a feature module")
	AddCmd.AddCommand(scaffoldModuleCmd)
}

var scaffoldModuleCmd = &cobra.Command{
	Use:   "module <module-name> [feature-name]",
	Short: "Add a new module",
	Long: `Scaffolds a self-contained module with a stub service, model
directory, and migrations directory.

By default the module is created as a feature module under modules_dir.
With --core it is created as a shared module under core_dir and loaded
by every command.`,
	Args: cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		p, err := newProject(".", false)
		if err != nil {
			return err
		}
		if p.isHestia() {
			return nil
		}
		modName := args[0]
		featureName := modName
		if len(args) >= 2 {
			featureName = args[1]
		}

		target := p.modulesDir()
		if scaffoldModuleCore {
			target = p.coreDir()
		}

		modDir := filepath.Join(p.Root, target, modName)
		featureDir := filepath.Join(modDir, featureName)

		if _, err := os.Stat(modDir); err == nil {
			return fmt.Errorf("module %q already exists at %s", modName, modDir)
		}

		os.MkdirAll(featureDir, 0755)
		os.MkdirAll(filepath.Join(featureDir, "model", "migrations"), 0755)

		if err := writeFile(filepath.Join(modDir, "module.go"), scaffoldModule(modName)); err != nil {
			return err
		}
		if err := writeFile(filepath.Join(featureDir, "handler.go"), scaffoldHandler(modName, featureName)); err != nil {
			return err
		}
		if err := writeFile(filepath.Join(featureDir, "model.go"), scaffoldModel(featureName)); err != nil {
			return err
		}

		if err := gen.Generate(featureDir); err != nil {
			return fmt.Errorf("generate initial registrations for %s: %w", featureName, err)
		}
		if seeded, err := gen.SeedSanitization(featureDir); err != nil {
			return fmt.Errorf("seed sanitization.go for %s: %w", featureName, err)
		} else if seeded {
			fmt.Printf("Generated sanitization.go (seed) for %q\n", featureName)
		}
		if err := p.refreshCollector(modDir); err != nil {
			return err
		}

		fmt.Printf("Scaffolded module %q at %s\n", modName, modDir)
		if err := p.genModuleRegistry(); err != nil {
			return err
		}
		if err := p.regenCommandModules(); err != nil {
			return fmt.Errorf("regenerate command modules: %w", err)
		}
		return nil
	},
}

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content+"\n"), 0644)
}

func scaffoldModule(modName string) string {
	return fmt.Sprintf(`package %s

import (
	"context"

	"github.com/asaidimu/hestia/core/abstract"
	module "github.com/asaidimu/hestia/core/runtime/module"
)

type Module struct {
	module.BaseModule
}

func New() *Module {
	return &Module{}
}

func (m Module) Name() string { return %q }

func (m Module) Setup(ctx context.Context, rt abstract.Container) error {
	return RegisterServices(rt)
}

func (m Module) Capabilities(rt abstract.Container) ([]abstract.Capability, error) {
	regs, err := CollectServiceRegistrations(rt)
	if err != nil {
		return nil, err
	}
	return []abstract.Capability{
		{Name: %q, Messages: regs},
	}, nil
}
`, modName, modName, modName)
}

func scaffoldHandler(modName, featureName string) string {
	t := gen.Title(featureName)
	return fmt.Sprintf(`package %s

import (
	"context"

	"github.com/asaidimu/hestia/core/abstract"
)

// %sService is the service for the %s domain. Add message handlers as methods
// and annotate them with @hestia.register to have registrations.go and
// policies.go generated by 'hestia service generate'.
type %sService struct {
	store *%sStore
}

func New%sService(rt abstract.Container) (*%sService, error) {
	return &%sService{store: New%sStore()}, nil
}

// Ping answers a liveness check.
//
// @hestia.register(
//   name="%s:%s:ping:check",
//   intent="read",
//   rule="authenticated",
//   description="Ping",
// )
func (s *%sService) Ping(ctx context.Context, msg abstract.Message, input *%sPingInput) (*%sPingResult, error) {
	return &%sPingResult{Pong: true}, nil
}
`,
		featureName, t, featureName,
		t, t, t, t, t, t,
		modName, featureName,
		t, t, t, t,
	)
}

func scaffoldModel(featureName string) string {
	t := gen.Title(featureName)
	return fmt.Sprintf(`package %s

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
)

// %sStore is the feature's storage. Replace with a real persistence model
// (see core/system/<feature>/model for the pattern).
type %sStore struct{}

func New%sStore() *%sStore {
	return &%sStore{}
}

// %sPingInput binds the ping request.
type %sPingInput struct {
	Message string `+"`input:\"payload.message\"`"+`
}

// %sPingResult is the ping response. It embeds document.DocumentModel so it
// can be returned from a dispatch.HandleDocument handler.
type %sPingResult struct {
	document.DocumentModel
	Pong bool
}
`, featureName, t, t, t, t, t, t, t, t, t)
}
