package core

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/asaidimu/hestia/cmd/hestia/core/gen"
)

// Project holds all resolved state for a hestia project. Every command
// constructs one via newProject and passes it to helpers — no global state.
type Project struct {
	Root     string // absolute project root (contains hestia.json)
	Cfg      Config
	modPath  string // resolved Go module import path
	autoDir  string // resolved autogen output dir
	modDirs  []string
	forceGen bool // --force flag for generate
}

func newProject(root string, force bool) (*Project, error) {
	cfg := readConfig(root)
	modPath := cfg.Module
	if modPath == "" {
		modPath = detectModulePath(root)
	}
	if modPath == "" {
		return nil, fmt.Errorf("cannot detect module path: set \"module\" in hestia.json or ensure go.mod is present")
	}
	return &Project{
		Root:     root,
		Cfg:      cfg,
		modPath:  modPath,
		autoDir:  cfg.AutogenResolved(),
		modDirs:  effectiveModulesDirs(cfg),
		forceGen: force,
	}, nil
}

func (p *Project) coreDir() string     { return p.Cfg.CoreDirResolved() }
func (p *Project) modulesDir() string  { return p.Cfg.ModulesDirResolved() }
func (p *Project) isHestia() bool      { return isHestiaModule(p.Root) }
func (p *Project) moduleImport(dir string) string {
	rel, err := filepath.Rel(p.Root, dir)
	if err != nil {
		rel = dir
	}
	return p.modPath + "/" + filepath.ToSlash(rel)
}

// discoverModules scans dir (relative to root) for subdirectories containing
// a module.go. Returns package names sorted alphabetically mapped to their
// Go import paths.
func (p *Project) discoverModules(dir string) ([]string, map[string]string) {
	mods := map[string]string{}
	srcDir := filepath.Join(p.Root, dir)
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return nil, mods
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}
		modPath := filepath.Join(srcDir, name, "module.go")
		if _, err := os.Stat(modPath); os.IsNotExist(err) {
			continue
		}
		pkgName := extractPackageName(modPath)
		if pkgName == "" {
			continue
		}
		rel, err := filepath.Rel(p.Root, filepath.Join(srcDir, name))
		if err != nil {
			rel = filepath.Join(dir, name)
		}
		mods[pkgName] = p.modPath + "/" + filepath.ToSlash(rel)
	}
	names := make([]string, 0, len(mods))
	for n := range mods {
		names = append(names, n)
	}
	sort.Strings(names)
	return names, mods
}

// writeCommandModules writes a single command's <name>_modules.go with core
// modules first and the given feature modules after, in uses order. Unknown
// uses entries are skipped with a warning.
func (p *Project) writeCommandModules(cmdName string, coreNames []string, coreImports map[string]string, uses []string, featImports map[string]string) error {
	type modRef struct {
		pkg     string
		import_ string
	}
	var mods []modRef
	seen := map[string]bool{}
	for _, pkg := range coreNames {
		mods = append(mods, modRef{pkg, coreImports[pkg]})
		seen[pkg] = true
	}
	for _, use := range uses {
		imp, ok := featImports[use]
		if !ok {
			fmt.Fprintf(os.Stderr, "Warning: command %q uses unknown module %q, skipping\n", cmdName, use)
			continue
		}
		if seen[use] {
			fmt.Fprintf(os.Stderr, "Warning: module %q is both a core and feature module, using core\n", use)
			continue
		}
		mods = append(mods, modRef{use, imp})
		seen[use] = true
	}

	funcName := commandFuncName(cmdName)
	var b strings.Builder
	b.WriteString("// Code generated by cmd/hestia; DO NOT EDIT.\n")
	b.WriteString("\npackage autogen\n\n")
	if len(mods) == 0 {
		b.WriteString("import hestia \"github.com/asaidimu/hestia/core\"\n\n")
		b.WriteString(fmt.Sprintf("func %s() []hestia.Module {\n\treturn nil\n}\n", funcName))
	} else {
		b.WriteString("import (\n")
		b.WriteString("\thestia \"github.com/asaidimu/hestia/core\"\n")
		imports := make([]string, 0, len(mods))
		for _, m := range mods {
			imports = append(imports, m.import_)
		}
		sort.Strings(imports)
		for _, imp := range imports {
			b.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		b.WriteString(")\n\n")
		b.WriteString(fmt.Sprintf("func %s() []hestia.Module {\n", funcName))
		byPkg := map[string]modRef{}
		for _, m := range mods {
			byPkg[m.pkg] = m
		}
		b.WriteString("\treturn []hestia.Module{\n")
		for _, pkg := range coreNames {
			if _, ok := byPkg[pkg]; ok {
				b.WriteString(fmt.Sprintf("\t\t%s.Module{},\n", pkg))
			}
		}
		for _, use := range uses {
			if _, ok := byPkg[use]; ok {
				isCore := false
				for _, c := range coreNames {
					if c == use {
						isCore = true
						break
					}
				}
				if !isCore {
					b.WriteString(fmt.Sprintf("\t\t%s.Module{},\n", use))
				}
			}
		}
		b.WriteString("\t}\n}\n")
	}

	outPath := filepath.Join(p.Root, p.autoDir, commandStubFileName(cmdName))
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return err
	}
	fmt.Printf("Generated %s with %d modules\n", outPath, len(mods))
	return nil
}

// regenCommandModules regenerates every command's <name>_modules.go file.
func (p *Project) regenCommandModules() error {
	if len(p.Cfg.Commands) == 0 {
		return nil
	}
	modPath := p.Cfg.Module
	if modPath == "" {
		modPath = p.modPath
	}
	coreNames, coreImports := p.discoverModules(p.coreDir())
	_, featImports := p.discoverModules(p.modulesDir())
	featByPkg := featImports

	names := make([]string, 0, len(p.Cfg.Commands))
	for n := range p.Cfg.Commands {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, cmdName := range names {
		uses := p.Cfg.Commands[cmdName].Uses
		if err := p.writeCommandModules(cmdName, coreNames, coreImports, uses, featByPkg); err != nil {
			return err
		}
	}
	return nil
}

// refreshCollector regenerates a module's service collector (services.go)
// and sanitization collector (gen_sanitization.go).
func (p *Project) refreshCollector(moduleDir string) error {
	if _, err := os.Stat(moduleDir); err != nil {
		return nil
	}
	if err := gen.GenerateCollector(moduleDir, p.modPath); err != nil {
		return fmt.Errorf("regenerate service collector: %w", err)
	}
	rel, err := filepath.Rel(p.Root, filepath.Join(moduleDir, "services.go"))
	if err != nil {
		rel = filepath.Join(moduleDir, "services.go")
	}
	fmt.Printf("Generated %s (service collector)\n", rel)

	if err := gen.GenerateSanitizationCollector(moduleDir, p.modPath); err != nil {
		return fmt.Errorf("regenerate sanitization collector: %w", err)
	}
	relSan, err := filepath.Rel(p.Root, filepath.Join(moduleDir, "gen_sanitization.go"))
	if err != nil {
		relSan = filepath.Join(moduleDir, "gen_sanitization.go")
	}
	fmt.Printf("Generated %s (sanitization collector)\n", relSan)
	return nil
}

// allModuleDirs returns every module directory.
func (p *Project) allModuleDirs() []string {
	if p.isHestia() {
		if _, err := os.Stat(filepath.Join(p.Root, "core", "system")); err == nil {
			return []string{filepath.Join(p.Root, "core", "system")}
		}
		return nil
	}
	var dirs []string
	for _, src := range p.modDirs {
		srcDir := filepath.Join(p.Root, src)
		entries, err := os.ReadDir(srcDir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || strings.HasPrefix(entry.Name(), "_") {
				continue
			}
			if _, err := os.Stat(filepath.Join(srcDir, entry.Name(), "module.go")); err != nil {
				continue
			}
			dirs = append(dirs, filepath.Join(srcDir, entry.Name()))
		}
	}
	return dirs
}

// serviceModuleDir resolves the module directory a service belongs to.
func (p *Project) serviceModuleDir(module string) (string, error) {
	if p.isHestia() {
		if module != "" && module != "system" {
			return "", fmt.Errorf("unknown module %q: the hestia library provides only the 'system' module (core/system)", module)
		}
		root := filepath.Join(p.Root, "core", "system")
		if _, err := os.Stat(root); err != nil {
			return "", err
		}
		return root, nil
	}
	if module == "" {
		return "", fmt.Errorf("missing module name: use 'hestia service new <module> <name>'")
	}
	for _, src := range p.modDirs {
		dir := filepath.Join(p.Root, src, module)
		if _, err := os.Stat(filepath.Join(dir, "module.go")); err == nil {
			return dir, nil
		}
	}
	return "", fmt.Errorf("module %q not found under %s (create it first with 'hestia add module %s')", module, strings.Join(p.modDirs, ", "), module)
}

// genModuleRegistry scans configured module dirs, deduplicates by package name,
// and writes the autogen/modules.go registry.
func (p *Project) genModuleRegistry() error {
	if p.isHestia() && !p.forceGen {
		fmt.Println("Skipping module registry generation: running inside the hestia library (use --force to override)")
		return nil
	}
	mods := map[string]string{}
	for _, src := range p.modDirs {
		srcDir := filepath.Join(p.Root, src)
		entries, err := os.ReadDir(srcDir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			name := entry.Name()
			if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
				continue
			}
			modPath := filepath.Join(srcDir, name, "module.go")
			if _, err := os.Stat(modPath); os.IsNotExist(err) {
				continue
			}
			pkgName := extractPackageName(modPath)
			if pkgName == "" {
				continue
			}
			rel, err := filepath.Rel(p.Root, filepath.Join(srcDir, name))
			if err != nil {
				rel = filepath.Join(src, name)
			}
			mods[pkgName] = p.modPath + "/" + filepath.ToSlash(rel)
		}
	}

	if len(mods) == 0 {
		outDir := filepath.Join(p.Root, p.autoDir)
		os.MkdirAll(outDir, 0755)
		outPath := filepath.Join(outDir, "modules.go")
		stub := "// Code generated by cmd/hestia generate; DO NOT EDIT.\n\n// Package autogen is the generated module registry.\npackage autogen\n\nimport  hestia \"github.com/asaidimu/hestia/core\"\n\nfunc Modules() []hestia.Module {\n\treturn nil\n}\n"
		if err := os.WriteFile(outPath, []byte(stub), 0644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		fmt.Printf("Generated %s (no modules found)\n", outPath)
		return nil
	}

	moduleNames := make([]string, 0, len(mods))
	for m := range mods {
		moduleNames = append(moduleNames, m)
	}
	sort.Strings(moduleNames)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/hestia generate; DO NOT EDIT.\n")
	b.WriteString("\n// Package autogen is the generated module registry.\n")
	b.WriteString("package autogen\n\n")
	b.WriteString("import (\n")
	b.WriteString("\thestia \"github.com/asaidimu/hestia/core\"\n")
	for _, m := range moduleNames {
		b.WriteString(fmt.Sprintf("\t%q\n", mods[m]))
	}
	b.WriteString(")\n\n")
	b.WriteString("func Modules() []hestia.Module {\n")
	b.WriteString("\treturn []hestia.Module{\n")
	for _, m := range moduleNames {
		b.WriteString(fmt.Sprintf("\t\t%s.New(),\n", m))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	outDir := filepath.Join(p.Root, p.autoDir)
	os.MkdirAll(outDir, 0755)
	outPath := filepath.Join(outDir, "modules.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("Generated %s with %d modules\n", outPath, len(moduleNames))
	return nil
}

// scanFeatures discovers feature packages under internal/app/ that contain
// a feature.go with a Dependencies struct.
func (p *Project) scanFeatures() ([]featureInfo, error) {
	featureDir := filepath.Join(p.Root, "internal", "app")
	entries, err := os.ReadDir(featureDir)
	if err != nil {
		return nil, fmt.Errorf("read feature directory %s: %w", featureDir, err)
	}

	var features []featureInfo
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}

		regPath := filepath.Join(featureDir, name, "feature.go")
		if _, err := os.Stat(regPath); os.IsNotExist(err) {
			continue
		}

		pkgName := extractPackageName(regPath)
		if pkgName == "" {
			continue
		}

		fields := extractFeatureDeps(regPath)

		features = append(features, featureInfo{
			PkgName: pkgName,
			DirName: name,
			Fields:  fields,
		})
	}

	sortFeatures(features)
	return features, nil
}

// genFeatures regenerates internal/app/gen_features.go from feature annotations.
func (p *Project) genFeatures(features []featureInfo) error {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/hestia generate; DO NOT EDIT.\n")
	b.WriteString("\n// Package app contains generated feature wiring.\n")
	b.WriteString("package app\n\n")
	b.WriteString("import (\n")
	b.WriteString(fmt.Sprintf("\t%q\n", p.modPath+"/core/abstract"))
	for _, f := range features {
		b.WriteString(fmt.Sprintf("\t%q\n", fmt.Sprintf("%s/internal/feature/%s", p.modPath, f.DirName)))
	}
	b.WriteString(")\n\n")

	b.WriteString("var allPolicyBindings = func() []policies.Binding {\n")
	b.WriteString("\tvar all []policies.Binding\n")
	for _, f := range features {
		b.WriteString(fmt.Sprintf("\tall = append(all, %s.PolicyBindings()...)\n", f.PkgName))
	}
	b.WriteString("\treturn all\n")
	b.WriteString("}()\n\n")

	b.WriteString("func collectFeatureRegistrations(m *SystemModule, apiKeyAuth *auth.APIKeyAuthenticator) []abstract.MessageRegistration {\n")
	b.WriteString("\tvar all []abstract.MessageRegistration\n")
	b.WriteString("\tvar allRegs []abstract.MessageRegistration\n\n")

	for _, f := range features {
		b.WriteString(fmt.Sprintf("\t%sDeps := %s.Dependencies{\n", f.PkgName, f.PkgName))
		for _, field := range f.Fields {
			expr := fieldToExpr(field)
			b.WriteString(fmt.Sprintf("\t\t%s: %s,\n", field.Name, expr))
		}
		b.WriteString("\t}\n")
		b.WriteString(fmt.Sprintf("\tall = append(all, %s.Registrations(%sDeps)...)\n", f.PkgName, f.PkgName))
	}

	b.WriteString("\n\tallRegs = all\n")
	b.WriteString("\treturn all\n")
	b.WriteString("}\n")

	outDir := filepath.Join(p.Root, "internal", "app")
	os.MkdirAll(outDir, 0755)
	outPath := filepath.Join(outDir, "gen_features.go")
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write generated file: %w", err)
	}
	fmt.Printf("Generated %s with %d features\n", outPath, len(features))
	return nil
}
