// Code generated by cmd/hestia service generate. DO NOT EDIT.

package logs

import (
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/logs/model"
)

// RegisterService registers the logs service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*LogsService](rt, func(c abstract.Container) (*LogsService, error) {
		return NewLogsService(c)
	})
}

// Registrations returns the message registrations for the logs service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*LogsService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:logs:list",
			Description: "Query application logs",
			Intent:      abstract.Query,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.LogQueryInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.LogListOutput](),
			Handler: dispatch.Handle[model.LogQueryInput](s.Query),
		},
		{
			Name:        "system:logs:stream",
			Description: "Stream live log entries",
			Intent:      abstract.Stream,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.LogStreamInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.LogStreamOutput](),
			Handler: dispatch.Handle[model.LogStreamInput](s.Stream),
		},
	}, nil
}
