// Code generated by cmd/hestia generate; DO NOT EDIT.
package autogen

import (
	"github.com/asaidimu/hestia/internal/abstract"
	"github.com/asaidimu/hestia/module/greeter"
)

func Modules() []abstract.Module {
	return []abstract.Module{
		greeter.New(),
	}
}
