// Code generated by cmd/hestia service generate. DO NOT EDIT.

package schedules

import (
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/schedules/model"
)

// RegisterService registers the schedules service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*SchedulesService](rt, func(c abstract.Container) (*SchedulesService, error) {
		return NewSchedulesService(c)
	})
}

// Registrations returns the message registrations for the schedules service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*SchedulesService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:schedules:schedule:create",
			Description: "Create a cron-triggered schedule",
			Intent:      abstract.Create,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.ScheduleCreateInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.ScheduleCreatedView](),
			Handler: dispatch.HandleDocument[model.ScheduleCreateInput, *model.ScheduleCreatedView](s.Create),
		},
		{
			Name:        "system:schedules:schedule:list",
			Description: "List all schedules",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.ScheduleListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[model.ScheduleListInput](s.List),
		},
		{
			Name:        "system:schedules:schedule:all",
			Description: "List all schedules (admin)",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.ScheduleListInput]("input"),
			},
			Output:  dispatch.SchemaFromType[document.Document](),
			Handler: dispatch.HandleDocuments[model.ScheduleListInput](s.All),
		},
		{
			Name:        "system:schedules:schedule:get",
			Description: "Get a single schedule by ID",
			Intent:      abstract.Read,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.ScheduleGetInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[model.ScheduleDocumentView](),
			Handler: dispatch.HandleDocument[model.ScheduleGetInput, *model.ScheduleDocumentView](s.Get),
		},
		{
			Name:        "system:schedules:schedule:update",
			Description: "Update a schedule",
			Intent:      abstract.Update,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.ScheduleUpdateInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleDocument[model.ScheduleUpdateInput, *model.MessageOutput](s.Update),
		},
		{
			Name:        "system:schedules:schedule:delete",
			Description: "Delete a schedule",
			Intent:      abstract.Delete,
			Enabled:     true,
			Input: abstract.Input{
				Schema:          dispatch.SchemaFromTypeWithTag[model.ScheduleDeleteInput]("input"),
				ResourceIDField: "id",
			},
			Output:  dispatch.SchemaFromType[model.MessageOutput](),
			Handler: dispatch.HandleDocument[model.ScheduleDeleteInput, *model.MessageOutput](s.Delete),
		},
	}, nil
}
