package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemAPIKey model in separate Go files,
// using filenames that reflect their purpose (e.g., system_a_p_i_key_validation.go,
// system_a_p_i_key_serialization.go). Avoid throwing all logic into a
// single system_a_p_i_key_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type IPCIDR = string
type Operation = string

type IPConfig struct {
	Whitelist []IPCIDR `anansi:"whitelist,required=false" json:"whitelist,omitempty"`
}

type Limits struct {
	Rph *int64 `anansi:"rph,required=false" json:"rph,omitempty"`
	Rpm *int64 `anansi:"rpm,required=false" json:"rpm,omitempty"`
}

type SystemAPIKey struct {
	data.DocumentModel
	Operations  []Operation `anansi:"operations,required=false" json:"operations,omitempty"`
	Hash        string      `anansi:"hash,required=true" json:"hash"`
	Name        string      `anansi:"name,required=true" json:"name"`
	Prefix      string      `anansi:"prefix,required=true" json:"prefix"`
	UserID      string      `anansi:"userId,required=true" json:"userId"`
	Environment *string     `anansi:"environment,required=false" json:"environment,omitempty"`
	Expiry      *string     `anansi:"expiry,required=false" json:"expiry,omitempty"`
	Ip          *IPConfig   `anansi:"ip,required=false" json:"ip,omitempty"`
	LastUsed    *string     `anansi:"last_used,required=false" json:"last_used,omitempty"`
	Limits      *Limits     `anansi:"limits,required=false" json:"limits,omitempty"`
	Status      *string     `anansi:"status,required=false" json:"status,omitempty"`
	Usage       *int64      `anansi:"usage,required=false" json:"usage,omitempty"`
}

// NewSystemAPIKey creates and initializes a new SystemAPIKey
func NewSystemAPIKey(model SystemAPIKey) *SystemAPIKey {
	return data.New(&model)
}

// SystemAPIKeys is a type-safe collection for SystemAPIKey
type SystemAPIKeys struct {
	*collection.ModelCollection[*SystemAPIKey]
}

const SystemAPIKeysCollectionName = "_api_key_"

var (
	systemAPIKeysModelMu sync.Mutex
	systemAPIKeysModel   *SystemAPIKeys
)

// InitSystemAPIKeysModel must be called once at startup to configure and
// construct the SystemAPIKey model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemAPIKeysModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemAPIKey]) (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel != nil {
		return systemAPIKeysModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemAPIKeysCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	mc, err := collection.NewModelCollection[*SystemAPIKey](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	systemAPIKeysModel = &SystemAPIKeys{ModelCollection: mc}
	return systemAPIKeysModel, nil
}

// SystemAPIKeysModel returns the singleton SystemAPIKey model.
func SystemAPIKeysModel() (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemAPIKeysModel not initialized — call InitSystemAPIKeysModel first").
			WithOperation("SystemAPIKeysModel")
	}
	return systemAPIKeysModel, nil
}
