package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_a_p_i_key_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type Operation = string
type IPCIDR = string

type Limits struct {
	Rph int64 `anansi:"rph" json:"rph"`
	Rpm int64 `anansi:"rpm" json:"rpm"`
}

type IPConfig struct {
	Whitelist []IPCIDR `anansi:"whitelist" json:"whitelist"`
}

type SystemAPIKey struct {
	data.DocumentModel
	Operations  []Operation `anansi:"operations" json:"operations"`
	Expiry      string      `anansi:"expiry" json:"expiry"`
	Hash        string      `anansi:"hash" json:"hash"`
	LastUsed    string      `anansi:"last_used" json:"last_used"`
	Status      string      `anansi:"status" json:"status"`
	Name        string      `anansi:"name" json:"name"`
	Environment string      `anansi:"environment" json:"environment"`
	UserID      string      `anansi:"userId" json:"userId"`
	Prefix      string      `anansi:"prefix" json:"prefix"`
	Limits      Limits      `anansi:"limits" json:"limits"`
	Usage       int64       `anansi:"usage" json:"usage"`
	Ip          IPConfig    `anansi:"ip" json:"ip"`
}

// NewSystemAPIKey creates and initializes a new SystemAPIKey
func NewSystemAPIKey(model SystemAPIKey) *SystemAPIKey {
	return data.New(&model)
}

// SystemAPIKeys is a type-safe collection for SystemAPIKey
type SystemAPIKeys struct {
	base.ModelCollection[SystemAPIKey, *SystemAPIKey]
}

const SystemAPIKeysCollectionName = "_api_key_"

var (
	systemAPIKeysModelMu sync.Mutex
	systemAPIKeysModel   *SystemAPIKeys
)

// InitSystemAPIKeysModel must be called once at startup to configure and
// construct the SystemAPIKey model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemAPIKeysModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemAPIKey, *SystemAPIKey]) (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel != nil {
		return systemAPIKeysModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemAPIKeysCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	mc, err := collection.NewModelCollection[SystemAPIKey, *SystemAPIKey](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAPIKeysModel").
			WithPath("_api_key_")
	}
	systemAPIKeysModel = &SystemAPIKeys{ModelCollection: mc}
	return systemAPIKeysModel, nil
}

// SystemAPIKeysModel returns the singleton SystemAPIKey model.
func SystemAPIKeysModel() (*SystemAPIKeys, error) {
	systemAPIKeysModelMu.Lock()
	defer systemAPIKeysModelMu.Unlock()
	if systemAPIKeysModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemAPIKeysModel not initialized — call InitSystemAPIKeysModel first").
			WithOperation("SystemAPIKeysModel")
	}
	return systemAPIKeysModel, nil
}
