// Code generated by cmd/hestia service generate. DO NOT EDIT.

package audit

import "github.com/asaidimu/hestia/core/system/policies"

// Policies returns the policy bindings for the audit service.
func Policies() []policies.Binding {
	return []policies.Binding{
		{Name: "system:audit:log:stream", RuleKey: "administrator", Description: "Stream audit log entries in real-time"},
	}
}
