// Code generated by cmd/hestia service generate. DO NOT EDIT.

package audit

import (
	"github.com/asaidimu/hestia/core/abstract"
	dispatch "github.com/asaidimu/hestia/core/runtime/dispatch"
	"github.com/asaidimu/hestia/core/system/audit/model"
)

// RegisterService registers the audit service in the runtime DI
// container so other services can resolve it as a dependency.
func RegisterService(rt abstract.Container) error {
	return abstract.Register[*AuditService](rt, func(c abstract.Container) (*AuditService, error) {
		return NewAuditService(c)
	})
}

// Registrations returns the message registrations for the audit service.
func Registrations(rt abstract.Container) ([]abstract.MessageRegistration, error) {
	s := abstract.MustResolve[*AuditService](rt)
	return []abstract.MessageRegistration{
		{
			Name:        "system:audit:log:stream",
			Description: "Stream audit log entries in real-time",
			Intent:      abstract.Stream,
			Enabled:     true,
			Input: abstract.Input{
				Schema: dispatch.SchemaFromTypeWithTag[model.LogStreamInput]("input"),
			},
			Output:  dispatch.SchemaFromType[model.LogStreamOutput](),
			Handler: dispatch.Handle[model.LogStreamInput](s.Stream),
		},
	}, nil
}
