package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemNotifications model in separate Go files,
// using filenames that reflect their purpose (e.g., system_notifications_validation.go,
// system_notifications_serialization.go). Avoid throwing all logic into a
// single system_notifications_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemNotifications struct {
	data.DocumentModel
	Subject   string         `anansi:"subject,required=true" json:"subject"`
	Type      string         `anansi:"type,required=true" json:"type"`
	UserID    string         `anansi:"user_id,required=true" json:"user_id"`
	Body      *string        `anansi:"body,required=false" json:"body,omitempty"`
	CreatedAt *int64         `anansi:"created_at,required=false" json:"created_at,omitempty"`
	Data      map[string]any `anansi:"data,required=false" json:"data,omitempty"`
	Read      *bool          `anansi:"read,required=false" json:"read,omitempty"`
	TenantID  *string        `anansi:"tenant_id,required=false" json:"tenant_id,omitempty"`
}

// NewSystemNotifications creates and initializes a new SystemNotifications
func NewSystemNotifications(model SystemNotifications) *SystemNotifications {
	return data.New(&model)
}

// SystemNotificationss is a type-safe collection for SystemNotifications
type SystemNotificationss struct {
	*collection.ModelCollection[*SystemNotifications]
}

const SystemNotificationssCollectionName = "_notifications_"

var (
	systemNotificationssModelMu sync.Mutex
	systemNotificationssModel   *SystemNotificationss
)

// InitSystemNotificationssModel must be called once at startup to configure and
// construct the SystemNotifications model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemNotificationssModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemNotifications]) (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel != nil {
		return systemNotificationssModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemNotificationssCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	mc, err := collection.NewModelCollection[*SystemNotifications](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	systemNotificationssModel = &SystemNotificationss{ModelCollection: mc}
	return systemNotificationssModel, nil
}

// SystemNotificationssModel returns the singleton SystemNotifications model.
func SystemNotificationssModel() (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemNotificationssModel not initialized — call InitSystemNotificationssModel first").
			WithOperation("SystemNotificationssModel")
	}
	return systemNotificationssModel, nil
}
