package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_notifications_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemNotifications struct {
	data.DocumentModel
	Body      string         `anansi:"body" json:"body"`
	TenantID  string         `anansi:"tenant_id" json:"tenant_id"`
	UserID    string         `anansi:"user_id" json:"user_id"`
	Type      string         `anansi:"type" json:"type"`
	Subject   string         `anansi:"subject" json:"subject"`
	Data      map[string]any `anansi:"data" json:"data"`
	CreatedAt int64          `anansi:"created_at" json:"created_at"`
	Read      bool           `anansi:"read" json:"read"`
}

// NewSystemNotifications creates and initializes a new SystemNotifications
func NewSystemNotifications(model SystemNotifications) *SystemNotifications {
	return data.New(&model)
}

// SystemNotificationss is a type-safe collection for SystemNotifications
type SystemNotificationss struct {
	base.ModelCollection[SystemNotifications, *SystemNotifications]
}

const SystemNotificationssCollectionName = "_notifications_"

var (
	systemNotificationssModelMu sync.Mutex
	systemNotificationssModel   *SystemNotificationss
)

// InitSystemNotificationssModel must be called once at startup to configure and
// construct the SystemNotifications model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemNotificationssModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemNotifications, *SystemNotifications]) (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel != nil {
		return systemNotificationssModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemNotificationssCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	mc, err := collection.NewModelCollection[SystemNotifications, *SystemNotifications](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemNotificationssModel").
			WithPath("_notifications_")
	}
	systemNotificationssModel = &SystemNotificationss{ModelCollection: mc}
	return systemNotificationssModel, nil
}

// SystemNotificationssModel returns the singleton SystemNotifications model.
func SystemNotificationssModel() (*SystemNotificationss, error) {
	systemNotificationssModelMu.Lock()
	defer systemNotificationssModelMu.Unlock()
	if systemNotificationssModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemNotificationssModel not initialized — call InitSystemNotificationssModel first").
			WithOperation("SystemNotificationssModel")
	}
	return systemNotificationssModel, nil
}
