package model

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Add custom methods to the SystemScheduledMessages model in separate Go files,
// using filenames that reflect their purpose (e.g., system_scheduled_messages_validation.go,
// system_scheduled_messages_serialization.go). Avoid throwing all logic into a
// single system_scheduled_messages_utils.go file.
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/document"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemScheduledMessagesMetadata struct {
	Checksum  string  `anansi:"checksum,required=true" json:"checksum"`
	Created   string  `anansi:"created,required=true" json:"created"`
	Updated   string  `anansi:"updated,required=true" json:"updated"`
	Signature *string `anansi:"signature,required=false,omitempty" json:"signature,omitempty"`
	TraceID   *string `anansi:"trace_id,required=false,omitempty" json:"trace_id,omitempty"`
	Version   float64 `anansi:"version,required=true" json:"version"`
}

type SystemScheduledMessages struct {
	document.DocumentModel
	ID        string                           `anansi:"_id_,required=true" json:"_id_"`
	Cron      string                           `anansi:"cron,required=true" json:"cron"`
	Message   string                           `anansi:"message,required=true" json:"message"`
	UserID    string                           `anansi:"user_id,required=true" json:"user_id"`
	Metadata  *SystemScheduledMessagesMetadata `anansi:"_metadata_,required=false,omitempty" json:"_metadata_,omitempty"`
	CreatedAt *int64                           `anansi:"created_at,required=false,omitempty" json:"created_at,omitempty"`
	Disabled  *bool                            `anansi:"disabled,required=false,omitempty" json:"disabled,omitempty"`
	Input     map[string]any                   `anansi:"input,required=false,omitempty" json:"input,omitempty"`
	Protected *bool                            `anansi:"protected,required=false,omitempty" json:"protected,omitempty"`
	TenantID  *string                          `anansi:"tenant_id,required=false,omitempty" json:"tenant_id,omitempty"`
}

// GetID returns the document identifier for SystemScheduledMessages.
func (m *SystemScheduledMessages) GetID() string {
	return m.ID
}

// NewSystemScheduledMessages creates and initializes a new SystemScheduledMessages
func NewSystemScheduledMessages(model SystemScheduledMessages) *SystemScheduledMessages {
	return document.New(&model)
}

// SystemScheduledMessagess is a type-safe collection for SystemScheduledMessages
type SystemScheduledMessagess struct {
	*collection.ModelCollection[*SystemScheduledMessages]
}

const SystemScheduledMessagessCollectionName = "_scheduled_messages_"

var (
	systemScheduledMessagessModelMu sync.Mutex
	systemScheduledMessagessModel   *SystemScheduledMessagess
)

// InitSystemScheduledMessagessModel must be called once at startup to configure and
// construct the SystemScheduledMessages model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemScheduledMessagessModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[*SystemScheduledMessages]) (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel != nil {
		return systemScheduledMessagessModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemScheduledMessagessCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	mc, err := collection.NewModelCollection[*SystemScheduledMessages](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemScheduledMessagessModel").
			WithPath("_scheduled_messages_")
	}
	systemScheduledMessagessModel = &SystemScheduledMessagess{ModelCollection: mc}
	return systemScheduledMessagessModel, nil
}

// SystemScheduledMessagessModel returns the singleton SystemScheduledMessages model.
func SystemScheduledMessagessModel() (*SystemScheduledMessagess, error) {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemScheduledMessagessModel not initialized — call InitSystemScheduledMessagessModel first").
			WithOperation("SystemScheduledMessagessModel")
	}
	return systemScheduledMessagessModel, nil
}

// Deprecated: DangerouslyResetSystemScheduledMessagessModel clears the cached singleton so
// InitSystemScheduledMessagessModel can be called again — for example after rebuilding the
// persistence layer in tests. It closes the previous instance's managed
// cache, if any. Never use in production code.
func DangerouslyResetSystemScheduledMessagessModel() {
	systemScheduledMessagessModelMu.Lock()
	defer systemScheduledMessagessModelMu.Unlock()
	if systemScheduledMessagessModel == nil {
		return
	}
	_ = systemScheduledMessagessModel.Close()
	systemScheduledMessagessModel = nil
}
