package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_audit_log_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type ActorType string

const (
	ActorTypeUser      ActorType = "user"
	ActorTypeService   ActorType = "service"
	ActorTypeSystem    ActorType = "system"
	ActorTypeAnonymous ActorType = "anonymous"
)

type AuthMethod string

const (
	AuthMethodPassword       AuthMethod = "password"
	AuthMethodOauth          AuthMethod = "oauth"
	AuthMethodAPIKey         AuthMethod = "api_key"
	AuthMethodMtls           AuthMethod = "mtls"
	AuthMethodSso            AuthMethod = "sso"
	AuthMethodServiceAccount AuthMethod = "service_account"
	AuthMethodNone           AuthMethod = "none"
)

type Operation string

const (
	OperationCreate  Operation = "create"
	OperationRead    Operation = "read"
	OperationUpdate  Operation = "update"
	OperationDelete  Operation = "delete"
	OperationLogin   Operation = "login"
	OperationLogout  Operation = "logout"
	OperationGrant   Operation = "grant"
	OperationRevoke  Operation = "revoke"
	OperationExecute Operation = "execute"
	OperationOther   Operation = "other"
)

type Status string

const (
	StatusSuccess Status = "success"
	StatusFailure Status = "failure"
	StatusDenied  Status = "denied"
	StatusError   Status = "error"
)

type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityCritical Severity = "critical"
)

type SystemAuditLog struct {
	data.DocumentModel
	ErrorCode     string         `anansi:"error_code" json:"error_code"`
	Region        string         `anansi:"region" json:"region"`
	SessionID     string         `anansi:"session_id" json:"session_id"`
	UserAgent     string         `anansi:"user_agent" json:"user_agent"`
	ErrorMessage  string         `anansi:"error_message" json:"error_message"`
	ActorID       string         `anansi:"actor_id" json:"actor_id"`
	SourceIp      string         `anansi:"source_ip" json:"source_ip"`
	EventID       string         `anansi:"event_id" json:"event_id"`
	RequestID     string         `anansi:"request_id" json:"request_id"`
	EventName     string         `anansi:"event_name" json:"event_name"`
	TraceID       string         `anansi:"trace_id" json:"trace_id"`
	IntegrityHash string         `anansi:"integrity_hash" json:"integrity_hash"`
	RecordedAt    string         `anansi:"recorded_at" json:"recorded_at"`
	OccurredAt    string         `anansi:"occurred_at" json:"occurred_at"`
	ServiceName   string         `anansi:"service_name" json:"service_name"`
	ResourceID    string         `anansi:"resource_id" json:"resource_id"`
	OnBehalfOfID  string         `anansi:"on_behalf_of_id" json:"on_behalf_of_id"`
	ResourceType  string         `anansi:"resource_type" json:"resource_type"`
	LatencyMs     int64          `anansi:"latency_ms" json:"latency_ms"`
	Severity      Severity       `anansi:"severity,type=enum" json:"severity"`
	Operation     Operation      `anansi:"operation,type=enum" json:"operation"`
	Status        Status         `anansi:"status,type=enum" json:"status"`
	AuthMethod    AuthMethod     `anansi:"auth_method,type=enum" json:"auth_method"`
	ActorType     ActorType      `anansi:"actor_type,type=enum" json:"actor_type"`
	Metadata      map[string]any `anansi:"metadata" json:"metadata"`
}

// NewSystemAuditLog creates and initializes a new SystemAuditLog
func NewSystemAuditLog(model SystemAuditLog) *SystemAuditLog {
	return data.New(&model)
}

// SystemAuditLogs is a type-safe collection for SystemAuditLog
type SystemAuditLogs struct {
	base.ModelCollection[SystemAuditLog, *SystemAuditLog]
}

const SystemAuditLogsCollectionName = "_audit_log_"

var (
	systemAuditLogsModelMu sync.Mutex
	systemAuditLogsModel   *SystemAuditLogs
)

// InitSystemAuditLogsModel must be called once at startup to configure and
// construct the SystemAuditLog model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemAuditLogsModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemAuditLog, *SystemAuditLog]) (*SystemAuditLogs, error) {
	systemAuditLogsModelMu.Lock()
	defer systemAuditLogsModelMu.Unlock()
	if systemAuditLogsModel != nil {
		return systemAuditLogsModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemAuditLogsCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAuditLogsModel").
			WithPath("_audit_log_")
	}
	mc, err := collection.NewModelCollection[SystemAuditLog, *SystemAuditLog](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemAuditLogsModel").
			WithPath("_audit_log_")
	}
	systemAuditLogsModel = &SystemAuditLogs{ModelCollection: mc}
	return systemAuditLogsModel, nil
}

// SystemAuditLogsModel returns the singleton SystemAuditLog model.
func SystemAuditLogsModel() (*SystemAuditLogs, error) {
	systemAuditLogsModelMu.Lock()
	defer systemAuditLogsModelMu.Unlock()
	if systemAuditLogsModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemAuditLogsModel not initialized — call InitSystemAuditLogsModel first").
			WithOperation("SystemAuditLogsModel")
	}
	return systemAuditLogsModel, nil
}
