package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_iam_rule_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemIamRule struct {
	data.DocumentModel
	Syntax      string `anansi:"syntax" json:"syntax"`
	Expression  string `anansi:"expression" json:"expression"`
	Rules       string `anansi:"rules" json:"rules"`
	Description string `anansi:"description" json:"description"`
	Name        string `anansi:"name" json:"name"`
	RuleType    string `anansi:"ruleType" json:"ruleType"`
	Protected   bool   `anansi:"protected" json:"protected"`
}

// NewSystemIamRule creates and initializes a new SystemIamRule
func NewSystemIamRule(model SystemIamRule) *SystemIamRule {
	return data.New(&model)
}

// SystemIamRules is a type-safe collection for SystemIamRule
type SystemIamRules struct {
	base.ModelCollection[SystemIamRule, *SystemIamRule]
}

const SystemIamRulesCollectionName = "_iam_rule_"

var (
	systemIamRulesModelMu sync.Mutex
	systemIamRulesModel   *SystemIamRules
)

// InitSystemIamRulesModel must be called once at startup to configure and
// construct the SystemIamRule model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemIamRulesModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemIamRule, *SystemIamRule]) (*SystemIamRules, error) {
	systemIamRulesModelMu.Lock()
	defer systemIamRulesModelMu.Unlock()
	if systemIamRulesModel != nil {
		return systemIamRulesModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemIamRulesCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemIamRulesModel").
			WithPath("_iam_rule_")
	}
	mc, err := collection.NewModelCollection[SystemIamRule, *SystemIamRule](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemIamRulesModel").
			WithPath("_iam_rule_")
	}
	systemIamRulesModel = &SystemIamRules{ModelCollection: mc}
	return systemIamRulesModel, nil
}

// SystemIamRulesModel returns the singleton SystemIamRule model.
func SystemIamRulesModel() (*SystemIamRules, error) {
	systemIamRulesModelMu.Lock()
	defer systemIamRulesModelMu.Unlock()
	if systemIamRulesModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemIamRulesModel not initialized — call InitSystemIamRulesModel first").
			WithOperation("SystemIamRulesModel")
	}
	return systemIamRulesModel, nil
}
