package schema

// Code generated by anansi. DO NOT EDIT.
//
// This file is auto-generated from the schema definition.
// Always run codegen alongside database migrations so that the
// generated models stay in sync with the schema on file.
//
// Extend model functionality in separate Go files (e.g. system_operation_policy_utils.go).
// This file is overwritten on each codegen run — never edit it directly.

import (
	"context"
	"github.com/asaidimu/go-anansi/v8/core/common"
	"github.com/asaidimu/go-anansi/v8/core/data"
	"github.com/asaidimu/go-anansi/v8/core/persistence/base"
	"github.com/asaidimu/go-anansi/v8/core/persistence/collection"
	"go.uber.org/zap"
	"sync"
)

type SystemOperationPolicy struct {
	data.DocumentModel
	RateIdentity        string         `anansi:"rate_identity" json:"rate_identity"`
	Description         string         `anansi:"description" json:"description"`
	Rule                string         `anansi:"rule" json:"rule"`
	Key                 string         `anansi:"key" json:"key"`
	Operation           string         `anansi:"operation" json:"operation"`
	ThrottleActionMsg   string         `anansi:"throttle_action_msg" json:"throttle_action_msg"`
	TenantID            string         `anansi:"tenant_id" json:"tenant_id"`
	IntentType          string         `anansi:"intentType" json:"intentType"`
	ThrottleActionInput map[string]any `anansi:"throttle_action_input" json:"throttle_action_input"`
	RatePeriod          float64        `anansi:"rate_period" json:"rate_period"`
	ThrottleLimit       float64        `anansi:"throttle_limit" json:"throttle_limit"`
	RateCapacity        float64        `anansi:"rate_capacity" json:"rate_capacity"`
	ThrottleWindow      float64        `anansi:"throttle_window" json:"throttle_window"`
	RateRefill          float64        `anansi:"rate_refill" json:"rate_refill"`
	RateLimitEnabled    bool           `anansi:"rate_limit_enabled" json:"rate_limit_enabled"`
	Protected           bool           `anansi:"protected" json:"protected"`
	Enabled             bool           `anansi:"enabled" json:"enabled"`
}

// NewSystemOperationPolicy creates and initializes a new SystemOperationPolicy
func NewSystemOperationPolicy(model SystemOperationPolicy) *SystemOperationPolicy {
	return data.New(&model)
}

// SystemOperationPolicys is a type-safe collection for SystemOperationPolicy
type SystemOperationPolicys struct {
	base.ModelCollection[SystemOperationPolicy, *SystemOperationPolicy]
}

const SystemOperationPolicysCollectionName = "_operation_policy_"

var (
	systemOperationPolicysModelMu sync.Mutex
	systemOperationPolicysModel   *SystemOperationPolicys
)

// InitSystemOperationPolicysModel must be called once at startup to configure and
// construct the SystemOperationPolicy model. Idempotent — subsequent calls return
// the existing instance. Retry-safe: if the first call fails, the
// caller can fix the underlying issue and call again.
func InitSystemOperationPolicysModel(p base.Persistence, logger *zap.Logger, opts ...collection.ModelCollectionOptions[SystemOperationPolicy, *SystemOperationPolicy]) (*SystemOperationPolicys, error) {
	systemOperationPolicysModelMu.Lock()
	defer systemOperationPolicysModelMu.Unlock()
	if systemOperationPolicysModel != nil {
		return systemOperationPolicysModel, nil
	}
	raw, err := p.Collection(context.Background(), SystemOperationPolicysCollectionName)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemOperationPolicysModel").
			WithPath("_operation_policy_")
	}
	mc, err := collection.NewModelCollection[SystemOperationPolicy, *SystemOperationPolicy](raw, logger, opts...)
	if err != nil {
		return nil, common.SystemErrorFrom(err, "ERR_MODEL_INIT_FAILED").
			WithOperation("InitSystemOperationPolicysModel").
			WithPath("_operation_policy_")
	}
	systemOperationPolicysModel = &SystemOperationPolicys{ModelCollection: mc}
	return systemOperationPolicysModel, nil
}

// SystemOperationPolicysModel returns the singleton SystemOperationPolicy model.
func SystemOperationPolicysModel() (*SystemOperationPolicys, error) {
	systemOperationPolicysModelMu.Lock()
	defer systemOperationPolicysModelMu.Unlock()
	if systemOperationPolicysModel == nil {
		return nil, common.NewSystemError("ERR_MODEL_NOT_INITIALIZED",
			"SystemOperationPolicysModel not initialized — call InitSystemOperationPolicysModel first").
			WithOperation("SystemOperationPolicysModel")
	}
	return systemOperationPolicysModel, nil
}
