name: Test Workflow

on:
  push:
    branches-ignore:
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run test command
        run: make test
